// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package device_data

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__data_feed__tracker "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/data_feed/tracker"
	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
	solarxr_protocol__datatypes__hardware_info "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes/hardware_info"
)

// / Describes all possible information about a hardware device. For example, a
// / vive tracker is a  single hardware device, and a slime tracker with two
// / extensions is a single hardware device but two trackers.
type DeviceData struct {
	_tab flatbuffers.Table
}

func GetRootAsDeviceData(buf []byte, offset flatbuffers.UOffsetT) *DeviceData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeviceData{}
	x.Init(buf, n+offset)
	return x
}

func FinishDeviceDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDeviceData(buf []byte, offset flatbuffers.UOffsetT) *DeviceData {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeviceData{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDeviceDataBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DeviceData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeviceData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeviceData) Id(obj *solarxr_protocol__datatypes.DeviceId) *solarxr_protocol__datatypes.DeviceId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(solarxr_protocol__datatypes.DeviceId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / The dynamically changeable name of the device. This might be set by the
// / user to help them remember which tracker is which.
func (rcv *DeviceData) CustomName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / The dynamically changeable name of the device. This might be set by the
// / user to help them remember which tracker is which.
// / Mostly-static info about the device hardware
func (rcv *DeviceData) HardwareInfo(obj *solarxr_protocol__datatypes__hardware_info.HardwareInfo) *solarxr_protocol__datatypes__hardware_info.HardwareInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(solarxr_protocol__datatypes__hardware_info.HardwareInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / Mostly-static info about the device hardware
// / General info about the status of the device
func (rcv *DeviceData) HardwareStatus(obj *solarxr_protocol__datatypes__hardware_info.HardwareStatus) *solarxr_protocol__datatypes__hardware_info.HardwareStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(solarxr_protocol__datatypes__hardware_info.HardwareStatus)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / General info about the status of the device
// / Info about all trackers attached to this device
func (rcv *DeviceData) Trackers(obj *solarxr_protocol__data_feed__tracker.TrackerData, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DeviceData) TrackersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

// / Info about all trackers attached to this device
func DeviceDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func DeviceDataAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(id), 0)
}
func DeviceDataAddCustomName(builder *flatbuffers.Builder, customName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(customName), 0)
}
func DeviceDataAddHardwareInfo(builder *flatbuffers.Builder, hardwareInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(hardwareInfo), 0)
}
func DeviceDataAddHardwareStatus(builder *flatbuffers.Builder, hardwareStatus flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(hardwareStatus), 0)
}
func DeviceDataAddTrackers(builder *flatbuffers.Builder, trackers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(trackers), 0)
}
func DeviceDataStartTrackersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DeviceDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
