// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hardware_info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / A mask of the data in `FirmwareStatus`
type FirmwareStatusMask struct {
	_tab flatbuffers.Table
}

func GetRootAsFirmwareStatusMask(buf []byte, offset flatbuffers.UOffsetT) *FirmwareStatusMask {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FirmwareStatusMask{}
	x.Init(buf, n+offset)
	return x
}

func FinishFirmwareStatusMaskBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFirmwareStatusMask(buf []byte, offset flatbuffers.UOffsetT) *FirmwareStatusMask {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FirmwareStatusMask{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFirmwareStatusMaskBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FirmwareStatusMask) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FirmwareStatusMask) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FirmwareStatusMask) ErrorStatus() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FirmwareStatusMask) MutateErrorStatus(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *FirmwareStatusMask) Tps() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FirmwareStatusMask) MutateTps(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *FirmwareStatusMask) Ping() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FirmwareStatusMask) MutatePing(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *FirmwareStatusMask) Rssi() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FirmwareStatusMask) MutateRssi(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *FirmwareStatusMask) McuTemp() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FirmwareStatusMask) MutateMcuTemp(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *FirmwareStatusMask) BatteryVoltage() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FirmwareStatusMask) MutateBatteryVoltage(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func (rcv *FirmwareStatusMask) BatteryPctEstimate() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FirmwareStatusMask) MutateBatteryPctEstimate(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func (rcv *FirmwareStatusMask) BatteryRuntimeEstimate() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FirmwareStatusMask) MutateBatteryRuntimeEstimate(n bool) bool {
	return rcv._tab.MutateBoolSlot(18, n)
}

func FirmwareStatusMaskStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func FirmwareStatusMaskAddErrorStatus(builder *flatbuffers.Builder, errorStatus bool) {
	builder.PrependBoolSlot(0, errorStatus, false)
}
func FirmwareStatusMaskAddTps(builder *flatbuffers.Builder, tps bool) {
	builder.PrependBoolSlot(1, tps, false)
}
func FirmwareStatusMaskAddPing(builder *flatbuffers.Builder, ping bool) {
	builder.PrependBoolSlot(2, ping, false)
}
func FirmwareStatusMaskAddRssi(builder *flatbuffers.Builder, rssi bool) {
	builder.PrependBoolSlot(3, rssi, false)
}
func FirmwareStatusMaskAddMcuTemp(builder *flatbuffers.Builder, mcuTemp bool) {
	builder.PrependBoolSlot(4, mcuTemp, false)
}
func FirmwareStatusMaskAddBatteryVoltage(builder *flatbuffers.Builder, batteryVoltage bool) {
	builder.PrependBoolSlot(5, batteryVoltage, false)
}
func FirmwareStatusMaskAddBatteryPctEstimate(builder *flatbuffers.Builder, batteryPctEstimate bool) {
	builder.PrependBoolSlot(6, batteryPctEstimate, false)
}
func FirmwareStatusMaskAddBatteryRuntimeEstimate(builder *flatbuffers.Builder, batteryRuntimeEstimate bool) {
	builder.PrependBoolSlot(7, batteryRuntimeEstimate, false)
}
func FirmwareStatusMaskEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
