// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hardware_info

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / A MAC address or a bluetooth address, or some other uniquely identifying address
// / associated with the endpoint that we are communicating with. If it doesn't take
// / up the full set of bytes, it is aligned towards the least significant bits.
type HardwareAddress struct {
	_tab flatbuffers.Struct
}

func (rcv *HardwareAddress) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HardwareAddress) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *HardwareAddress) Addr() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *HardwareAddress) MutateAddr(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateHardwareAddress(builder *flatbuffers.Builder, addr uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 8)
	builder.PrependUint64(addr)
	return builder.Offset()
}
