// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hardware_info

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
)

// / Mostly-dynamic status info about a tracked device's firmware
type HardwareStatus struct {
	_tab flatbuffers.Table
}

func GetRootAsHardwareStatus(buf []byte, offset flatbuffers.UOffsetT) *HardwareStatus {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HardwareStatus{}
	x.Init(buf, n+offset)
	return x
}

func FinishHardwareStatusBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHardwareStatus(buf []byte, offset flatbuffers.UOffsetT) *HardwareStatus {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HardwareStatus{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHardwareStatusBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HardwareStatus) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HardwareStatus) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HardwareStatus) ErrorStatus() *solarxr_protocol__datatypes.FirmwareErrorCode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		v := solarxr_protocol__datatypes.FirmwareErrorCode(rcv._tab.GetByte(o + rcv._tab.Pos))
		return &v
	}
	return nil
}

func (rcv *HardwareStatus) MutateErrorStatus(n solarxr_protocol__datatypes.FirmwareErrorCode) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *HardwareStatus) Ping() *uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		v := rcv._tab.GetUint16(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *HardwareStatus) MutatePing(n uint16) bool {
	return rcv._tab.MutateUint16Slot(8, n)
}

// / "Received Signal Strength Indicator" between device and wifi adapter in dBm
func (rcv *HardwareStatus) Rssi() *int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		v := rcv._tab.GetInt16(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

// / "Received Signal Strength Indicator" between device and wifi adapter in dBm
func (rcv *HardwareStatus) MutateRssi(n int16) bool {
	return rcv._tab.MutateInt16Slot(10, n)
}

// / Temperature in degrees celsius
func (rcv *HardwareStatus) McuTemp() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

// / Temperature in degrees celsius
func (rcv *HardwareStatus) MutateMcuTemp(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *HardwareStatus) BatteryVoltage() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *HardwareStatus) MutateBatteryVoltage(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

func (rcv *HardwareStatus) BatteryPctEstimate() *byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		v := rcv._tab.GetByte(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *HardwareStatus) MutateBatteryPctEstimate(n byte) bool {
	return rcv._tab.MutateByteSlot(16, n)
}

func (rcv *HardwareStatus) LogData(obj *solarxr_protocol__datatypes.LogData) *solarxr_protocol__datatypes.LogData {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(solarxr_protocol__datatypes.LogData)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *HardwareStatus) PacketLoss() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *HardwareStatus) MutatePacketLoss(n float32) bool {
	return rcv._tab.MutateFloat32Slot(20, n)
}

func (rcv *HardwareStatus) PacketsLost() *int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		v := rcv._tab.GetInt32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *HardwareStatus) MutatePacketsLost(n int32) bool {
	return rcv._tab.MutateInt32Slot(22, n)
}

func (rcv *HardwareStatus) PacketsReceived() *int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		v := rcv._tab.GetInt32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *HardwareStatus) MutatePacketsReceived(n int32) bool {
	return rcv._tab.MutateInt32Slot(24, n)
}

// / Runtime estimate in microseconds
func (rcv *HardwareStatus) BatteryRuntimeEstimate() *int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		v := rcv._tab.GetInt64(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

// / Runtime estimate in microseconds
func (rcv *HardwareStatus) MutateBatteryRuntimeEstimate(n int64) bool {
	return rcv._tab.MutateInt64Slot(26, n)
}

func HardwareStatusStart(builder *flatbuffers.Builder) {
	builder.StartObject(12)
}
func HardwareStatusAddErrorStatus(builder *flatbuffers.Builder, errorStatus solarxr_protocol__datatypes.FirmwareErrorCode) {
	builder.PrependByte(byte(errorStatus))
	builder.Slot(0)
}
func HardwareStatusAddPing(builder *flatbuffers.Builder, ping uint16) {
	builder.PrependUint16(ping)
	builder.Slot(2)
}
func HardwareStatusAddRssi(builder *flatbuffers.Builder, rssi int16) {
	builder.PrependInt16(rssi)
	builder.Slot(3)
}
func HardwareStatusAddMcuTemp(builder *flatbuffers.Builder, mcuTemp float32) {
	builder.PrependFloat32(mcuTemp)
	builder.Slot(4)
}
func HardwareStatusAddBatteryVoltage(builder *flatbuffers.Builder, batteryVoltage float32) {
	builder.PrependFloat32(batteryVoltage)
	builder.Slot(5)
}
func HardwareStatusAddBatteryPctEstimate(builder *flatbuffers.Builder, batteryPctEstimate byte) {
	builder.PrependByte(batteryPctEstimate)
	builder.Slot(6)
}
func HardwareStatusAddLogData(builder *flatbuffers.Builder, logData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(logData), 0)
}
func HardwareStatusAddPacketLoss(builder *flatbuffers.Builder, packetLoss float32) {
	builder.PrependFloat32(packetLoss)
	builder.Slot(8)
}
func HardwareStatusAddPacketsLost(builder *flatbuffers.Builder, packetsLost int32) {
	builder.PrependInt32(packetsLost)
	builder.Slot(9)
}
func HardwareStatusAddPacketsReceived(builder *flatbuffers.Builder, packetsReceived int32) {
	builder.PrependInt32(packetsReceived)
	builder.Slot(10)
}
func HardwareStatusAddBatteryRuntimeEstimate(builder *flatbuffers.Builder, batteryRuntimeEstimate int64) {
	builder.PrependInt64(batteryRuntimeEstimate)
	builder.Slot(11)
}
func HardwareStatusEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
