// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hardware_info

import "strconv"

type ImuType uint16

const (
	ImuTypeOther          ImuType = 0
	ImuTypeMPU9250        ImuType = 1
	ImuTypeMPU6500        ImuType = 2
	ImuTypeBNO080         ImuType = 3
	ImuTypeBNO085         ImuType = 4
	ImuTypeBNO055         ImuType = 5
	ImuTypeMPU6050        ImuType = 6
	ImuTypeBNO086         ImuType = 7
	ImuTypeBMI160         ImuType = 8
	ImuTypeICM20948       ImuType = 9
	ImuTypeICM42688       ImuType = 10
	ImuTypeBMI270         ImuType = 11
	ImuTypeLSM6DS3TRC     ImuType = 12
	ImuTypeLSM6DSV        ImuType = 13
	ImuTypeLSM6DSO        ImuType = 14
	ImuTypeLSM6DSR        ImuType = 15
	ImuTypeICM45686       ImuType = 16
	ImuTypeICM45605       ImuType = 17
	ImuTypeADC_RESISTANCE ImuType = 18
	ImuTypeICM55686       ImuType = 19
	ImuTypeDEV_RESERVED   ImuType = 250
)

var EnumNamesImuType = map[ImuType]string{
	ImuTypeOther:          "Other",
	ImuTypeMPU9250:        "MPU9250",
	ImuTypeMPU6500:        "MPU6500",
	ImuTypeBNO080:         "BNO080",
	ImuTypeBNO085:         "BNO085",
	ImuTypeBNO055:         "BNO055",
	ImuTypeMPU6050:        "MPU6050",
	ImuTypeBNO086:         "BNO086",
	ImuTypeBMI160:         "BMI160",
	ImuTypeICM20948:       "ICM20948",
	ImuTypeICM42688:       "ICM42688",
	ImuTypeBMI270:         "BMI270",
	ImuTypeLSM6DS3TRC:     "LSM6DS3TRC",
	ImuTypeLSM6DSV:        "LSM6DSV",
	ImuTypeLSM6DSO:        "LSM6DSO",
	ImuTypeLSM6DSR:        "LSM6DSR",
	ImuTypeICM45686:       "ICM45686",
	ImuTypeICM45605:       "ICM45605",
	ImuTypeADC_RESISTANCE: "ADC_RESISTANCE",
	ImuTypeICM55686:       "ICM55686",
	ImuTypeDEV_RESERVED:   "DEV_RESERVED",
}

var EnumValuesImuType = map[string]ImuType{
	"Other":          ImuTypeOther,
	"MPU9250":        ImuTypeMPU9250,
	"MPU6500":        ImuTypeMPU6500,
	"BNO080":         ImuTypeBNO080,
	"BNO085":         ImuTypeBNO085,
	"BNO055":         ImuTypeBNO055,
	"MPU6050":        ImuTypeMPU6050,
	"BNO086":         ImuTypeBNO086,
	"BMI160":         ImuTypeBMI160,
	"ICM20948":       ImuTypeICM20948,
	"ICM42688":       ImuTypeICM42688,
	"BMI270":         ImuTypeBMI270,
	"LSM6DS3TRC":     ImuTypeLSM6DS3TRC,
	"LSM6DSV":        ImuTypeLSM6DSV,
	"LSM6DSO":        ImuTypeLSM6DSO,
	"LSM6DSR":        ImuTypeLSM6DSR,
	"ICM45686":       ImuTypeICM45686,
	"ICM45605":       ImuTypeICM45605,
	"ADC_RESISTANCE": ImuTypeADC_RESISTANCE,
	"ICM55686":       ImuTypeICM55686,
	"DEV_RESERVED":   ImuTypeDEV_RESERVED,
}

func (v ImuType) String() string {
	if s, ok := EnumNamesImuType[v]; ok {
		return s
	}
	return "ImuType(" + strconv.FormatInt(int64(v), 10) + ")"
}
