// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hardware_info

import "strconv"

type McuType uint16

const (
	McuTypeOther            McuType = 0
	McuTypeESP8266          McuType = 1
	McuTypeESP32            McuType = 2
	McuTypeOWOTRACK_ANDROID McuType = 3
	McuTypeWRANGLER         McuType = 4
	McuTypeOWOTRACK_IOS     McuType = 5
	McuTypeESP32_C3         McuType = 6
	McuTypeMOCOPI           McuType = 7
	McuTypeHARITORA         McuType = 8
	McuTypeNRF52            McuType = 9
	McuTypeNRF54L           McuType = 10
	McuTypeDEV_RESERVED     McuType = 250
)

var EnumNamesMcuType = map[McuType]string{
	McuTypeOther:            "Other",
	McuTypeESP8266:          "ESP8266",
	McuTypeESP32:            "ESP32",
	McuTypeOWOTRACK_ANDROID: "OWOTRACK_ANDROID",
	McuTypeWRANGLER:         "WRANGLER",
	McuTypeOWOTRACK_IOS:     "OWOTRACK_IOS",
	McuTypeESP32_C3:         "ESP32_C3",
	McuTypeMOCOPI:           "MOCOPI",
	McuTypeHARITORA:         "HARITORA",
	McuTypeNRF52:            "NRF52",
	McuTypeNRF54L:           "NRF54L",
	McuTypeDEV_RESERVED:     "DEV_RESERVED",
}

var EnumValuesMcuType = map[string]McuType{
	"Other":            McuTypeOther,
	"ESP8266":          McuTypeESP8266,
	"ESP32":            McuTypeESP32,
	"OWOTRACK_ANDROID": McuTypeOWOTRACK_ANDROID,
	"WRANGLER":         McuTypeWRANGLER,
	"OWOTRACK_IOS":     McuTypeOWOTRACK_IOS,
	"ESP32_C3":         McuTypeESP32_C3,
	"MOCOPI":           McuTypeMOCOPI,
	"HARITORA":         McuTypeHARITORA,
	"NRF52":            McuTypeNRF52,
	"NRF54L":           McuTypeNRF54L,
	"DEV_RESERVED":     McuTypeDEV_RESERVED,
}

func (v McuType) String() string {
	if s, ok := EnumNamesMcuType[v]; ok {
		return s
	}
	return "McuType(" + strconv.FormatInt(int64(v), 10) + ")"
}
