// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hardware_info

import "strconv"

// / What kind of data the tracker supports.The received data gets computed into a Quaternion rotation in any case.
type TrackerDataType byte

const (
	/// Rotation (e.g: IMUs or computed rotations in firmware)
	TrackerDataTypeROTATION TrackerDataType = 0
	/// Flex resistance (e.g: raw data from flex sensors or unscaled angle on a single axis)
	TrackerDataTypeFLEX_RESISTANCE TrackerDataType = 1
	/// Flex angle (e.g: computed angle from flex sensors or angle on a single axis)
	TrackerDataTypeFLEX_ANGLE TrackerDataType = 2
)

var EnumNamesTrackerDataType = map[TrackerDataType]string{
	TrackerDataTypeROTATION:        "ROTATION",
	TrackerDataTypeFLEX_RESISTANCE: "FLEX_RESISTANCE",
	TrackerDataTypeFLEX_ANGLE:      "FLEX_ANGLE",
}

var EnumValuesTrackerDataType = map[string]TrackerDataType{
	"ROTATION":        TrackerDataTypeROTATION,
	"FLEX_RESISTANCE": TrackerDataTypeFLEX_RESISTANCE,
	"FLEX_ANGLE":      TrackerDataTypeFLEX_ANGLE,
}

func (v TrackerDataType) String() string {
	if s, ok := EnumNamesTrackerDataType[v]; ok {
		return s
	}
	return "TrackerDataType(" + strconv.FormatInt(int64(v), 10) + ")"
}
