// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pub_sub

import "strconv"

type Payload byte

const (
	PayloadNONE                                   Payload = 0
	Payloadsolarxr_protocol_datatypes_StringTable Payload = 1
	Payloadsolarxr_protocol_datatypes_Bytes       Payload = 2
	PayloadKeyValues                              Payload = 3
)

var EnumNamesPayload = map[Payload]string{
	PayloadNONE: "NONE",
	Payloadsolarxr_protocol_datatypes_StringTable: "solarxr_protocol_datatypes_StringTable",
	Payloadsolarxr_protocol_datatypes_Bytes:       "solarxr_protocol_datatypes_Bytes",
	PayloadKeyValues:                              "KeyValues",
}

var EnumValuesPayload = map[string]Payload{
	"NONE":                                   PayloadNONE,
	"solarxr_protocol_datatypes_StringTable": Payloadsolarxr_protocol_datatypes_StringTable,
	"solarxr_protocol_datatypes_Bytes":       Payloadsolarxr_protocol_datatypes_Bytes,
	"KeyValues":                              PayloadKeyValues,
}

func (v Payload) String() string {
	if s, ok := EnumNamesPayload[v]; ok {
		return s
	}
	return "Payload(" + strconv.FormatInt(int64(v), 10) + ")"
}
