// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pub_sub

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PubSubHeader struct {
	_tab flatbuffers.Table
}

func GetRootAsPubSubHeader(buf []byte, offset flatbuffers.UOffsetT) *PubSubHeader {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PubSubHeader{}
	x.Init(buf, n+offset)
	return x
}

func FinishPubSubHeaderBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPubSubHeader(buf []byte, offset flatbuffers.UOffsetT) *PubSubHeader {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PubSubHeader{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPubSubHeaderBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PubSubHeader) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PubSubHeader) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PubSubHeader) UType() PubSubUnion {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return PubSubUnion(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *PubSubHeader) MutateUType(n PubSubUnion) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *PubSubHeader) U(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func PubSubHeaderStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PubSubHeaderAddUType(builder *flatbuffers.Builder, uType PubSubUnion) {
	builder.PrependByteSlot(0, byte(uType), 0)
}
func PubSubHeaderAddU(builder *flatbuffers.Builder, u flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(u), 0)
}
func PubSubHeaderEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
