// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pub_sub

import "strconv"

type PubSubUnion byte

const (
	PubSubUnionNONE                PubSubUnion = 0
	PubSubUnionMessage             PubSubUnion = 1
	PubSubUnionSubscriptionRequest PubSubUnion = 2
	PubSubUnionTopicHandleRequest  PubSubUnion = 3
	PubSubUnionTopicMapping        PubSubUnion = 4
)

var EnumNamesPubSubUnion = map[PubSubUnion]string{
	PubSubUnionNONE:                "NONE",
	PubSubUnionMessage:             "Message",
	PubSubUnionSubscriptionRequest: "SubscriptionRequest",
	PubSubUnionTopicHandleRequest:  "TopicHandleRequest",
	PubSubUnionTopicMapping:        "TopicMapping",
}

var EnumValuesPubSubUnion = map[string]PubSubUnion{
	"NONE":                PubSubUnionNONE,
	"Message":             PubSubUnionMessage,
	"SubscriptionRequest": PubSubUnionSubscriptionRequest,
	"TopicHandleRequest":  PubSubUnionTopicHandleRequest,
	"TopicMapping":        PubSubUnionTopicMapping,
}

func (v PubSubUnion) String() string {
	if s, ok := EnumNamesPubSubUnion[v]; ok {
		return s
	}
	return "PubSubUnion(" + strconv.FormatInt(int64(v), 10) + ")"
}
