// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pub_sub

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Requests a subscription to `topic`. Replies with a `TopicMapping`.
type SubscriptionRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSubscriptionRequest(buf []byte, offset flatbuffers.UOffsetT) *SubscriptionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SubscriptionRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSubscriptionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSubscriptionRequest(buf []byte, offset flatbuffers.UOffsetT) *SubscriptionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SubscriptionRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSubscriptionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SubscriptionRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SubscriptionRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SubscriptionRequest) TopicType() Topic {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Topic(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *SubscriptionRequest) MutateTopicType(n Topic) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *SubscriptionRequest) Topic(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func SubscriptionRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SubscriptionRequestAddTopicType(builder *flatbuffers.Builder, topicType Topic) {
	builder.PrependByteSlot(0, byte(topicType), 0)
}
func SubscriptionRequestAddTopic(builder *flatbuffers.Builder, topic flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(topic), 0)
}
func SubscriptionRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
