// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pub_sub

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Response for `TopicHandleRequest` or `SubscriptionRequest`.
type TopicMapping struct {
	_tab flatbuffers.Table
}

func GetRootAsTopicMapping(buf []byte, offset flatbuffers.UOffsetT) *TopicMapping {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TopicMapping{}
	x.Init(buf, n+offset)
	return x
}

func FinishTopicMappingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTopicMapping(buf []byte, offset flatbuffers.UOffsetT) *TopicMapping {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TopicMapping{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTopicMappingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TopicMapping) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TopicMapping) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TopicMapping) Id(obj *TopicId) *TopicId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TopicId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TopicMapping) Handle(obj *TopicHandle) *TopicHandle {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TopicHandle)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TopicMappingStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TopicMappingAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func TopicMappingAddHandle(builder *flatbuffers.Builder, handle flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(handle), 0)
}
func TopicMappingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
