// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pub_sub

import "strconv"

type Topic byte

const (
	TopicNONE        Topic = 0
	TopicTopicHandle Topic = 1
	TopicTopicId     Topic = 2
)

var EnumNamesTopic = map[Topic]string{
	TopicNONE:        "NONE",
	TopicTopicHandle: "TopicHandle",
	TopicTopicId:     "TopicId",
}

var EnumValuesTopic = map[string]Topic{
	"NONE":        TopicNONE,
	"TopicHandle": TopicTopicHandle,
	"TopicId":     TopicTopicId,
}

func (v Topic) String() string {
	if s, ok := EnumNamesTopic[v]; ok {
		return s
	}
	return "Topic(" + strconv.FormatInt(int64(v), 10) + ")"
}
