// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pub_sub

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / A handle for the topic, allows referencing a topic without sending a huge
// / `TopicId`.
type TopicHandle struct {
	_tab flatbuffers.Table
}

func GetRootAsTopicHandle(buf []byte, offset flatbuffers.UOffsetT) *TopicHandle {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TopicHandle{}
	x.Init(buf, n+offset)
	return x
}

func FinishTopicHandleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTopicHandle(buf []byte, offset flatbuffers.UOffsetT) *TopicHandle {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TopicHandle{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTopicHandleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TopicHandle) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TopicHandle) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TopicHandle) Id() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TopicHandle) MutateId(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func TopicHandleStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TopicHandleAddId(builder *flatbuffers.Builder, id uint16) {
	builder.PrependUint16Slot(0, id, 0)
}
func TopicHandleEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
