name: camesura
description: "SlimeVRのYaw Resetを正しい姿勢で行うための補助アプリ。"
publish_to: 'none'
version: 0.4.0+6

environment:
  sdk: ^3.13.3

dependencies:
  camera: 0.12.1
  flutter:
    sdk: flutter
  google_mlkit_commons: 0.13.0
  google_mlkit_pose_detection: 0.16.1
  shared_preferences: 2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
