name: camesura
description: "SlimeVRのYaw Resetを正しい姿勢で行うための補助アプリ。"
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
