// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datatypes

import "strconv"

// / Different parts of the body. Maps to each possible non-tracker bone in the skeleton.
// / These are *NOT* the trackers.
type BodyPart byte

const (
	BodyPartNONE                      BodyPart = 0
	BodyPartHEAD                      BodyPart = 1
	BodyPartNECK                      BodyPart = 2
	BodyPartCHEST                     BodyPart = 3
	BodyPartWAIST                     BodyPart = 4
	BodyPartHIP                       BodyPart = 5
	BodyPartLEFT_UPPER_LEG            BodyPart = 6
	BodyPartRIGHT_UPPER_LEG           BodyPart = 7
	BodyPartLEFT_LOWER_LEG            BodyPart = 8
	BodyPartRIGHT_LOWER_LEG           BodyPart = 9
	BodyPartLEFT_FOOT                 BodyPart = 10
	BodyPartRIGHT_FOOT                BodyPart = 11
	BodyPartLEFT_LOWER_ARM            BodyPart = 14
	BodyPartRIGHT_LOWER_ARM           BodyPart = 15
	BodyPartLEFT_UPPER_ARM            BodyPart = 16
	BodyPartRIGHT_UPPER_ARM           BodyPart = 17
	BodyPartLEFT_HAND                 BodyPart = 18
	BodyPartRIGHT_HAND                BodyPart = 19
	BodyPartLEFT_SHOULDER             BodyPart = 20
	BodyPartRIGHT_SHOULDER            BodyPart = 21
	BodyPartUPPER_CHEST               BodyPart = 22
	BodyPartLEFT_HIP                  BodyPart = 23
	BodyPartRIGHT_HIP                 BodyPart = 24
	BodyPartLEFT_THUMB_METACARPAL     BodyPart = 25
	BodyPartLEFT_THUMB_PROXIMAL       BodyPart = 26
	BodyPartLEFT_THUMB_DISTAL         BodyPart = 27
	BodyPartLEFT_INDEX_PROXIMAL       BodyPart = 28
	BodyPartLEFT_INDEX_INTERMEDIATE   BodyPart = 29
	BodyPartLEFT_INDEX_DISTAL         BodyPart = 30
	BodyPartLEFT_MIDDLE_PROXIMAL      BodyPart = 31
	BodyPartLEFT_MIDDLE_INTERMEDIATE  BodyPart = 32
	BodyPartLEFT_MIDDLE_DISTAL        BodyPart = 33
	BodyPartLEFT_RING_PROXIMAL        BodyPart = 34
	BodyPartLEFT_RING_INTERMEDIATE    BodyPart = 35
	BodyPartLEFT_RING_DISTAL          BodyPart = 36
	BodyPartLEFT_LITTLE_PROXIMAL      BodyPart = 37
	BodyPartLEFT_LITTLE_INTERMEDIATE  BodyPart = 38
	BodyPartLEFT_LITTLE_DISTAL        BodyPart = 39
	BodyPartRIGHT_THUMB_METACARPAL    BodyPart = 40
	BodyPartRIGHT_THUMB_PROXIMAL      BodyPart = 41
	BodyPartRIGHT_THUMB_DISTAL        BodyPart = 42
	BodyPartRIGHT_INDEX_PROXIMAL      BodyPart = 43
	BodyPartRIGHT_INDEX_INTERMEDIATE  BodyPart = 44
	BodyPartRIGHT_INDEX_DISTAL        BodyPart = 45
	BodyPartRIGHT_MIDDLE_PROXIMAL     BodyPart = 46
	BodyPartRIGHT_MIDDLE_INTERMEDIATE BodyPart = 47
	BodyPartRIGHT_MIDDLE_DISTAL       BodyPart = 48
	BodyPartRIGHT_RING_PROXIMAL       BodyPart = 49
	BodyPartRIGHT_RING_INTERMEDIATE   BodyPart = 50
	BodyPartRIGHT_RING_DISTAL         BodyPart = 51
	BodyPartRIGHT_LITTLE_PROXIMAL     BodyPart = 52
	BodyPartRIGHT_LITTLE_INTERMEDIATE BodyPart = 53
	BodyPartRIGHT_LITTLE_DISTAL       BodyPart = 54
)

var EnumNamesBodyPart = map[BodyPart]string{
	BodyPartNONE:                      "NONE",
	BodyPartHEAD:                      "HEAD",
	BodyPartNECK:                      "NECK",
	BodyPartCHEST:                     "CHEST",
	BodyPartWAIST:                     "WAIST",
	BodyPartHIP:                       "HIP",
	BodyPartLEFT_UPPER_LEG:            "LEFT_UPPER_LEG",
	BodyPartRIGHT_UPPER_LEG:           "RIGHT_UPPER_LEG",
	BodyPartLEFT_LOWER_LEG:            "LEFT_LOWER_LEG",
	BodyPartRIGHT_LOWER_LEG:           "RIGHT_LOWER_LEG",
	BodyPartLEFT_FOOT:                 "LEFT_FOOT",
	BodyPartRIGHT_FOOT:                "RIGHT_FOOT",
	BodyPartLEFT_LOWER_ARM:            "LEFT_LOWER_ARM",
	BodyPartRIGHT_LOWER_ARM:           "RIGHT_LOWER_ARM",
	BodyPartLEFT_UPPER_ARM:            "LEFT_UPPER_ARM",
	BodyPartRIGHT_UPPER_ARM:           "RIGHT_UPPER_ARM",
	BodyPartLEFT_HAND:                 "LEFT_HAND",
	BodyPartRIGHT_HAND:                "RIGHT_HAND",
	BodyPartLEFT_SHOULDER:             "LEFT_SHOULDER",
	BodyPartRIGHT_SHOULDER:            "RIGHT_SHOULDER",
	BodyPartUPPER_CHEST:               "UPPER_CHEST",
	BodyPartLEFT_HIP:                  "LEFT_HIP",
	BodyPartRIGHT_HIP:                 "RIGHT_HIP",
	BodyPartLEFT_THUMB_METACARPAL:     "LEFT_THUMB_METACARPAL",
	BodyPartLEFT_THUMB_PROXIMAL:       "LEFT_THUMB_PROXIMAL",
	BodyPartLEFT_THUMB_DISTAL:         "LEFT_THUMB_DISTAL",
	BodyPartLEFT_INDEX_PROXIMAL:       "LEFT_INDEX_PROXIMAL",
	BodyPartLEFT_INDEX_INTERMEDIATE:   "LEFT_INDEX_INTERMEDIATE",
	BodyPartLEFT_INDEX_DISTAL:         "LEFT_INDEX_DISTAL",
	BodyPartLEFT_MIDDLE_PROXIMAL:      "LEFT_MIDDLE_PROXIMAL",
	BodyPartLEFT_MIDDLE_INTERMEDIATE:  "LEFT_MIDDLE_INTERMEDIATE",
	BodyPartLEFT_MIDDLE_DISTAL:        "LEFT_MIDDLE_DISTAL",
	BodyPartLEFT_RING_PROXIMAL:        "LEFT_RING_PROXIMAL",
	BodyPartLEFT_RING_INTERMEDIATE:    "LEFT_RING_INTERMEDIATE",
	BodyPartLEFT_RING_DISTAL:          "LEFT_RING_DISTAL",
	BodyPartLEFT_LITTLE_PROXIMAL:      "LEFT_LITTLE_PROXIMAL",
	BodyPartLEFT_LITTLE_INTERMEDIATE:  "LEFT_LITTLE_INTERMEDIATE",
	BodyPartLEFT_LITTLE_DISTAL:        "LEFT_LITTLE_DISTAL",
	BodyPartRIGHT_THUMB_METACARPAL:    "RIGHT_THUMB_METACARPAL",
	BodyPartRIGHT_THUMB_PROXIMAL:      "RIGHT_THUMB_PROXIMAL",
	BodyPartRIGHT_THUMB_DISTAL:        "RIGHT_THUMB_DISTAL",
	BodyPartRIGHT_INDEX_PROXIMAL:      "RIGHT_INDEX_PROXIMAL",
	BodyPartRIGHT_INDEX_INTERMEDIATE:  "RIGHT_INDEX_INTERMEDIATE",
	BodyPartRIGHT_INDEX_DISTAL:        "RIGHT_INDEX_DISTAL",
	BodyPartRIGHT_MIDDLE_PROXIMAL:     "RIGHT_MIDDLE_PROXIMAL",
	BodyPartRIGHT_MIDDLE_INTERMEDIATE: "RIGHT_MIDDLE_INTERMEDIATE",
	BodyPartRIGHT_MIDDLE_DISTAL:       "RIGHT_MIDDLE_DISTAL",
	BodyPartRIGHT_RING_PROXIMAL:       "RIGHT_RING_PROXIMAL",
	BodyPartRIGHT_RING_INTERMEDIATE:   "RIGHT_RING_INTERMEDIATE",
	BodyPartRIGHT_RING_DISTAL:         "RIGHT_RING_DISTAL",
	BodyPartRIGHT_LITTLE_PROXIMAL:     "RIGHT_LITTLE_PROXIMAL",
	BodyPartRIGHT_LITTLE_INTERMEDIATE: "RIGHT_LITTLE_INTERMEDIATE",
	BodyPartRIGHT_LITTLE_DISTAL:       "RIGHT_LITTLE_DISTAL",
}

var EnumValuesBodyPart = map[string]BodyPart{
	"NONE":                      BodyPartNONE,
	"HEAD":                      BodyPartHEAD,
	"NECK":                      BodyPartNECK,
	"CHEST":                     BodyPartCHEST,
	"WAIST":                     BodyPartWAIST,
	"HIP":                       BodyPartHIP,
	"LEFT_UPPER_LEG":            BodyPartLEFT_UPPER_LEG,
	"RIGHT_UPPER_LEG":           BodyPartRIGHT_UPPER_LEG,
	"LEFT_LOWER_LEG":            BodyPartLEFT_LOWER_LEG,
	"RIGHT_LOWER_LEG":           BodyPartRIGHT_LOWER_LEG,
	"LEFT_FOOT":                 BodyPartLEFT_FOOT,
	"RIGHT_FOOT":                BodyPartRIGHT_FOOT,
	"LEFT_LOWER_ARM":            BodyPartLEFT_LOWER_ARM,
	"RIGHT_LOWER_ARM":           BodyPartRIGHT_LOWER_ARM,
	"LEFT_UPPER_ARM":            BodyPartLEFT_UPPER_ARM,
	"RIGHT_UPPER_ARM":           BodyPartRIGHT_UPPER_ARM,
	"LEFT_HAND":                 BodyPartLEFT_HAND,
	"RIGHT_HAND":                BodyPartRIGHT_HAND,
	"LEFT_SHOULDER":             BodyPartLEFT_SHOULDER,
	"RIGHT_SHOULDER":            BodyPartRIGHT_SHOULDER,
	"UPPER_CHEST":               BodyPartUPPER_CHEST,
	"LEFT_HIP":                  BodyPartLEFT_HIP,
	"RIGHT_HIP":                 BodyPartRIGHT_HIP,
	"LEFT_THUMB_METACARPAL":     BodyPartLEFT_THUMB_METACARPAL,
	"LEFT_THUMB_PROXIMAL":       BodyPartLEFT_THUMB_PROXIMAL,
	"LEFT_THUMB_DISTAL":         BodyPartLEFT_THUMB_DISTAL,
	"LEFT_INDEX_PROXIMAL":       BodyPartLEFT_INDEX_PROXIMAL,
	"LEFT_INDEX_INTERMEDIATE":   BodyPartLEFT_INDEX_INTERMEDIATE,
	"LEFT_INDEX_DISTAL":         BodyPartLEFT_INDEX_DISTAL,
	"LEFT_MIDDLE_PROXIMAL":      BodyPartLEFT_MIDDLE_PROXIMAL,
	"LEFT_MIDDLE_INTERMEDIATE":  BodyPartLEFT_MIDDLE_INTERMEDIATE,
	"LEFT_MIDDLE_DISTAL":        BodyPartLEFT_MIDDLE_DISTAL,
	"LEFT_RING_PROXIMAL":        BodyPartLEFT_RING_PROXIMAL,
	"LEFT_RING_INTERMEDIATE":    BodyPartLEFT_RING_INTERMEDIATE,
	"LEFT_RING_DISTAL":          BodyPartLEFT_RING_DISTAL,
	"LEFT_LITTLE_PROXIMAL":      BodyPartLEFT_LITTLE_PROXIMAL,
	"LEFT_LITTLE_INTERMEDIATE":  BodyPartLEFT_LITTLE_INTERMEDIATE,
	"LEFT_LITTLE_DISTAL":        BodyPartLEFT_LITTLE_DISTAL,
	"RIGHT_THUMB_METACARPAL":    BodyPartRIGHT_THUMB_METACARPAL,
	"RIGHT_THUMB_PROXIMAL":      BodyPartRIGHT_THUMB_PROXIMAL,
	"RIGHT_THUMB_DISTAL":        BodyPartRIGHT_THUMB_DISTAL,
	"RIGHT_INDEX_PROXIMAL":      BodyPartRIGHT_INDEX_PROXIMAL,
	"RIGHT_INDEX_INTERMEDIATE":  BodyPartRIGHT_INDEX_INTERMEDIATE,
	"RIGHT_INDEX_DISTAL":        BodyPartRIGHT_INDEX_DISTAL,
	"RIGHT_MIDDLE_PROXIMAL":     BodyPartRIGHT_MIDDLE_PROXIMAL,
	"RIGHT_MIDDLE_INTERMEDIATE": BodyPartRIGHT_MIDDLE_INTERMEDIATE,
	"RIGHT_MIDDLE_DISTAL":       BodyPartRIGHT_MIDDLE_DISTAL,
	"RIGHT_RING_PROXIMAL":       BodyPartRIGHT_RING_PROXIMAL,
	"RIGHT_RING_INTERMEDIATE":   BodyPartRIGHT_RING_INTERMEDIATE,
	"RIGHT_RING_DISTAL":         BodyPartRIGHT_RING_DISTAL,
	"RIGHT_LITTLE_PROXIMAL":     BodyPartRIGHT_LITTLE_PROXIMAL,
	"RIGHT_LITTLE_INTERMEDIATE": BodyPartRIGHT_LITTLE_INTERMEDIATE,
	"RIGHT_LITTLE_DISTAL":       BodyPartRIGHT_LITTLE_DISTAL,
}

func (v BodyPart) String() string {
	if s, ok := EnumNamesBodyPart[v]; ok {
		return s
	}
	return "BodyPart(" + strconv.FormatInt(int64(v), 10) + ")"
}
