// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datatypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / To be used inside unions
type DeviceIdTable struct {
	_tab flatbuffers.Table
}

func GetRootAsDeviceIdTable(buf []byte, offset flatbuffers.UOffsetT) *DeviceIdTable {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeviceIdTable{}
	x.Init(buf, n+offset)
	return x
}

func FinishDeviceIdTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDeviceIdTable(buf []byte, offset flatbuffers.UOffsetT) *DeviceIdTable {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeviceIdTable{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDeviceIdTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DeviceIdTable) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeviceIdTable) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeviceIdTable) Id(obj *DeviceId) *DeviceId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(DeviceId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func DeviceIdTableStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DeviceIdTableAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(id), 0)
}
func DeviceIdTableEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
