// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datatypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / A unique ID for the device. IDs are not guaranteed to be the same after
// / the connection is terminated.
type DeviceId struct {
	_tab flatbuffers.Struct
}

func (rcv *DeviceId) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeviceId) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *DeviceId) Id() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *DeviceId) MutateId(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateDeviceId(builder *flatbuffers.Builder, id byte) flatbuffers.UOffsetT {
	builder.Prep(1, 1)
	builder.PrependByte(id)
	return builder.Offset()
}
