// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datatypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Frequency as 32 bit float
type HzF32 struct {
	_tab flatbuffers.Struct
}

func (rcv *HzF32) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HzF32) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *HzF32) F() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *HzF32) MutateF(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateHzF32(builder *flatbuffers.Builder, f float32) flatbuffers.UOffsetT {
	builder.Prep(4, 4)
	builder.PrependFloat32(f)
	return builder.Offset()
}
