// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datatypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / The 4 bytes of an ip address are stored in 32 bits in big endian order.
// / We will switch over to fixed size arrays when they are supported better.
type Ipv4Address struct {
	_tab flatbuffers.Struct
}

func (rcv *Ipv4Address) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Ipv4Address) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Ipv4Address) Addr() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Ipv4Address) MutateAddr(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateIpv4Address(builder *flatbuffers.Builder, addr uint32) flatbuffers.UOffsetT {
	builder.Prep(4, 4)
	builder.PrependUint32(addr)
	return builder.Offset()
}
