// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datatypes

import "strconv"

type MagnetometerStatus byte

const (
	MagnetometerStatusNOT_SUPPORTED MagnetometerStatus = 0
	MagnetometerStatusDISABLED      MagnetometerStatus = 1
	MagnetometerStatusENABLED       MagnetometerStatus = 2
)

var EnumNamesMagnetometerStatus = map[MagnetometerStatus]string{
	MagnetometerStatusNOT_SUPPORTED: "NOT_SUPPORTED",
	MagnetometerStatusDISABLED:      "DISABLED",
	MagnetometerStatusENABLED:       "ENABLED",
}

var EnumValuesMagnetometerStatus = map[string]MagnetometerStatus{
	"NOT_SUPPORTED": MagnetometerStatusNOT_SUPPORTED,
	"DISABLED":      MagnetometerStatusDISABLED,
	"ENABLED":       MagnetometerStatusENABLED,
}

func (v MagnetometerStatus) String() string {
	if s, ok := EnumNamesMagnetometerStatus[v]; ok {
		return s
	}
	return "MagnetometerStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
