// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datatypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StringTable struct {
	_tab flatbuffers.Table
}

func GetRootAsStringTable(buf []byte, offset flatbuffers.UOffsetT) *StringTable {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StringTable{}
	x.Init(buf, n+offset)
	return x
}

func FinishStringTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStringTable(buf []byte, offset flatbuffers.UOffsetT) *StringTable {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StringTable{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStringTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StringTable) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StringTable) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StringTable) S() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StringTableStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StringTableAddS(builder *flatbuffers.Builder, s flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(s), 0)
}
func StringTableEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
