// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datatypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Temperature in degrees celsius
type Temperature struct {
	_tab flatbuffers.Struct
}

func (rcv *Temperature) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Temperature) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Temperature) Temp() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Temperature) MutateTemp(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateTemperature(builder *flatbuffers.Builder, temp float32) flatbuffers.UOffsetT {
	builder.Prep(4, 4)
	builder.PrependFloat32(temp)
	return builder.Offset()
}
