// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datatypes

import "strconv"

type TrackerStatus byte

const (
	TrackerStatusNONE         TrackerStatus = 0
	TrackerStatusDISCONNECTED TrackerStatus = 1
	TrackerStatusOK           TrackerStatus = 2
	TrackerStatusBUSY         TrackerStatus = 3
	TrackerStatusERROR        TrackerStatus = 4
	TrackerStatusOCCLUDED     TrackerStatus = 5
	TrackerStatusTIMED_OUT    TrackerStatus = 6
)

var EnumNamesTrackerStatus = map[TrackerStatus]string{
	TrackerStatusNONE:         "NONE",
	TrackerStatusDISCONNECTED: "DISCONNECTED",
	TrackerStatusOK:           "OK",
	TrackerStatusBUSY:         "BUSY",
	TrackerStatusERROR:        "ERROR",
	TrackerStatusOCCLUDED:     "OCCLUDED",
	TrackerStatusTIMED_OUT:    "TIMED_OUT",
}

var EnumValuesTrackerStatus = map[string]TrackerStatus{
	"NONE":         TrackerStatusNONE,
	"DISCONNECTED": TrackerStatusDISCONNECTED,
	"OK":           TrackerStatusOK,
	"BUSY":         TrackerStatusBUSY,
	"ERROR":        TrackerStatusERROR,
	"OCCLUDED":     TrackerStatusOCCLUDED,
	"TIMED_OUT":    TrackerStatusTIMED_OUT,
}

func (v TrackerStatus) String() string {
	if s, ok := EnumNamesTrackerStatus[v]; ok {
		return s
	}
	return "TrackerStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
