// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datatypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TrackerId struct {
	_tab flatbuffers.Table
}

func GetRootAsTrackerId(buf []byte, offset flatbuffers.UOffsetT) *TrackerId {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TrackerId{}
	x.Init(buf, n+offset)
	return x
}

func FinishTrackerIdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTrackerId(buf []byte, offset flatbuffers.UOffsetT) *TrackerId {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TrackerId{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTrackerIdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TrackerId) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TrackerId) Table() flatbuffers.Table {
	return rcv._tab
}

// / The device the tracker is associated with. If there is no hardware device it is
// / associated with, this should be `null`.
func (rcv *TrackerId) DeviceId(obj *DeviceId) *DeviceId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(DeviceId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / The device the tracker is associated with. If there is no hardware device it is
// / associated with, this should be `null`.
// / There are possibly multiple trackers per device. This identifies which one.
func (rcv *TrackerId) TrackerNum() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

// / There are possibly multiple trackers per device. This identifies which one.
func (rcv *TrackerId) MutateTrackerNum(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func TrackerIdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TrackerIdAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(deviceId), 0)
}
func TrackerIdAddTrackerNum(builder *flatbuffers.Builder, trackerNum byte) {
	builder.PrependByteSlot(1, trackerNum, 0)
}
func TrackerIdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
