// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package datatypes

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransactionId struct {
	_tab flatbuffers.Struct
}

func (rcv *TransactionId) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransactionId) Table() flatbuffers.Table {
	return rcv._tab.Table
}

// / This is expected to overflow, networking logic should handle this case.
func (rcv *TransactionId) Id() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}

// / This is expected to overflow, networking logic should handle this case.
func (rcv *TransactionId) MutateId(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateTransactionId(builder *flatbuffers.Builder, id uint32) flatbuffers.UOffsetT {
	builder.Prep(4, 4)
	builder.PrependUint32(id)
	return builder.Offset()
}
