// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stay_aligned

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StayAlignedTracker struct {
	_tab flatbuffers.Table
}

func GetRootAsStayAlignedTracker(buf []byte, offset flatbuffers.UOffsetT) *StayAlignedTracker {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StayAlignedTracker{}
	x.Init(buf, n+offset)
	return x
}

func FinishStayAlignedTrackerBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStayAlignedTracker(buf []byte, offset flatbuffers.UOffsetT) *StayAlignedTracker {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StayAlignedTracker{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStayAlignedTrackerBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StayAlignedTracker) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StayAlignedTracker) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StayAlignedTracker) YawCorrectionInDeg() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StayAlignedTracker) MutateYawCorrectionInDeg(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *StayAlignedTracker) LockedErrorInDeg() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StayAlignedTracker) MutateLockedErrorInDeg(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *StayAlignedTracker) CenterErrorInDeg() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StayAlignedTracker) MutateCenterErrorInDeg(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *StayAlignedTracker) NeighborErrorInDeg() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StayAlignedTracker) MutateNeighborErrorInDeg(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *StayAlignedTracker) Locked() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StayAlignedTracker) MutateLocked(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func StayAlignedTrackerStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func StayAlignedTrackerAddYawCorrectionInDeg(builder *flatbuffers.Builder, yawCorrectionInDeg float32) {
	builder.PrependFloat32Slot(0, yawCorrectionInDeg, 0.0)
}
func StayAlignedTrackerAddLockedErrorInDeg(builder *flatbuffers.Builder, lockedErrorInDeg float32) {
	builder.PrependFloat32Slot(1, lockedErrorInDeg, 0.0)
}
func StayAlignedTrackerAddCenterErrorInDeg(builder *flatbuffers.Builder, centerErrorInDeg float32) {
	builder.PrependFloat32Slot(2, centerErrorInDeg, 0.0)
}
func StayAlignedTrackerAddNeighborErrorInDeg(builder *flatbuffers.Builder, neighborErrorInDeg float32) {
	builder.PrependFloat32Slot(3, neighborErrorInDeg, 0.0)
}
func StayAlignedTrackerAddLocked(builder *flatbuffers.Builder, locked bool) {
	builder.PrependBoolSlot(4, locked, false)
}
func StayAlignedTrackerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
