// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tracker

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
	solarxr_protocol__datatypes__hardware_info "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes/hardware_info"
	solarxr_protocol__datatypes__math "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes/math"
)

// / Static description of a tracker
type TrackerInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsTrackerInfo(buf []byte, offset flatbuffers.UOffsetT) *TrackerInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TrackerInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishTrackerInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTrackerInfo(buf []byte, offset flatbuffers.UOffsetT) *TrackerInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TrackerInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTrackerInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TrackerInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TrackerInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TrackerInfo) ImuType() solarxr_protocol__datatypes__hardware_info.ImuType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return solarxr_protocol__datatypes__hardware_info.ImuType(rcv._tab.GetUint16(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TrackerInfo) MutateImuType(n solarxr_protocol__datatypes__hardware_info.ImuType) bool {
	return rcv._tab.MutateUint16Slot(4, uint16(n))
}

// / The user-assigned role of the tracker.
func (rcv *TrackerInfo) BodyPart() solarxr_protocol__datatypes.BodyPart {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return solarxr_protocol__datatypes.BodyPart(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

// / The user-assigned role of the tracker.
func (rcv *TrackerInfo) MutateBodyPart(n solarxr_protocol__datatypes.BodyPart) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

// / average samples per second
func (rcv *TrackerInfo) PollRate(obj *solarxr_protocol__datatypes.HzF32) *solarxr_protocol__datatypes.HzF32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(solarxr_protocol__datatypes.HzF32)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / average samples per second
// / The orientation of the tracker when mounted on the body
func (rcv *TrackerInfo) MountingOrientation(obj *solarxr_protocol__datatypes__math.Quat) *solarxr_protocol__datatypes__math.Quat {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(solarxr_protocol__datatypes__math.Quat)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / The orientation of the tracker when mounted on the body
// / Should the tracker's settings be editable by the user
func (rcv *TrackerInfo) Editable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

// / Should the tracker's settings be editable by the user
func (rcv *TrackerInfo) MutateEditable(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

// / Indicates if the tracker is computed (solved position and rotation)
func (rcv *TrackerInfo) IsComputed() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

// / Indicates if the tracker is computed (solved position and rotation)
func (rcv *TrackerInfo) MutateIsComputed(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

// / Indicates if the tracker is using an IMU for its tracking data
func (rcv *TrackerInfo) IsImu() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

// / Indicates if the tracker is using an IMU for its tracking data
func (rcv *TrackerInfo) MutateIsImu(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

// / A human-friendly name to display as the name of the tracker.
func (rcv *TrackerInfo) DisplayName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / A human-friendly name to display as the name of the tracker.
// / name to display as the name of the tracker set by the user
func (rcv *TrackerInfo) CustomName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / name to display as the name of the tracker set by the user
// / Whether to allow yaw drift compensation for this tracker or not.
func (rcv *TrackerInfo) AllowDriftCompensation() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

// / Whether to allow yaw drift compensation for this tracker or not.
func (rcv *TrackerInfo) MutateAllowDriftCompensation(n bool) bool {
	return rcv._tab.MutateBoolSlot(22, n)
}

// / Mounting Reset orientation overrides the current `mounting_orientation` of
// / the tracker, this orientation is not saved and needs to be calculated
// / each time the server is ran
func (rcv *TrackerInfo) MountingResetOrientation(obj *solarxr_protocol__datatypes__math.Quat) *solarxr_protocol__datatypes__math.Quat {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(solarxr_protocol__datatypes__math.Quat)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / Mounting Reset orientation overrides the current `mounting_orientation` of
// / the tracker, this orientation is not saved and needs to be calculated
// / each time the server is ran
// / Indicates if the tracker is actually an HMD
func (rcv *TrackerInfo) IsHmd() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

// / Indicates if the tracker is actually an HMD
func (rcv *TrackerInfo) MutateIsHmd(n bool) bool {
	return rcv._tab.MutateBoolSlot(26, n)
}

func (rcv *TrackerInfo) Magnetometer() solarxr_protocol__datatypes.MagnetometerStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return solarxr_protocol__datatypes.MagnetometerStatus(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TrackerInfo) MutateMagnetometer(n solarxr_protocol__datatypes.MagnetometerStatus) bool {
	return rcv._tab.MutateByteSlot(28, byte(n))
}

// / Indicates what type of data the tracker sends (note: it always ends up being rotation in the end)
func (rcv *TrackerInfo) DataSupport() solarxr_protocol__datatypes__hardware_info.TrackerDataType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return solarxr_protocol__datatypes__hardware_info.TrackerDataType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

// / Indicates what type of data the tracker sends (note: it always ends up being rotation in the end)
func (rcv *TrackerInfo) MutateDataSupport(n solarxr_protocol__datatypes__hardware_info.TrackerDataType) bool {
	return rcv._tab.MutateByteSlot(30, byte(n))
}

func TrackerInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(14)
}
func TrackerInfoAddImuType(builder *flatbuffers.Builder, imuType solarxr_protocol__datatypes__hardware_info.ImuType) {
	builder.PrependUint16Slot(0, uint16(imuType), 0)
}
func TrackerInfoAddBodyPart(builder *flatbuffers.Builder, bodyPart solarxr_protocol__datatypes.BodyPart) {
	builder.PrependByteSlot(1, byte(bodyPart), 0)
}
func TrackerInfoAddPollRate(builder *flatbuffers.Builder, pollRate flatbuffers.UOffsetT) {
	builder.PrependStructSlot(2, flatbuffers.UOffsetT(pollRate), 0)
}
func TrackerInfoAddMountingOrientation(builder *flatbuffers.Builder, mountingOrientation flatbuffers.UOffsetT) {
	builder.PrependStructSlot(3, flatbuffers.UOffsetT(mountingOrientation), 0)
}
func TrackerInfoAddEditable(builder *flatbuffers.Builder, editable bool) {
	builder.PrependBoolSlot(4, editable, false)
}
func TrackerInfoAddIsComputed(builder *flatbuffers.Builder, isComputed bool) {
	builder.PrependBoolSlot(5, isComputed, false)
}
func TrackerInfoAddIsImu(builder *flatbuffers.Builder, isImu bool) {
	builder.PrependBoolSlot(6, isImu, false)
}
func TrackerInfoAddDisplayName(builder *flatbuffers.Builder, displayName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(displayName), 0)
}
func TrackerInfoAddCustomName(builder *flatbuffers.Builder, customName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(customName), 0)
}
func TrackerInfoAddAllowDriftCompensation(builder *flatbuffers.Builder, allowDriftCompensation bool) {
	builder.PrependBoolSlot(9, allowDriftCompensation, false)
}
func TrackerInfoAddMountingResetOrientation(builder *flatbuffers.Builder, mountingResetOrientation flatbuffers.UOffsetT) {
	builder.PrependStructSlot(10, flatbuffers.UOffsetT(mountingResetOrientation), 0)
}
func TrackerInfoAddIsHmd(builder *flatbuffers.Builder, isHmd bool) {
	builder.PrependBoolSlot(11, isHmd, false)
}
func TrackerInfoAddMagnetometer(builder *flatbuffers.Builder, magnetometer solarxr_protocol__datatypes.MagnetometerStatus) {
	builder.PrependByteSlot(12, byte(magnetometer), 0)
}
func TrackerInfoAddDataSupport(builder *flatbuffers.Builder, dataSupport solarxr_protocol__datatypes__hardware_info.TrackerDataType) {
	builder.PrependByteSlot(13, byte(dataSupport), 0)
}
func TrackerInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
