// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tracker

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / A mask of the different components in `TrackerComponent`
type TrackerDataMask struct {
	_tab flatbuffers.Table
}

func GetRootAsTrackerDataMask(buf []byte, offset flatbuffers.UOffsetT) *TrackerDataMask {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TrackerDataMask{}
	x.Init(buf, n+offset)
	return x
}

func FinishTrackerDataMaskBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTrackerDataMask(buf []byte, offset flatbuffers.UOffsetT) *TrackerDataMask {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TrackerDataMask{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTrackerDataMaskBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TrackerDataMask) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TrackerDataMask) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TrackerDataMask) Info() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TrackerDataMask) MutateInfo(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *TrackerDataMask) Status() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TrackerDataMask) MutateStatus(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *TrackerDataMask) Rotation() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TrackerDataMask) MutateRotation(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *TrackerDataMask) Position() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TrackerDataMask) MutatePosition(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *TrackerDataMask) RawAngularVelocity() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TrackerDataMask) MutateRawAngularVelocity(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *TrackerDataMask) RawAcceleration() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TrackerDataMask) MutateRawAcceleration(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func (rcv *TrackerDataMask) Temp() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TrackerDataMask) MutateTemp(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func (rcv *TrackerDataMask) LinearAcceleration() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TrackerDataMask) MutateLinearAcceleration(n bool) bool {
	return rcv._tab.MutateBoolSlot(18, n)
}

func (rcv *TrackerDataMask) RotationReferenceAdjusted() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TrackerDataMask) MutateRotationReferenceAdjusted(n bool) bool {
	return rcv._tab.MutateBoolSlot(20, n)
}

func (rcv *TrackerDataMask) RotationIdentityAdjusted() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TrackerDataMask) MutateRotationIdentityAdjusted(n bool) bool {
	return rcv._tab.MutateBoolSlot(22, n)
}

func (rcv *TrackerDataMask) Tps() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TrackerDataMask) MutateTps(n bool) bool {
	return rcv._tab.MutateBoolSlot(24, n)
}

func (rcv *TrackerDataMask) RawMagneticVector() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TrackerDataMask) MutateRawMagneticVector(n bool) bool {
	return rcv._tab.MutateBoolSlot(26, n)
}

func (rcv *TrackerDataMask) StayAligned() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TrackerDataMask) MutateStayAligned(n bool) bool {
	return rcv._tab.MutateBoolSlot(28, n)
}

func TrackerDataMaskStart(builder *flatbuffers.Builder) {
	builder.StartObject(13)
}
func TrackerDataMaskAddInfo(builder *flatbuffers.Builder, info bool) {
	builder.PrependBoolSlot(0, info, false)
}
func TrackerDataMaskAddStatus(builder *flatbuffers.Builder, status bool) {
	builder.PrependBoolSlot(1, status, false)
}
func TrackerDataMaskAddRotation(builder *flatbuffers.Builder, rotation bool) {
	builder.PrependBoolSlot(2, rotation, false)
}
func TrackerDataMaskAddPosition(builder *flatbuffers.Builder, position bool) {
	builder.PrependBoolSlot(3, position, false)
}
func TrackerDataMaskAddRawAngularVelocity(builder *flatbuffers.Builder, rawAngularVelocity bool) {
	builder.PrependBoolSlot(4, rawAngularVelocity, false)
}
func TrackerDataMaskAddRawAcceleration(builder *flatbuffers.Builder, rawAcceleration bool) {
	builder.PrependBoolSlot(5, rawAcceleration, false)
}
func TrackerDataMaskAddTemp(builder *flatbuffers.Builder, temp bool) {
	builder.PrependBoolSlot(6, temp, false)
}
func TrackerDataMaskAddLinearAcceleration(builder *flatbuffers.Builder, linearAcceleration bool) {
	builder.PrependBoolSlot(7, linearAcceleration, false)
}
func TrackerDataMaskAddRotationReferenceAdjusted(builder *flatbuffers.Builder, rotationReferenceAdjusted bool) {
	builder.PrependBoolSlot(8, rotationReferenceAdjusted, false)
}
func TrackerDataMaskAddRotationIdentityAdjusted(builder *flatbuffers.Builder, rotationIdentityAdjusted bool) {
	builder.PrependBoolSlot(9, rotationIdentityAdjusted, false)
}
func TrackerDataMaskAddTps(builder *flatbuffers.Builder, tps bool) {
	builder.PrependBoolSlot(10, tps, false)
}
func TrackerDataMaskAddRawMagneticVector(builder *flatbuffers.Builder, rawMagneticVector bool) {
	builder.PrependBoolSlot(11, rawMagneticVector, false)
}
func TrackerDataMaskAddStayAligned(builder *flatbuffers.Builder, stayAligned bool) {
	builder.PrependBoolSlot(12, stayAligned, false)
}
func TrackerDataMaskEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
