// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package settings

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LegTweaksSettings struct {
	_tab flatbuffers.Table
}

func GetRootAsLegTweaksSettings(buf []byte, offset flatbuffers.UOffsetT) *LegTweaksSettings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LegTweaksSettings{}
	x.Init(buf, n+offset)
	return x
}

func FinishLegTweaksSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLegTweaksSettings(buf []byte, offset flatbuffers.UOffsetT) *LegTweaksSettings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LegTweaksSettings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLegTweaksSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LegTweaksSettings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LegTweaksSettings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LegTweaksSettings) CorrectionStrength() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *LegTweaksSettings) MutateCorrectionStrength(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func LegTweaksSettingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LegTweaksSettingsAddCorrectionStrength(builder *flatbuffers.Builder, correctionStrength float32) {
	builder.PrependFloat32(correctionStrength)
	builder.Slot(0)
}
func LegTweaksSettingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
