// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package settings

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Settings for the skeletal model that are ratios.
// / These values range from 0 to 1.
type ModelRatios struct {
	_tab flatbuffers.Table
}

func GetRootAsModelRatios(buf []byte, offset flatbuffers.UOffsetT) *ModelRatios {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ModelRatios{}
	x.Init(buf, n+offset)
	return x
}

func FinishModelRatiosBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsModelRatios(buf []byte, offset flatbuffers.UOffsetT) *ModelRatios {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ModelRatios{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedModelRatiosBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ModelRatios) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ModelRatios) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ModelRatios) ImputeWaistFromChestHip() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelRatios) MutateImputeWaistFromChestHip(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *ModelRatios) ImputeWaistFromChestLegs() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelRatios) MutateImputeWaistFromChestLegs(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *ModelRatios) ImputeHipFromChestLegs() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelRatios) MutateImputeHipFromChestLegs(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *ModelRatios) ImputeHipFromWaistLegs() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelRatios) MutateImputeHipFromWaistLegs(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

// / Hip's yaw and roll is set to the average of legs when 1.0
func (rcv *ModelRatios) InterpHipLegs() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

// / Hip's yaw and roll is set to the average of legs when 1.0
func (rcv *ModelRatios) MutateInterpHipLegs(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

// / Knee trackers' yaw and roll is set to the lower leg's when 1.0
func (rcv *ModelRatios) InterpKneeTrackerAnkle() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

// / Knee trackers' yaw and roll is set to the lower leg's when 1.0
func (rcv *ModelRatios) MutateInterpKneeTrackerAnkle(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

// / Upper leg's yaw and roll is set to the lower leg's when 1.0
func (rcv *ModelRatios) InterpKneeAnkle() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

// / Upper leg's yaw and roll is set to the lower leg's when 1.0
func (rcv *ModelRatios) MutateInterpKneeAnkle(n float32) bool {
	return rcv._tab.MutateFloat32Slot(16, n)
}

func ModelRatiosStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func ModelRatiosAddImputeWaistFromChestHip(builder *flatbuffers.Builder, imputeWaistFromChestHip float32) {
	builder.PrependFloat32(imputeWaistFromChestHip)
	builder.Slot(0)
}
func ModelRatiosAddImputeWaistFromChestLegs(builder *flatbuffers.Builder, imputeWaistFromChestLegs float32) {
	builder.PrependFloat32(imputeWaistFromChestLegs)
	builder.Slot(1)
}
func ModelRatiosAddImputeHipFromChestLegs(builder *flatbuffers.Builder, imputeHipFromChestLegs float32) {
	builder.PrependFloat32(imputeHipFromChestLegs)
	builder.Slot(2)
}
func ModelRatiosAddImputeHipFromWaistLegs(builder *flatbuffers.Builder, imputeHipFromWaistLegs float32) {
	builder.PrependFloat32(imputeHipFromWaistLegs)
	builder.Slot(3)
}
func ModelRatiosAddInterpHipLegs(builder *flatbuffers.Builder, interpHipLegs float32) {
	builder.PrependFloat32(interpHipLegs)
	builder.Slot(4)
}
func ModelRatiosAddInterpKneeTrackerAnkle(builder *flatbuffers.Builder, interpKneeTrackerAnkle float32) {
	builder.PrependFloat32(interpKneeTrackerAnkle)
	builder.Slot(5)
}
func ModelRatiosAddInterpKneeAnkle(builder *flatbuffers.Builder, interpKneeAnkle float32) {
	builder.PrependFloat32(interpKneeAnkle)
	builder.Slot(6)
}
func ModelRatiosEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
