// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package settings

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Settings for the skeletal model that are toggles.
type ModelToggles struct {
	_tab flatbuffers.Table
}

func GetRootAsModelToggles(buf []byte, offset flatbuffers.UOffsetT) *ModelToggles {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ModelToggles{}
	x.Init(buf, n+offset)
	return x
}

func FinishModelTogglesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsModelToggles(buf []byte, offset flatbuffers.UOffsetT) *ModelToggles {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ModelToggles{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedModelTogglesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ModelToggles) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ModelToggles) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ModelToggles) ExtendedSpine() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelToggles) MutateExtendedSpine(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *ModelToggles) ExtendedPelvis() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelToggles) MutateExtendedPelvis(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *ModelToggles) ExtendedKnee() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelToggles) MutateExtendedKnee(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *ModelToggles) ForceArmsFromHmd() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelToggles) MutateForceArmsFromHmd(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *ModelToggles) FloorClip() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelToggles) MutateFloorClip(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *ModelToggles) SkatingCorrection() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelToggles) MutateSkatingCorrection(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func (rcv *ModelToggles) ToeSnap() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelToggles) MutateToeSnap(n bool) bool {
	return rcv._tab.MutateBoolSlot(18, n)
}

func (rcv *ModelToggles) FootPlant() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelToggles) MutateFootPlant(n bool) bool {
	return rcv._tab.MutateBoolSlot(20, n)
}

func (rcv *ModelToggles) SelfLocalization() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelToggles) MutateSelfLocalization(n bool) bool {
	return rcv._tab.MutateBoolSlot(22, n)
}

func (rcv *ModelToggles) UsePosition() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelToggles) MutateUsePosition(n bool) bool {
	return rcv._tab.MutateBoolSlot(24, n)
}

func (rcv *ModelToggles) EnforceConstraints() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelToggles) MutateEnforceConstraints(n bool) bool {
	return rcv._tab.MutateBoolSlot(26, n)
}

func (rcv *ModelToggles) CorrectConstraints() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *ModelToggles) MutateCorrectConstraints(n bool) bool {
	return rcv._tab.MutateBoolSlot(28, n)
}

func ModelTogglesStart(builder *flatbuffers.Builder) {
	builder.StartObject(13)
}
func ModelTogglesAddExtendedSpine(builder *flatbuffers.Builder, extendedSpine bool) {
	builder.PrependBool(extendedSpine)
	builder.Slot(0)
}
func ModelTogglesAddExtendedPelvis(builder *flatbuffers.Builder, extendedPelvis bool) {
	builder.PrependBool(extendedPelvis)
	builder.Slot(1)
}
func ModelTogglesAddExtendedKnee(builder *flatbuffers.Builder, extendedKnee bool) {
	builder.PrependBool(extendedKnee)
	builder.Slot(2)
}
func ModelTogglesAddForceArmsFromHmd(builder *flatbuffers.Builder, forceArmsFromHmd bool) {
	builder.PrependBool(forceArmsFromHmd)
	builder.Slot(3)
}
func ModelTogglesAddFloorClip(builder *flatbuffers.Builder, floorClip bool) {
	builder.PrependBool(floorClip)
	builder.Slot(4)
}
func ModelTogglesAddSkatingCorrection(builder *flatbuffers.Builder, skatingCorrection bool) {
	builder.PrependBool(skatingCorrection)
	builder.Slot(5)
}
func ModelTogglesAddToeSnap(builder *flatbuffers.Builder, toeSnap bool) {
	builder.PrependBool(toeSnap)
	builder.Slot(7)
}
func ModelTogglesAddFootPlant(builder *flatbuffers.Builder, footPlant bool) {
	builder.PrependBool(footPlant)
	builder.Slot(8)
}
func ModelTogglesAddSelfLocalization(builder *flatbuffers.Builder, selfLocalization bool) {
	builder.PrependBool(selfLocalization)
	builder.Slot(9)
}
func ModelTogglesAddUsePosition(builder *flatbuffers.Builder, usePosition bool) {
	builder.PrependBool(usePosition)
	builder.Slot(10)
}
func ModelTogglesAddEnforceConstraints(builder *flatbuffers.Builder, enforceConstraints bool) {
	builder.PrependBool(enforceConstraints)
	builder.Slot(11)
}
func ModelTogglesAddCorrectConstraints(builder *flatbuffers.Builder, correctConstraints bool) {
	builder.PrependBool(correctConstraints)
	builder.Slot(12)
}
func ModelTogglesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
