// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package settings

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Settings for the skeletal model.
type ModelSettings struct {
	_tab flatbuffers.Table
}

func GetRootAsModelSettings(buf []byte, offset flatbuffers.UOffsetT) *ModelSettings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ModelSettings{}
	x.Init(buf, n+offset)
	return x
}

func FinishModelSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsModelSettings(buf []byte, offset flatbuffers.UOffsetT) *ModelSettings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ModelSettings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedModelSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ModelSettings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ModelSettings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ModelSettings) Toggles(obj *ModelToggles) *ModelToggles {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ModelToggles)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ModelSettings) Ratios(obj *ModelRatios) *ModelRatios {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ModelRatios)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ModelSettings) LegTweaks(obj *LegTweaksSettings) *LegTweaksSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(LegTweaksSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ModelSettings) SkeletonHeight(obj *SkeletonHeight) *SkeletonHeight {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(SkeletonHeight)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ModelSettingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ModelSettingsAddToggles(builder *flatbuffers.Builder, toggles flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(toggles), 0)
}
func ModelSettingsAddRatios(builder *flatbuffers.Builder, ratios flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(ratios), 0)
}
func ModelSettingsAddLegTweaks(builder *flatbuffers.Builder, legTweaks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(legTweaks), 0)
}
func ModelSettingsAddSkeletonHeight(builder *flatbuffers.Builder, skeletonHeight flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(skeletonHeight), 0)
}
func ModelSettingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
