// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package settings

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SkeletonHeight struct {
	_tab flatbuffers.Table
}

func GetRootAsSkeletonHeight(buf []byte, offset flatbuffers.UOffsetT) *SkeletonHeight {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SkeletonHeight{}
	x.Init(buf, n+offset)
	return x
}

func FinishSkeletonHeightBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSkeletonHeight(buf []byte, offset flatbuffers.UOffsetT) *SkeletonHeight {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SkeletonHeight{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSkeletonHeightBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SkeletonHeight) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SkeletonHeight) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SkeletonHeight) HmdHeight() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *SkeletonHeight) MutateHmdHeight(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *SkeletonHeight) FloorHeight() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *SkeletonHeight) MutateFloorHeight(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func SkeletonHeightStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SkeletonHeightAddHmdHeight(builder *flatbuffers.Builder, hmdHeight float32) {
	builder.PrependFloat32(hmdHeight)
	builder.Slot(0)
}
func SkeletonHeightAddFloorHeight(builder *flatbuffers.Builder, floorHeight float32) {
	builder.PrependFloat32(floorHeight)
	builder.Slot(1)
}
func SkeletonHeightEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
