// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data_feed

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
	solarxr_protocol__datatypes__math "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes/math"
)

type Bone struct {
	_tab flatbuffers.Table
}

func GetRootAsBone(buf []byte, offset flatbuffers.UOffsetT) *Bone {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Bone{}
	x.Init(buf, n+offset)
	return x
}

func FinishBoneBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBone(buf []byte, offset flatbuffers.UOffsetT) *Bone {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Bone{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBoneBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Bone) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Bone) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Bone) BodyPart() solarxr_protocol__datatypes.BodyPart {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return solarxr_protocol__datatypes.BodyPart(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Bone) MutateBodyPart(n solarxr_protocol__datatypes.BodyPart) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

// / The global rotation of the bone.
// /
// / Note that the identity rotation is where a bone's tail is towards -y (assuming
// / the head of the bone is the origin)
func (rcv *Bone) RotationG(obj *solarxr_protocol__datatypes__math.Quat) *solarxr_protocol__datatypes__math.Quat {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(solarxr_protocol__datatypes__math.Quat)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / The global rotation of the bone.
// /
// / Note that the identity rotation is where a bone's tail is towards -y (assuming
// / the head of the bone is the origin)
func (rcv *Bone) BoneLength() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Bone) MutateBoneLength(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

// / The global position of the head of this bone.
// /
// / The head of a bone is joint/node of the bone touching the parent bone. The
// / parent is defined as the bone closer to the HMD.
func (rcv *Bone) HeadPositionG(obj *solarxr_protocol__datatypes__math.Vec3f) *solarxr_protocol__datatypes__math.Vec3f {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(solarxr_protocol__datatypes__math.Vec3f)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / The global position of the head of this bone.
// /
// / The head of a bone is joint/node of the bone touching the parent bone. The
// / parent is defined as the bone closer to the HMD.
func BoneStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func BoneAddBodyPart(builder *flatbuffers.Builder, bodyPart solarxr_protocol__datatypes.BodyPart) {
	builder.PrependByteSlot(0, byte(bodyPart), 0)
}
func BoneAddRotationG(builder *flatbuffers.Builder, rotationG flatbuffers.UOffsetT) {
	builder.PrependStructSlot(1, flatbuffers.UOffsetT(rotationG), 0)
}
func BoneAddBoneLength(builder *flatbuffers.Builder, boneLength float32) {
	builder.PrependFloat32Slot(2, boneLength, 0.0)
}
func BoneAddHeadPositionG(builder *flatbuffers.Builder, headPositionG flatbuffers.UOffsetT) {
	builder.PrependStructSlot(3, flatbuffers.UOffsetT(headPositionG), 0)
}
func BoneEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
