// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data_feed

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__data_feed__device_data "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/data_feed/device_data"
	solarxr_protocol__data_feed__tracker "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/data_feed/tracker"
)

// / All information related to the configuration of a data feed. This may be sent
// / as part of a `StartFeed`.
type DataFeedConfig struct {
	_tab flatbuffers.Table
}

func GetRootAsDataFeedConfig(buf []byte, offset flatbuffers.UOffsetT) *DataFeedConfig {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DataFeedConfig{}
	x.Init(buf, n+offset)
	return x
}

func FinishDataFeedConfigBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDataFeedConfig(buf []byte, offset flatbuffers.UOffsetT) *DataFeedConfig {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DataFeedConfig{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDataFeedConfigBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DataFeedConfig) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DataFeedConfig) Table() flatbuffers.Table {
	return rcv._tab
}

// / Minimum delay in milliseconds between new data updates. This value will be
// / ignored when used for a `PollDataFeed`.
func (rcv *DataFeedConfig) MinimumTimeSinceLast() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

// / Minimum delay in milliseconds between new data updates. This value will be
// / ignored when used for a `PollDataFeed`.
func (rcv *DataFeedConfig) MutateMinimumTimeSinceLast(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *DataFeedConfig) DataMask(obj *solarxr_protocol__data_feed__device_data.DeviceDataMask) *solarxr_protocol__data_feed__device_data.DeviceDataMask {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(solarxr_protocol__data_feed__device_data.DeviceDataMask)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DataFeedConfig) SyntheticTrackersMask(obj *solarxr_protocol__data_feed__tracker.TrackerDataMask) *solarxr_protocol__data_feed__tracker.TrackerDataMask {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(solarxr_protocol__data_feed__tracker.TrackerDataMask)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DataFeedConfig) BoneMask() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DataFeedConfig) MutateBoneMask(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *DataFeedConfig) StayAlignedPoseMask() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DataFeedConfig) MutateStayAlignedPoseMask(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *DataFeedConfig) ServerGuardsMask() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DataFeedConfig) MutateServerGuardsMask(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func DataFeedConfigStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func DataFeedConfigAddMinimumTimeSinceLast(builder *flatbuffers.Builder, minimumTimeSinceLast uint16) {
	builder.PrependUint16Slot(0, minimumTimeSinceLast, 0)
}
func DataFeedConfigAddDataMask(builder *flatbuffers.Builder, dataMask flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(dataMask), 0)
}
func DataFeedConfigAddSyntheticTrackersMask(builder *flatbuffers.Builder, syntheticTrackersMask flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(syntheticTrackersMask), 0)
}
func DataFeedConfigAddBoneMask(builder *flatbuffers.Builder, boneMask bool) {
	builder.PrependBoolSlot(3, boneMask, false)
}
func DataFeedConfigAddStayAlignedPoseMask(builder *flatbuffers.Builder, stayAlignedPoseMask bool) {
	builder.PrependBoolSlot(4, stayAlignedPoseMask, false)
}
func DataFeedConfigAddServerGuardsMask(builder *flatbuffers.Builder, serverGuardsMask bool) {
	builder.PrependBoolSlot(5, serverGuardsMask, false)
}
func DataFeedConfigEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
