// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data_feed

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DataFeedMessageHeader struct {
	_tab flatbuffers.Table
}

func GetRootAsDataFeedMessageHeader(buf []byte, offset flatbuffers.UOffsetT) *DataFeedMessageHeader {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DataFeedMessageHeader{}
	x.Init(buf, n+offset)
	return x
}

func FinishDataFeedMessageHeaderBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDataFeedMessageHeader(buf []byte, offset flatbuffers.UOffsetT) *DataFeedMessageHeader {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DataFeedMessageHeader{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDataFeedMessageHeaderBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DataFeedMessageHeader) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DataFeedMessageHeader) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DataFeedMessageHeader) MessageType() DataFeedMessage {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return DataFeedMessage(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DataFeedMessageHeader) MutateMessageType(n DataFeedMessage) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *DataFeedMessageHeader) Message(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func DataFeedMessageHeaderStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DataFeedMessageHeaderAddMessageType(builder *flatbuffers.Builder, messageType DataFeedMessage) {
	builder.PrependByteSlot(0, byte(messageType), 0)
}
func DataFeedMessageHeaderAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(message), 0)
}
func DataFeedMessageHeaderEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
