// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data_feed

import "strconv"

type DataFeedMessage byte

const (
	DataFeedMessageNONE           DataFeedMessage = 0
	DataFeedMessagePollDataFeed   DataFeedMessage = 1
	DataFeedMessageStartDataFeed  DataFeedMessage = 2
	DataFeedMessageDataFeedUpdate DataFeedMessage = 3
	DataFeedMessageDataFeedConfig DataFeedMessage = 4
)

var EnumNamesDataFeedMessage = map[DataFeedMessage]string{
	DataFeedMessageNONE:           "NONE",
	DataFeedMessagePollDataFeed:   "PollDataFeed",
	DataFeedMessageStartDataFeed:  "StartDataFeed",
	DataFeedMessageDataFeedUpdate: "DataFeedUpdate",
	DataFeedMessageDataFeedConfig: "DataFeedConfig",
}

var EnumValuesDataFeedMessage = map[string]DataFeedMessage{
	"NONE":           DataFeedMessageNONE,
	"PollDataFeed":   DataFeedMessagePollDataFeed,
	"StartDataFeed":  DataFeedMessageStartDataFeed,
	"DataFeedUpdate": DataFeedMessageDataFeedUpdate,
	"DataFeedConfig": DataFeedMessageDataFeedConfig,
}

func (v DataFeedMessage) String() string {
	if s, ok := EnumNamesDataFeedMessage[v]; ok {
		return s
	}
	return "DataFeedMessage(" + strconv.FormatInt(int64(v), 10) + ")"
}
