// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data_feed

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Requests for a single `Update` to be sent. This is helpful when getting
// / initial info about the device.
type PollDataFeed struct {
	_tab flatbuffers.Table
}

func GetRootAsPollDataFeed(buf []byte, offset flatbuffers.UOffsetT) *PollDataFeed {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PollDataFeed{}
	x.Init(buf, n+offset)
	return x
}

func FinishPollDataFeedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPollDataFeed(buf []byte, offset flatbuffers.UOffsetT) *PollDataFeed {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PollDataFeed{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPollDataFeedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PollDataFeed) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PollDataFeed) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PollDataFeed) Config(obj *DataFeedConfig) *DataFeedConfig {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DataFeedConfig)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func PollDataFeedStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PollDataFeedAddConfig(builder *flatbuffers.Builder, config flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(config), 0)
}
func PollDataFeedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
