// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package solarxr_protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__data_feed "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/data_feed"
	solarxr_protocol__pub_sub "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/pub_sub"
	solarxr_protocol__rpc "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/rpc"
)

// / MessageBundle contains all of the messages for the data feed system and the
// / rpc system that will be sent in one buffer.
type MessageBundle struct {
	_tab flatbuffers.Table
}

func GetRootAsMessageBundle(buf []byte, offset flatbuffers.UOffsetT) *MessageBundle {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessageBundle{}
	x.Init(buf, n+offset)
	return x
}

func FinishMessageBundleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMessageBundle(buf []byte, offset flatbuffers.UOffsetT) *MessageBundle {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MessageBundle{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMessageBundleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MessageBundle) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessageBundle) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MessageBundle) DataFeedMsgs(obj *solarxr_protocol__data_feed.DataFeedMessageHeader, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MessageBundle) DataFeedMsgsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MessageBundle) RpcMsgs(obj *solarxr_protocol__rpc.RpcMessageHeader, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MessageBundle) RpcMsgsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MessageBundle) PubSubMsgs(obj *solarxr_protocol__pub_sub.PubSubHeader, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MessageBundle) PubSubMsgsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MessageBundleStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MessageBundleAddDataFeedMsgs(builder *flatbuffers.Builder, dataFeedMsgs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dataFeedMsgs), 0)
}
func MessageBundleStartDataFeedMsgsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MessageBundleAddRpcMsgs(builder *flatbuffers.Builder, rpcMsgs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(rpcMsgs), 0)
}
func MessageBundleStartRpcMsgsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MessageBundleAddPubSubMsgs(builder *flatbuffers.Builder, pubSubMsgs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(pubSubMsgs), 0)
}
func MessageBundleStartPubSubMsgsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MessageBundleEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
