// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package server

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ServerGuards struct {
	_tab flatbuffers.Table
}

func GetRootAsServerGuards(buf []byte, offset flatbuffers.UOffsetT) *ServerGuards {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ServerGuards{}
	x.Init(buf, n+offset)
	return x
}

func FinishServerGuardsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsServerGuards(buf []byte, offset flatbuffers.UOffsetT) *ServerGuards {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ServerGuards{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedServerGuardsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ServerGuards) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ServerGuards) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ServerGuards) CanDoMounting() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ServerGuards) MutateCanDoMounting(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *ServerGuards) CanDoYawReset() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ServerGuards) MutateCanDoYawReset(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *ServerGuards) CanDoUserHeightCalibration() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ServerGuards) MutateCanDoUserHeightCalibration(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func ServerGuardsStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ServerGuardsAddCanDoMounting(builder *flatbuffers.Builder, canDoMounting bool) {
	builder.PrependBoolSlot(0, canDoMounting, false)
}
func ServerGuardsAddCanDoYawReset(builder *flatbuffers.Builder, canDoYawReset bool) {
	builder.PrependBoolSlot(1, canDoYawReset, false)
}
func ServerGuardsAddCanDoUserHeightCalibration(builder *flatbuffers.Builder, canDoUserHeightCalibration bool) {
	builder.PrependBoolSlot(2, canDoUserHeightCalibration, false)
}
func ServerGuardsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
