// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AddUnknownDeviceRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsAddUnknownDeviceRequest(buf []byte, offset flatbuffers.UOffsetT) *AddUnknownDeviceRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AddUnknownDeviceRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishAddUnknownDeviceRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAddUnknownDeviceRequest(buf []byte, offset flatbuffers.UOffsetT) *AddUnknownDeviceRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AddUnknownDeviceRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAddUnknownDeviceRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AddUnknownDeviceRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AddUnknownDeviceRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AddUnknownDeviceRequest) MacAddress() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AddUnknownDeviceRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AddUnknownDeviceRequestAddMacAddress(builder *flatbuffers.Builder, macAddress flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(macAddress), 0)
}
func AddUnknownDeviceRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
