// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import "strconv"

type ArmsMountingResetMode byte

const (
	/// Upper arm going back and forearm going forward
	ArmsMountingResetModeBACK ArmsMountingResetMode = 0
	/// Arms going forward
	ArmsMountingResetModeFORWARD ArmsMountingResetMode = 1
	/// Arms going up to the sides into a tpose
	ArmsMountingResetModeTPOSE_UP ArmsMountingResetMode = 2
	/// Arms going down to the sides from a tpose
	ArmsMountingResetModeTPOSE_DOWN ArmsMountingResetMode = 3
)

var EnumNamesArmsMountingResetMode = map[ArmsMountingResetMode]string{
	ArmsMountingResetModeBACK:       "BACK",
	ArmsMountingResetModeFORWARD:    "FORWARD",
	ArmsMountingResetModeTPOSE_UP:   "TPOSE_UP",
	ArmsMountingResetModeTPOSE_DOWN: "TPOSE_DOWN",
}

var EnumValuesArmsMountingResetMode = map[string]ArmsMountingResetMode{
	"BACK":       ArmsMountingResetModeBACK,
	"FORWARD":    ArmsMountingResetModeFORWARD,
	"TPOSE_UP":   ArmsMountingResetModeTPOSE_UP,
	"TPOSE_DOWN": ArmsMountingResetModeTPOSE_DOWN,
}

func (v ArmsMountingResetMode) String() string {
	if s, ok := EnumNamesArmsMountingResetMode[v]; ok {
		return s
	}
	return "ArmsMountingResetMode(" + strconv.FormatInt(int64(v), 10) + ")"
}
