// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
	solarxr_protocol__datatypes__math "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes/math"
)

type AssignTrackerRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsAssignTrackerRequest(buf []byte, offset flatbuffers.UOffsetT) *AssignTrackerRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AssignTrackerRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishAssignTrackerRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAssignTrackerRequest(buf []byte, offset flatbuffers.UOffsetT) *AssignTrackerRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AssignTrackerRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAssignTrackerRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AssignTrackerRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AssignTrackerRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AssignTrackerRequest) TrackerId(obj *solarxr_protocol__datatypes.TrackerId) *solarxr_protocol__datatypes.TrackerId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(solarxr_protocol__datatypes.TrackerId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *AssignTrackerRequest) BodyPosition() solarxr_protocol__datatypes.BodyPart {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return solarxr_protocol__datatypes.BodyPart(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *AssignTrackerRequest) MutateBodyPosition(n solarxr_protocol__datatypes.BodyPart) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *AssignTrackerRequest) MountingOrientation(obj *solarxr_protocol__datatypes__math.Quat) *solarxr_protocol__datatypes__math.Quat {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(solarxr_protocol__datatypes__math.Quat)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *AssignTrackerRequest) DisplayName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AssignTrackerRequest) AllowDriftCompensation() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *AssignTrackerRequest) MutateAllowDriftCompensation(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func AssignTrackerRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func AssignTrackerRequestAddTrackerId(builder *flatbuffers.Builder, trackerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(trackerId), 0)
}
func AssignTrackerRequestAddBodyPosition(builder *flatbuffers.Builder, bodyPosition solarxr_protocol__datatypes.BodyPart) {
	builder.PrependByteSlot(1, byte(bodyPosition), 0)
}
func AssignTrackerRequestAddMountingOrientation(builder *flatbuffers.Builder, mountingOrientation flatbuffers.UOffsetT) {
	builder.PrependStructSlot(2, flatbuffers.UOffsetT(mountingOrientation), 0)
}
func AssignTrackerRequestAddDisplayName(builder *flatbuffers.Builder, displayName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(displayName), 0)
}
func AssignTrackerRequestAddAllowDriftCompensation(builder *flatbuffers.Builder, allowDriftCompensation bool) {
	builder.PrependBoolSlot(4, allowDriftCompensation, false)
}
func AssignTrackerRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
