// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Stops the current recording, using it as far as it has been recorded
type AutoBoneStopRecordingRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsAutoBoneStopRecordingRequest(buf []byte, offset flatbuffers.UOffsetT) *AutoBoneStopRecordingRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AutoBoneStopRecordingRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishAutoBoneStopRecordingRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAutoBoneStopRecordingRequest(buf []byte, offset flatbuffers.UOffsetT) *AutoBoneStopRecordingRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AutoBoneStopRecordingRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAutoBoneStopRecordingRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AutoBoneStopRecordingRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AutoBoneStopRecordingRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func AutoBoneStopRecordingRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func AutoBoneStopRecordingRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
