// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AutoBoneProcessStatusResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsAutoBoneProcessStatusResponse(buf []byte, offset flatbuffers.UOffsetT) *AutoBoneProcessStatusResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AutoBoneProcessStatusResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishAutoBoneProcessStatusResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAutoBoneProcessStatusResponse(buf []byte, offset flatbuffers.UOffsetT) *AutoBoneProcessStatusResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AutoBoneProcessStatusResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAutoBoneProcessStatusResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AutoBoneProcessStatusResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AutoBoneProcessStatusResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AutoBoneProcessStatusResponse) ProcessType() AutoBoneProcessType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return AutoBoneProcessType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *AutoBoneProcessStatusResponse) MutateProcessType(n AutoBoneProcessType) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

// / The current count. This value is -1 if there is nothing to report.
func (rcv *AutoBoneProcessStatusResponse) Current() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

// / The current count. This value is -1 if there is nothing to report.
func (rcv *AutoBoneProcessStatusResponse) MutateCurrent(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

// / The total count. This value is -1 if there is nothing to report.
func (rcv *AutoBoneProcessStatusResponse) Total() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

// / The total count. This value is -1 if there is nothing to report.
func (rcv *AutoBoneProcessStatusResponse) MutateTotal(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

// / True if the operation has completed with any result, successful or not.
func (rcv *AutoBoneProcessStatusResponse) Completed() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

// / True if the operation has completed with any result, successful or not.
func (rcv *AutoBoneProcessStatusResponse) MutateCompleted(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

// / True if the completed operation was successful, only observe if `completed` is true.
func (rcv *AutoBoneProcessStatusResponse) Success() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

// / True if the completed operation was successful, only observe if `completed` is true.
func (rcv *AutoBoneProcessStatusResponse) MutateSuccess(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

// / The time remaining in seconds. This value is -1 if there is nothing to report.
func (rcv *AutoBoneProcessStatusResponse) Eta() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

// / The time remaining in seconds. This value is -1 if there is nothing to report.
func (rcv *AutoBoneProcessStatusResponse) MutateEta(n float32) bool {
	return rcv._tab.MutateFloat32Slot(16, n)
}

func AutoBoneProcessStatusResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func AutoBoneProcessStatusResponseAddProcessType(builder *flatbuffers.Builder, processType AutoBoneProcessType) {
	builder.PrependByteSlot(0, byte(processType), 0)
}
func AutoBoneProcessStatusResponseAddCurrent(builder *flatbuffers.Builder, current uint32) {
	builder.PrependUint32Slot(2, current, 0)
}
func AutoBoneProcessStatusResponseAddTotal(builder *flatbuffers.Builder, total uint32) {
	builder.PrependUint32Slot(3, total, 0)
}
func AutoBoneProcessStatusResponseAddCompleted(builder *flatbuffers.Builder, completed bool) {
	builder.PrependBoolSlot(4, completed, false)
}
func AutoBoneProcessStatusResponseAddSuccess(builder *flatbuffers.Builder, success bool) {
	builder.PrependBoolSlot(5, success, false)
}
func AutoBoneProcessStatusResponseAddEta(builder *flatbuffers.Builder, eta float32) {
	builder.PrependFloat32Slot(6, eta, 0.0)
}
func AutoBoneProcessStatusResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
