// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AutoBoneProcessRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsAutoBoneProcessRequest(buf []byte, offset flatbuffers.UOffsetT) *AutoBoneProcessRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AutoBoneProcessRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishAutoBoneProcessRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAutoBoneProcessRequest(buf []byte, offset flatbuffers.UOffsetT) *AutoBoneProcessRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AutoBoneProcessRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAutoBoneProcessRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AutoBoneProcessRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AutoBoneProcessRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AutoBoneProcessRequest) ProcessType() AutoBoneProcessType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return AutoBoneProcessType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *AutoBoneProcessRequest) MutateProcessType(n AutoBoneProcessType) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func AutoBoneProcessRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AutoBoneProcessRequestAddProcessType(builder *flatbuffers.Builder, processType AutoBoneProcessType) {
	builder.PrependByteSlot(0, byte(processType), 0)
}
func AutoBoneProcessRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
