// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Cancels the current recording, aborting the process and discarding the data
type AutoBoneCancelRecordingRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsAutoBoneCancelRecordingRequest(buf []byte, offset flatbuffers.UOffsetT) *AutoBoneCancelRecordingRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AutoBoneCancelRecordingRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishAutoBoneCancelRecordingRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAutoBoneCancelRecordingRequest(buf []byte, offset flatbuffers.UOffsetT) *AutoBoneCancelRecordingRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AutoBoneCancelRecordingRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAutoBoneCancelRecordingRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AutoBoneCancelRecordingRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AutoBoneCancelRecordingRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func AutoBoneCancelRecordingRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func AutoBoneCancelRecordingRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
