// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AutoBoneEpochResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsAutoBoneEpochResponse(buf []byte, offset flatbuffers.UOffsetT) *AutoBoneEpochResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AutoBoneEpochResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishAutoBoneEpochResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAutoBoneEpochResponse(buf []byte, offset flatbuffers.UOffsetT) *AutoBoneEpochResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AutoBoneEpochResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAutoBoneEpochResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AutoBoneEpochResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AutoBoneEpochResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AutoBoneEpochResponse) CurrentEpoch() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AutoBoneEpochResponse) MutateCurrentEpoch(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *AutoBoneEpochResponse) TotalEpochs() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AutoBoneEpochResponse) MutateTotalEpochs(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

// / The current error value. This can be any positive number, where lower is better.
func (rcv *AutoBoneEpochResponse) EpochError() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

// / The current error value. This can be any positive number, where lower is better.
func (rcv *AutoBoneEpochResponse) MutateEpochError(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

// / A list of the current estimated body proportions.
func (rcv *AutoBoneEpochResponse) AdjustedSkeletonParts(obj *SkeletonPart, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AutoBoneEpochResponse) AdjustedSkeletonPartsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

// / A list of the current estimated body proportions.
func AutoBoneEpochResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func AutoBoneEpochResponseAddCurrentEpoch(builder *flatbuffers.Builder, currentEpoch uint32) {
	builder.PrependUint32Slot(0, currentEpoch, 0)
}
func AutoBoneEpochResponseAddTotalEpochs(builder *flatbuffers.Builder, totalEpochs uint32) {
	builder.PrependUint32Slot(1, totalEpochs, 0)
}
func AutoBoneEpochResponseAddEpochError(builder *flatbuffers.Builder, epochError float32) {
	builder.PrependFloat32Slot(2, epochError, 0.0)
}
func AutoBoneEpochResponseAddAdjustedSkeletonParts(builder *flatbuffers.Builder, adjustedSkeletonParts flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(adjustedSkeletonParts), 0)
}
func AutoBoneEpochResponseStartAdjustedSkeletonPartsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AutoBoneEpochResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
