// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / https://github.com/SlimeVR/SlimeVR-Server/blob/v0.8.3/server/src/main/java/dev/slimevr/config/AutoBoneConfig.kt
type AutoBoneSettings struct {
	_tab flatbuffers.Table
}

func GetRootAsAutoBoneSettings(buf []byte, offset flatbuffers.UOffsetT) *AutoBoneSettings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AutoBoneSettings{}
	x.Init(buf, n+offset)
	return x
}

func FinishAutoBoneSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAutoBoneSettings(buf []byte, offset flatbuffers.UOffsetT) *AutoBoneSettings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AutoBoneSettings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAutoBoneSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AutoBoneSettings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AutoBoneSettings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AutoBoneSettings) CursorIncrement() *int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		v := rcv._tab.GetInt32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateCursorIncrement(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *AutoBoneSettings) MinDataDistance() *int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		v := rcv._tab.GetInt32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateMinDataDistance(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *AutoBoneSettings) MaxDataDistance() *int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		v := rcv._tab.GetInt32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateMaxDataDistance(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *AutoBoneSettings) NumEpochs() *int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		v := rcv._tab.GetInt32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateNumEpochs(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *AutoBoneSettings) PrintEveryNumEpochs() *int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		v := rcv._tab.GetInt32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutatePrintEveryNumEpochs(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *AutoBoneSettings) InitialAdjustRate() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateInitialAdjustRate(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

func (rcv *AutoBoneSettings) AdjustRateDecay() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateAdjustRateDecay(n float32) bool {
	return rcv._tab.MutateFloat32Slot(16, n)
}

func (rcv *AutoBoneSettings) SlideErrorFactor() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateSlideErrorFactor(n float32) bool {
	return rcv._tab.MutateFloat32Slot(18, n)
}

func (rcv *AutoBoneSettings) OffsetSlideErrorFactor() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateOffsetSlideErrorFactor(n float32) bool {
	return rcv._tab.MutateFloat32Slot(20, n)
}

func (rcv *AutoBoneSettings) FootHeightOffsetErrorFactor() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateFootHeightOffsetErrorFactor(n float32) bool {
	return rcv._tab.MutateFloat32Slot(22, n)
}

func (rcv *AutoBoneSettings) BodyProportionErrorFactor() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateBodyProportionErrorFactor(n float32) bool {
	return rcv._tab.MutateFloat32Slot(24, n)
}

func (rcv *AutoBoneSettings) HeightErrorFactor() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateHeightErrorFactor(n float32) bool {
	return rcv._tab.MutateFloat32Slot(26, n)
}

func (rcv *AutoBoneSettings) PositionErrorFactor() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutatePositionErrorFactor(n float32) bool {
	return rcv._tab.MutateFloat32Slot(28, n)
}

func (rcv *AutoBoneSettings) PositionOffsetErrorFactor() *float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		v := rcv._tab.GetFloat32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutatePositionOffsetErrorFactor(n float32) bool {
	return rcv._tab.MutateFloat32Slot(30, n)
}

func (rcv *AutoBoneSettings) CalcInitError() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateCalcInitError(n bool) bool {
	return rcv._tab.MutateBoolSlot(32, n)
}

func (rcv *AutoBoneSettings) RandomizeFrameOrder() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateRandomizeFrameOrder(n bool) bool {
	return rcv._tab.MutateBoolSlot(34, n)
}

func (rcv *AutoBoneSettings) ScaleEachStep() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateScaleEachStep(n bool) bool {
	return rcv._tab.MutateBoolSlot(36, n)
}

func (rcv *AutoBoneSettings) SampleCount() *int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		v := rcv._tab.GetInt32(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateSampleCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(38, n)
}

func (rcv *AutoBoneSettings) SampleRateMs() *int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		v := rcv._tab.GetInt64(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateSampleRateMs(n int64) bool {
	return rcv._tab.MutateInt64Slot(40, n)
}

func (rcv *AutoBoneSettings) SaveRecordings() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateSaveRecordings(n bool) bool {
	return rcv._tab.MutateBoolSlot(42, n)
}

func (rcv *AutoBoneSettings) UseSkeletonHeight() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(44))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateUseSkeletonHeight(n bool) bool {
	return rcv._tab.MutateBoolSlot(44, n)
}

func (rcv *AutoBoneSettings) RandSeed() *int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(46))
	if o != 0 {
		v := rcv._tab.GetInt64(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *AutoBoneSettings) MutateRandSeed(n int64) bool {
	return rcv._tab.MutateInt64Slot(46, n)
}

func AutoBoneSettingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(22)
}
func AutoBoneSettingsAddCursorIncrement(builder *flatbuffers.Builder, cursorIncrement int32) {
	builder.PrependInt32(cursorIncrement)
	builder.Slot(0)
}
func AutoBoneSettingsAddMinDataDistance(builder *flatbuffers.Builder, minDataDistance int32) {
	builder.PrependInt32(minDataDistance)
	builder.Slot(1)
}
func AutoBoneSettingsAddMaxDataDistance(builder *flatbuffers.Builder, maxDataDistance int32) {
	builder.PrependInt32(maxDataDistance)
	builder.Slot(2)
}
func AutoBoneSettingsAddNumEpochs(builder *flatbuffers.Builder, numEpochs int32) {
	builder.PrependInt32(numEpochs)
	builder.Slot(3)
}
func AutoBoneSettingsAddPrintEveryNumEpochs(builder *flatbuffers.Builder, printEveryNumEpochs int32) {
	builder.PrependInt32(printEveryNumEpochs)
	builder.Slot(4)
}
func AutoBoneSettingsAddInitialAdjustRate(builder *flatbuffers.Builder, initialAdjustRate float32) {
	builder.PrependFloat32(initialAdjustRate)
	builder.Slot(5)
}
func AutoBoneSettingsAddAdjustRateDecay(builder *flatbuffers.Builder, adjustRateDecay float32) {
	builder.PrependFloat32(adjustRateDecay)
	builder.Slot(6)
}
func AutoBoneSettingsAddSlideErrorFactor(builder *flatbuffers.Builder, slideErrorFactor float32) {
	builder.PrependFloat32(slideErrorFactor)
	builder.Slot(7)
}
func AutoBoneSettingsAddOffsetSlideErrorFactor(builder *flatbuffers.Builder, offsetSlideErrorFactor float32) {
	builder.PrependFloat32(offsetSlideErrorFactor)
	builder.Slot(8)
}
func AutoBoneSettingsAddFootHeightOffsetErrorFactor(builder *flatbuffers.Builder, footHeightOffsetErrorFactor float32) {
	builder.PrependFloat32(footHeightOffsetErrorFactor)
	builder.Slot(9)
}
func AutoBoneSettingsAddBodyProportionErrorFactor(builder *flatbuffers.Builder, bodyProportionErrorFactor float32) {
	builder.PrependFloat32(bodyProportionErrorFactor)
	builder.Slot(10)
}
func AutoBoneSettingsAddHeightErrorFactor(builder *flatbuffers.Builder, heightErrorFactor float32) {
	builder.PrependFloat32(heightErrorFactor)
	builder.Slot(11)
}
func AutoBoneSettingsAddPositionErrorFactor(builder *flatbuffers.Builder, positionErrorFactor float32) {
	builder.PrependFloat32(positionErrorFactor)
	builder.Slot(12)
}
func AutoBoneSettingsAddPositionOffsetErrorFactor(builder *flatbuffers.Builder, positionOffsetErrorFactor float32) {
	builder.PrependFloat32(positionOffsetErrorFactor)
	builder.Slot(13)
}
func AutoBoneSettingsAddCalcInitError(builder *flatbuffers.Builder, calcInitError bool) {
	builder.PrependBool(calcInitError)
	builder.Slot(14)
}
func AutoBoneSettingsAddRandomizeFrameOrder(builder *flatbuffers.Builder, randomizeFrameOrder bool) {
	builder.PrependBool(randomizeFrameOrder)
	builder.Slot(15)
}
func AutoBoneSettingsAddScaleEachStep(builder *flatbuffers.Builder, scaleEachStep bool) {
	builder.PrependBool(scaleEachStep)
	builder.Slot(16)
}
func AutoBoneSettingsAddSampleCount(builder *flatbuffers.Builder, sampleCount int32) {
	builder.PrependInt32(sampleCount)
	builder.Slot(17)
}
func AutoBoneSettingsAddSampleRateMs(builder *flatbuffers.Builder, sampleRateMs int64) {
	builder.PrependInt64(sampleRateMs)
	builder.Slot(18)
}
func AutoBoneSettingsAddSaveRecordings(builder *flatbuffers.Builder, saveRecordings bool) {
	builder.PrependBool(saveRecordings)
	builder.Slot(19)
}
func AutoBoneSettingsAddUseSkeletonHeight(builder *flatbuffers.Builder, useSkeletonHeight bool) {
	builder.PrependBool(useSkeletonHeight)
	builder.Slot(20)
}
func AutoBoneSettingsAddRandSeed(builder *flatbuffers.Builder, randSeed int64) {
	builder.PrependInt64(randSeed)
	builder.Slot(21)
}
func AutoBoneSettingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
