// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Applies the estimated proportions
type AutoBoneApplyRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsAutoBoneApplyRequest(buf []byte, offset flatbuffers.UOffsetT) *AutoBoneApplyRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AutoBoneApplyRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishAutoBoneApplyRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAutoBoneApplyRequest(buf []byte, offset flatbuffers.UOffsetT) *AutoBoneApplyRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AutoBoneApplyRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAutoBoneApplyRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AutoBoneApplyRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AutoBoneApplyRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func AutoBoneApplyRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func AutoBoneApplyRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
