// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CancelUserHeightCalibration struct {
	_tab flatbuffers.Table
}

func GetRootAsCancelUserHeightCalibration(buf []byte, offset flatbuffers.UOffsetT) *CancelUserHeightCalibration {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CancelUserHeightCalibration{}
	x.Init(buf, n+offset)
	return x
}

func FinishCancelUserHeightCalibrationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCancelUserHeightCalibration(buf []byte, offset flatbuffers.UOffsetT) *CancelUserHeightCalibration {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CancelUserHeightCalibration{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCancelUserHeightCalibrationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CancelUserHeightCalibration) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CancelUserHeightCalibration) Table() flatbuffers.Table {
	return rcv._tab
}

func CancelUserHeightCalibrationStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func CancelUserHeightCalibrationEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
