// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
)

// / If no tracker ID is given, it's the setting for every tracker/device
type ChangeMagToggleRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsChangeMagToggleRequest(buf []byte, offset flatbuffers.UOffsetT) *ChangeMagToggleRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChangeMagToggleRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishChangeMagToggleRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsChangeMagToggleRequest(buf []byte, offset flatbuffers.UOffsetT) *ChangeMagToggleRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ChangeMagToggleRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedChangeMagToggleRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ChangeMagToggleRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChangeMagToggleRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChangeMagToggleRequest) TrackerId(obj *solarxr_protocol__datatypes.TrackerId) *solarxr_protocol__datatypes.TrackerId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(solarxr_protocol__datatypes.TrackerId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChangeMagToggleRequest) Enable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ChangeMagToggleRequest) MutateEnable(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func ChangeMagToggleRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ChangeMagToggleRequestAddTrackerId(builder *flatbuffers.Builder, trackerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(trackerId), 0)
}
func ChangeMagToggleRequestAddEnable(builder *flatbuffers.Builder, enable bool) {
	builder.PrependBoolSlot(1, enable, false)
}
func ChangeMagToggleRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
