// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChangeKeybindRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsChangeKeybindRequest(buf []byte, offset flatbuffers.UOffsetT) *ChangeKeybindRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChangeKeybindRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishChangeKeybindRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsChangeKeybindRequest(buf []byte, offset flatbuffers.UOffsetT) *ChangeKeybindRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ChangeKeybindRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedChangeKeybindRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ChangeKeybindRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChangeKeybindRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChangeKeybindRequest) Keybind(obj *Keybind) *Keybind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Keybind)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ChangeKeybindRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ChangeKeybindRequestAddKeybind(builder *flatbuffers.Builder, keybind flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(keybind), 0)
}
func ChangeKeybindRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
