// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChangeSkeletonConfigRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsChangeSkeletonConfigRequest(buf []byte, offset flatbuffers.UOffsetT) *ChangeSkeletonConfigRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChangeSkeletonConfigRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishChangeSkeletonConfigRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsChangeSkeletonConfigRequest(buf []byte, offset flatbuffers.UOffsetT) *ChangeSkeletonConfigRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ChangeSkeletonConfigRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedChangeSkeletonConfigRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ChangeSkeletonConfigRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChangeSkeletonConfigRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChangeSkeletonConfigRequest) Bone() SkeletonBone {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return SkeletonBone(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ChangeSkeletonConfigRequest) MutateBone(n SkeletonBone) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *ChangeSkeletonConfigRequest) Value() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ChangeSkeletonConfigRequest) MutateValue(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func ChangeSkeletonConfigRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ChangeSkeletonConfigRequestAddBone(builder *flatbuffers.Builder, bone SkeletonBone) {
	builder.PrependByteSlot(0, byte(bone), 0)
}
func ChangeSkeletonConfigRequestAddValue(builder *flatbuffers.Builder, value float32) {
	builder.PrependFloat32Slot(1, value, 0.0)
}
func ChangeSkeletonConfigRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
