// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__rpc__settings "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/rpc/settings"
)

type ChangeSettingsRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsChangeSettingsRequest(buf []byte, offset flatbuffers.UOffsetT) *ChangeSettingsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChangeSettingsRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishChangeSettingsRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsChangeSettingsRequest(buf []byte, offset flatbuffers.UOffsetT) *ChangeSettingsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ChangeSettingsRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedChangeSettingsRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ChangeSettingsRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChangeSettingsRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChangeSettingsRequest) SteamVrTrackers(obj *SteamVRTrackersSetting) *SteamVRTrackersSetting {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(SteamVRTrackersSetting)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChangeSettingsRequest) Filtering(obj *FilteringSettings) *FilteringSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FilteringSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChangeSettingsRequest) DriftCompensation(obj *DriftCompensationSettings) *DriftCompensationSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DriftCompensationSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChangeSettingsRequest) OscRouter(obj *OSCRouterSettings) *OSCRouterSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(OSCRouterSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChangeSettingsRequest) VrcOsc(obj *VRCOSCSettings) *VRCOSCSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(VRCOSCSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChangeSettingsRequest) VmcOsc(obj *VMCOSCSettings) *VMCOSCSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(VMCOSCSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChangeSettingsRequest) ModelSettings(obj *solarxr_protocol__rpc__settings.ModelSettings) *solarxr_protocol__rpc__settings.ModelSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(solarxr_protocol__rpc__settings.ModelSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChangeSettingsRequest) TapDetectionSettings(obj *TapDetectionSettings) *TapDetectionSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TapDetectionSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChangeSettingsRequest) AutoBoneSettings(obj *AutoBoneSettings) *AutoBoneSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(AutoBoneSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChangeSettingsRequest) ResetsSettings(obj *ResetsSettings) *ResetsSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ResetsSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChangeSettingsRequest) StayAligned(obj *StayAlignedSettings) *StayAlignedSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(StayAlignedSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChangeSettingsRequest) HidSettings(obj *HIDSettings) *HIDSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(HIDSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChangeSettingsRequest) Timeout(obj *TimeoutSettings) *TimeoutSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TimeoutSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChangeSettingsRequest) VelocitySettings(obj *VelocitySettings) *VelocitySettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(VelocitySettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChangeSettingsRequest) Vrm(obj *VRMSettings) *VRMSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(VRMSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ChangeSettingsRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(15)
}
func ChangeSettingsRequestAddSteamVrTrackers(builder *flatbuffers.Builder, steamVrTrackers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(steamVrTrackers), 0)
}
func ChangeSettingsRequestAddFiltering(builder *flatbuffers.Builder, filtering flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(filtering), 0)
}
func ChangeSettingsRequestAddDriftCompensation(builder *flatbuffers.Builder, driftCompensation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(driftCompensation), 0)
}
func ChangeSettingsRequestAddOscRouter(builder *flatbuffers.Builder, oscRouter flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(oscRouter), 0)
}
func ChangeSettingsRequestAddVrcOsc(builder *flatbuffers.Builder, vrcOsc flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(vrcOsc), 0)
}
func ChangeSettingsRequestAddVmcOsc(builder *flatbuffers.Builder, vmcOsc flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(vmcOsc), 0)
}
func ChangeSettingsRequestAddModelSettings(builder *flatbuffers.Builder, modelSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(modelSettings), 0)
}
func ChangeSettingsRequestAddTapDetectionSettings(builder *flatbuffers.Builder, tapDetectionSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(tapDetectionSettings), 0)
}
func ChangeSettingsRequestAddAutoBoneSettings(builder *flatbuffers.Builder, autoBoneSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(autoBoneSettings), 0)
}
func ChangeSettingsRequestAddResetsSettings(builder *flatbuffers.Builder, resetsSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(resetsSettings), 0)
}
func ChangeSettingsRequestAddStayAligned(builder *flatbuffers.Builder, stayAligned flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(stayAligned), 0)
}
func ChangeSettingsRequestAddHidSettings(builder *flatbuffers.Builder, hidSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(hidSettings), 0)
}
func ChangeSettingsRequestAddTimeout(builder *flatbuffers.Builder, timeout flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(timeout), 0)
}
func ChangeSettingsRequestAddVelocitySettings(builder *flatbuffers.Builder, velocitySettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(velocitySettings), 0)
}
func ChangeSettingsRequestAddVrm(builder *flatbuffers.Builder, vrm flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(14, flatbuffers.UOffsetT(vrm), 0)
}
func ChangeSettingsRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
