// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClearDriftCompensationRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsClearDriftCompensationRequest(buf []byte, offset flatbuffers.UOffsetT) *ClearDriftCompensationRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClearDriftCompensationRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishClearDriftCompensationRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsClearDriftCompensationRequest(buf []byte, offset flatbuffers.UOffsetT) *ClearDriftCompensationRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClearDriftCompensationRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedClearDriftCompensationRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ClearDriftCompensationRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClearDriftCompensationRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func ClearDriftCompensationRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ClearDriftCompensationRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
