// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DetectStayAlignedRelaxedPoseRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsDetectStayAlignedRelaxedPoseRequest(buf []byte, offset flatbuffers.UOffsetT) *DetectStayAlignedRelaxedPoseRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DetectStayAlignedRelaxedPoseRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishDetectStayAlignedRelaxedPoseRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDetectStayAlignedRelaxedPoseRequest(buf []byte, offset flatbuffers.UOffsetT) *DetectStayAlignedRelaxedPoseRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DetectStayAlignedRelaxedPoseRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDetectStayAlignedRelaxedPoseRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DetectStayAlignedRelaxedPoseRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DetectStayAlignedRelaxedPoseRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DetectStayAlignedRelaxedPoseRequest) Pose() StayAlignedRelaxedPose {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return StayAlignedRelaxedPose(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DetectStayAlignedRelaxedPoseRequest) MutatePose(n StayAlignedRelaxedPose) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func DetectStayAlignedRelaxedPoseRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DetectStayAlignedRelaxedPoseRequestAddPose(builder *flatbuffers.Builder, pose StayAlignedRelaxedPose) {
	builder.PrependByteSlot(0, byte(pose), 0)
}
func DetectStayAlignedRelaxedPoseRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
