// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Settings related to IMU yaw drift compensation
type DriftCompensationSettings struct {
	_tab flatbuffers.Table
}

func GetRootAsDriftCompensationSettings(buf []byte, offset flatbuffers.UOffsetT) *DriftCompensationSettings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DriftCompensationSettings{}
	x.Init(buf, n+offset)
	return x
}

func FinishDriftCompensationSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDriftCompensationSettings(buf []byte, offset flatbuffers.UOffsetT) *DriftCompensationSettings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DriftCompensationSettings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDriftCompensationSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DriftCompensationSettings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DriftCompensationSettings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DriftCompensationSettings) Enabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DriftCompensationSettings) MutateEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *DriftCompensationSettings) Prediction() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DriftCompensationSettings) MutatePrediction(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

// / 0 to 1. A higher value results in more yaw drift compensation
func (rcv *DriftCompensationSettings) Amount() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

// / 0 to 1. A higher value results in more yaw drift compensation
func (rcv *DriftCompensationSettings) MutateAmount(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

// / Number of previous resets to take into account when calculating yaw drift
func (rcv *DriftCompensationSettings) MaxResets() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

// / Number of previous resets to take into account when calculating yaw drift
func (rcv *DriftCompensationSettings) MutateMaxResets(n uint16) bool {
	return rcv._tab.MutateUint16Slot(10, n)
}

func DriftCompensationSettingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func DriftCompensationSettingsAddEnabled(builder *flatbuffers.Builder, enabled bool) {
	builder.PrependBoolSlot(0, enabled, false)
}
func DriftCompensationSettingsAddPrediction(builder *flatbuffers.Builder, prediction bool) {
	builder.PrependBoolSlot(1, prediction, false)
}
func DriftCompensationSettingsAddAmount(builder *flatbuffers.Builder, amount float32) {
	builder.PrependFloat32Slot(2, amount, 0.0)
}
func DriftCompensationSettingsAddMaxResets(builder *flatbuffers.Builder, maxResets uint16) {
	builder.PrependUint16Slot(3, maxResets, 0)
}
func DriftCompensationSettingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
