// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EnableStayAlignedRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsEnableStayAlignedRequest(buf []byte, offset flatbuffers.UOffsetT) *EnableStayAlignedRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EnableStayAlignedRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishEnableStayAlignedRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEnableStayAlignedRequest(buf []byte, offset flatbuffers.UOffsetT) *EnableStayAlignedRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EnableStayAlignedRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEnableStayAlignedRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EnableStayAlignedRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EnableStayAlignedRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EnableStayAlignedRequest) Enable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *EnableStayAlignedRequest) MutateEnable(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func EnableStayAlignedRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func EnableStayAlignedRequestAddEnable(builder *flatbuffers.Builder, enable bool) {
	builder.PrependBoolSlot(0, enable, false)
}
func EnableStayAlignedRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
