// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EnableSteamVRDriverRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsEnableSteamVRDriverRequest(buf []byte, offset flatbuffers.UOffsetT) *EnableSteamVRDriverRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EnableSteamVRDriverRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishEnableSteamVRDriverRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEnableSteamVRDriverRequest(buf []byte, offset flatbuffers.UOffsetT) *EnableSteamVRDriverRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EnableSteamVRDriverRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEnableSteamVRDriverRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EnableSteamVRDriverRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EnableSteamVRDriverRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func EnableSteamVRDriverRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func EnableSteamVRDriverRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
