// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
)

type FilteringSettings struct {
	_tab flatbuffers.Table
}

func GetRootAsFilteringSettings(buf []byte, offset flatbuffers.UOffsetT) *FilteringSettings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FilteringSettings{}
	x.Init(buf, n+offset)
	return x
}

func FinishFilteringSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFilteringSettings(buf []byte, offset flatbuffers.UOffsetT) *FilteringSettings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FilteringSettings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFilteringSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FilteringSettings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FilteringSettings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FilteringSettings) Type() solarxr_protocol__datatypes.FilteringType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return solarxr_protocol__datatypes.FilteringType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *FilteringSettings) MutateType(n solarxr_protocol__datatypes.FilteringType) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

// / 0 to 1. A higher value results in more smoothing or prediction
func (rcv *FilteringSettings) Amount() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

// / 0 to 1. A higher value results in more smoothing or prediction
func (rcv *FilteringSettings) MutateAmount(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func FilteringSettingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FilteringSettingsAddType(builder *flatbuffers.Builder, type_ solarxr_protocol__datatypes.FilteringType) {
	builder.PrependByteSlot(0, byte(type_), 0)
}
func FilteringSettingsAddAmount(builder *flatbuffers.Builder, amount float32) {
	builder.PrependFloat32Slot(1, amount, 0.0)
}
func FilteringSettingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
