// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FirmwarePart struct {
	_tab flatbuffers.Table
}

func GetRootAsFirmwarePart(buf []byte, offset flatbuffers.UOffsetT) *FirmwarePart {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FirmwarePart{}
	x.Init(buf, n+offset)
	return x
}

func FinishFirmwarePartBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFirmwarePart(buf []byte, offset flatbuffers.UOffsetT) *FirmwarePart {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FirmwarePart{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFirmwarePartBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FirmwarePart) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FirmwarePart) Table() flatbuffers.Table {
	return rcv._tab
}

// / Url of the firmware bin to download
func (rcv *FirmwarePart) Url() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / Url of the firmware bin to download
// / Offset of the firmware, used when flashing to the mcu, it indicates where to write this file in memory
// / Will be ignored in the case of OTA flashing
func (rcv *FirmwarePart) Offset() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

// / Offset of the firmware, used when flashing to the mcu, it indicates where to write this file in memory
// / Will be ignored in the case of OTA flashing
func (rcv *FirmwarePart) MutateOffset(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

// / Checksum of the file
func (rcv *FirmwarePart) Digest() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / Checksum of the file
func FirmwarePartStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func FirmwarePartAddUrl(builder *flatbuffers.Builder, url flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(url), 0)
}
func FirmwarePartAddOffset(builder *flatbuffers.Builder, offset uint32) {
	builder.PrependUint32Slot(1, offset, 0)
}
func FirmwarePartAddDigest(builder *flatbuffers.Builder, digest flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(digest), 0)
}
func FirmwarePartEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
