// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FirmwareUpdateStatusResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsFirmwareUpdateStatusResponse(buf []byte, offset flatbuffers.UOffsetT) *FirmwareUpdateStatusResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FirmwareUpdateStatusResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishFirmwareUpdateStatusResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFirmwareUpdateStatusResponse(buf []byte, offset flatbuffers.UOffsetT) *FirmwareUpdateStatusResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FirmwareUpdateStatusResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFirmwareUpdateStatusResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FirmwareUpdateStatusResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FirmwareUpdateStatusResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FirmwareUpdateStatusResponse) DeviceIdType() FirmwareUpdateDeviceId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return FirmwareUpdateDeviceId(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *FirmwareUpdateStatusResponse) MutateDeviceIdType(n FirmwareUpdateDeviceId) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *FirmwareUpdateStatusResponse) DeviceId(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func (rcv *FirmwareUpdateStatusResponse) Status() FirmwareUpdateStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return FirmwareUpdateStatus(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *FirmwareUpdateStatusResponse) MutateStatus(n FirmwareUpdateStatus) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

// / from 0 to 100
func (rcv *FirmwareUpdateStatusResponse) Progress() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

// / from 0 to 100
func (rcv *FirmwareUpdateStatusResponse) MutateProgress(n int8) bool {
	return rcv._tab.MutateInt8Slot(10, n)
}

func FirmwareUpdateStatusResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func FirmwareUpdateStatusResponseAddDeviceIdType(builder *flatbuffers.Builder, deviceIdType FirmwareUpdateDeviceId) {
	builder.PrependByteSlot(0, byte(deviceIdType), 0)
}
func FirmwareUpdateStatusResponseAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(deviceId), 0)
}
func FirmwareUpdateStatusResponseAddStatus(builder *flatbuffers.Builder, status FirmwareUpdateStatus) {
	builder.PrependByteSlot(2, byte(status), 0)
}
func FirmwareUpdateStatusResponseAddProgress(builder *flatbuffers.Builder, progress int8) {
	builder.PrependInt8Slot(3, progress, 0)
}
func FirmwareUpdateStatusResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
