// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import "strconv"

type FirmwareUpdateMethod byte

const (
	FirmwareUpdateMethodNONE                 FirmwareUpdateMethod = 0
	FirmwareUpdateMethodOTAFirmwareUpdate    FirmwareUpdateMethod = 1
	FirmwareUpdateMethodSerialFirmwareUpdate FirmwareUpdateMethod = 2
)

var EnumNamesFirmwareUpdateMethod = map[FirmwareUpdateMethod]string{
	FirmwareUpdateMethodNONE:                 "NONE",
	FirmwareUpdateMethodOTAFirmwareUpdate:    "OTAFirmwareUpdate",
	FirmwareUpdateMethodSerialFirmwareUpdate: "SerialFirmwareUpdate",
}

var EnumValuesFirmwareUpdateMethod = map[string]FirmwareUpdateMethod{
	"NONE":                 FirmwareUpdateMethodNONE,
	"OTAFirmwareUpdate":    FirmwareUpdateMethodOTAFirmwareUpdate,
	"SerialFirmwareUpdate": FirmwareUpdateMethodSerialFirmwareUpdate,
}

func (v FirmwareUpdateMethod) String() string {
	if s, ok := EnumNamesFirmwareUpdateMethod[v]; ok {
		return s
	}
	return "FirmwareUpdateMethod(" + strconv.FormatInt(int64(v), 10) + ")"
}
