// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import "strconv"

type FirmwareUpdateDeviceId byte

const (
	FirmwareUpdateDeviceIdNONE                                     FirmwareUpdateDeviceId = 0
	FirmwareUpdateDeviceIdsolarxr_protocol_datatypes_DeviceIdTable FirmwareUpdateDeviceId = 1
	FirmwareUpdateDeviceIdSerialDevicePort                         FirmwareUpdateDeviceId = 2
)

var EnumNamesFirmwareUpdateDeviceId = map[FirmwareUpdateDeviceId]string{
	FirmwareUpdateDeviceIdNONE:                                     "NONE",
	FirmwareUpdateDeviceIdsolarxr_protocol_datatypes_DeviceIdTable: "solarxr_protocol_datatypes_DeviceIdTable",
	FirmwareUpdateDeviceIdSerialDevicePort:                         "SerialDevicePort",
}

var EnumValuesFirmwareUpdateDeviceId = map[string]FirmwareUpdateDeviceId{
	"NONE": FirmwareUpdateDeviceIdNONE,
	"solarxr_protocol_datatypes_DeviceIdTable": FirmwareUpdateDeviceIdsolarxr_protocol_datatypes_DeviceIdTable,
	"SerialDevicePort":                         FirmwareUpdateDeviceIdSerialDevicePort,
}

func (v FirmwareUpdateDeviceId) String() string {
	if s, ok := EnumNamesFirmwareUpdateDeviceId[v]; ok {
		return s
	}
	return "FirmwareUpdateDeviceId(" + strconv.FormatInt(int64(v), 10) + ")"
}
