// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FirmwareUpdateStopQueuesRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsFirmwareUpdateStopQueuesRequest(buf []byte, offset flatbuffers.UOffsetT) *FirmwareUpdateStopQueuesRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FirmwareUpdateStopQueuesRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishFirmwareUpdateStopQueuesRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFirmwareUpdateStopQueuesRequest(buf []byte, offset flatbuffers.UOffsetT) *FirmwareUpdateStopQueuesRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FirmwareUpdateStopQueuesRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFirmwareUpdateStopQueuesRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FirmwareUpdateStopQueuesRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FirmwareUpdateStopQueuesRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func FirmwareUpdateStopQueuesRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func FirmwareUpdateStopQueuesRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
