// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import "strconv"

type FirmwareUpdateStatus byte

const (
	/// The server is downloading the firmware
	FirmwareUpdateStatusDOWNLOADING FirmwareUpdateStatus = 0
	/// The server is waiting for the tracker to be rebooted by the user
	/// Note that is is not the same as REBOOTING
	FirmwareUpdateStatusNEED_MANUAL_REBOOT FirmwareUpdateStatus = 1
	/// The server tries to authenticate with the MCU
	FirmwareUpdateStatusAUTHENTICATING FirmwareUpdateStatus = 2
	/// The server is uploading the firmware to the Device
	FirmwareUpdateStatusUPLOADING FirmwareUpdateStatus = 3
	/// The serial flasher tries to sync with the MCU
	/// You can use this event to prompt the user to press the boot btn
	FirmwareUpdateStatusSYNCING_WITH_MCU FirmwareUpdateStatus = 4
	/// The MCU is rebooting
	FirmwareUpdateStatusREBOOTING FirmwareUpdateStatus = 5
	/// The server is provisioning the tracker
	FirmwareUpdateStatusPROVISIONING FirmwareUpdateStatus = 6
	FirmwareUpdateStatusDONE         FirmwareUpdateStatus = 7
	/// Could not find the device
	FirmwareUpdateStatusERROR_DEVICE_NOT_FOUND FirmwareUpdateStatus = 8
	/// The operation timed out, > 1min
	FirmwareUpdateStatusERROR_TIMEOUT FirmwareUpdateStatus = 9
	/// The firmware download failed
	FirmwareUpdateStatusERROR_DOWNLOAD_FAILED FirmwareUpdateStatus = 10
	/// The server could not authenticate with the MCU
	FirmwareUpdateStatusERROR_AUTHENTICATION_FAILED FirmwareUpdateStatus = 11
	/// Could not upload the firmware to the MCU
	FirmwareUpdateStatusERROR_UPLOAD_FAILED FirmwareUpdateStatus = 12
	/// The provision of the tracker failed, usually wifi credentials
	FirmwareUpdateStatusERROR_PROVISIONING_FAILED FirmwareUpdateStatus = 13
	/// An unsupported Flashing method was used
	FirmwareUpdateStatusERROR_UNSUPPORTED_METHOD FirmwareUpdateStatus = 14
	FirmwareUpdateStatusERROR_UNKNOWN            FirmwareUpdateStatus = 15
)

var EnumNamesFirmwareUpdateStatus = map[FirmwareUpdateStatus]string{
	FirmwareUpdateStatusDOWNLOADING:                 "DOWNLOADING",
	FirmwareUpdateStatusNEED_MANUAL_REBOOT:          "NEED_MANUAL_REBOOT",
	FirmwareUpdateStatusAUTHENTICATING:              "AUTHENTICATING",
	FirmwareUpdateStatusUPLOADING:                   "UPLOADING",
	FirmwareUpdateStatusSYNCING_WITH_MCU:            "SYNCING_WITH_MCU",
	FirmwareUpdateStatusREBOOTING:                   "REBOOTING",
	FirmwareUpdateStatusPROVISIONING:                "PROVISIONING",
	FirmwareUpdateStatusDONE:                        "DONE",
	FirmwareUpdateStatusERROR_DEVICE_NOT_FOUND:      "ERROR_DEVICE_NOT_FOUND",
	FirmwareUpdateStatusERROR_TIMEOUT:               "ERROR_TIMEOUT",
	FirmwareUpdateStatusERROR_DOWNLOAD_FAILED:       "ERROR_DOWNLOAD_FAILED",
	FirmwareUpdateStatusERROR_AUTHENTICATION_FAILED: "ERROR_AUTHENTICATION_FAILED",
	FirmwareUpdateStatusERROR_UPLOAD_FAILED:         "ERROR_UPLOAD_FAILED",
	FirmwareUpdateStatusERROR_PROVISIONING_FAILED:   "ERROR_PROVISIONING_FAILED",
	FirmwareUpdateStatusERROR_UNSUPPORTED_METHOD:    "ERROR_UNSUPPORTED_METHOD",
	FirmwareUpdateStatusERROR_UNKNOWN:               "ERROR_UNKNOWN",
}

var EnumValuesFirmwareUpdateStatus = map[string]FirmwareUpdateStatus{
	"DOWNLOADING":                 FirmwareUpdateStatusDOWNLOADING,
	"NEED_MANUAL_REBOOT":          FirmwareUpdateStatusNEED_MANUAL_REBOOT,
	"AUTHENTICATING":              FirmwareUpdateStatusAUTHENTICATING,
	"UPLOADING":                   FirmwareUpdateStatusUPLOADING,
	"SYNCING_WITH_MCU":            FirmwareUpdateStatusSYNCING_WITH_MCU,
	"REBOOTING":                   FirmwareUpdateStatusREBOOTING,
	"PROVISIONING":                FirmwareUpdateStatusPROVISIONING,
	"DONE":                        FirmwareUpdateStatusDONE,
	"ERROR_DEVICE_NOT_FOUND":      FirmwareUpdateStatusERROR_DEVICE_NOT_FOUND,
	"ERROR_TIMEOUT":               FirmwareUpdateStatusERROR_TIMEOUT,
	"ERROR_DOWNLOAD_FAILED":       FirmwareUpdateStatusERROR_DOWNLOAD_FAILED,
	"ERROR_AUTHENTICATION_FAILED": FirmwareUpdateStatusERROR_AUTHENTICATION_FAILED,
	"ERROR_UPLOAD_FAILED":         FirmwareUpdateStatusERROR_UPLOAD_FAILED,
	"ERROR_PROVISIONING_FAILED":   FirmwareUpdateStatusERROR_PROVISIONING_FAILED,
	"ERROR_UNSUPPORTED_METHOD":    FirmwareUpdateStatusERROR_UNSUPPORTED_METHOD,
	"ERROR_UNKNOWN":               FirmwareUpdateStatusERROR_UNKNOWN,
}

func (v FirmwareUpdateStatus) String() string {
	if s, ok := EnumNamesFirmwareUpdateStatus[v]; ok {
		return s
	}
	return "FirmwareUpdateStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
