// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HeartbeatResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsHeartbeatResponse(buf []byte, offset flatbuffers.UOffsetT) *HeartbeatResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HeartbeatResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishHeartbeatResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHeartbeatResponse(buf []byte, offset flatbuffers.UOffsetT) *HeartbeatResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HeartbeatResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHeartbeatResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HeartbeatResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HeartbeatResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func HeartbeatResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func HeartbeatResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
