// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HeightRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsHeightRequest(buf []byte, offset flatbuffers.UOffsetT) *HeightRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HeightRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishHeightRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHeightRequest(buf []byte, offset flatbuffers.UOffsetT) *HeightRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HeightRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHeightRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HeightRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HeightRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func HeightRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func HeightRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
