// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Returns the current min and max positional tracker heights
type HeightResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsHeightResponse(buf []byte, offset flatbuffers.UOffsetT) *HeightResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HeightResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishHeightResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHeightResponse(buf []byte, offset flatbuffers.UOffsetT) *HeightResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HeightResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHeightResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HeightResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HeightResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HeightResponse) MinHeight() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *HeightResponse) MutateMinHeight(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *HeightResponse) MaxHeight() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *HeightResponse) MutateMaxHeight(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func HeightResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func HeightResponseAddMinHeight(builder *flatbuffers.Builder, minHeight float32) {
	builder.PrependFloat32Slot(0, minHeight, 0.0)
}
func HeightResponseAddMaxHeight(builder *flatbuffers.Builder, maxHeight float32) {
	builder.PrependFloat32Slot(1, maxHeight, 0.0)
}
func HeightResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
