// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HIDSettings struct {
	_tab flatbuffers.Table
}

func GetRootAsHIDSettings(buf []byte, offset flatbuffers.UOffsetT) *HIDSettings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HIDSettings{}
	x.Init(buf, n+offset)
	return x
}

func FinishHIDSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHIDSettings(buf []byte, offset flatbuffers.UOffsetT) *HIDSettings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HIDSettings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHIDSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HIDSettings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HIDSettings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HIDSettings) TrackersOverHid() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *HIDSettings) MutateTrackersOverHid(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func HIDSettingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func HIDSettingsAddTrackersOverHid(builder *flatbuffers.Builder, trackersOverHid bool) {
	builder.PrependBoolSlot(0, trackersOverHid, false)
}
func HIDSettingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
