// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InstalledInfoResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsInstalledInfoResponse(buf []byte, offset flatbuffers.UOffsetT) *InstalledInfoResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InstalledInfoResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishInstalledInfoResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInstalledInfoResponse(buf []byte, offset flatbuffers.UOffsetT) *InstalledInfoResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InstalledInfoResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInstalledInfoResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InstalledInfoResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InstalledInfoResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InstalledInfoResponse) IsUdevInstalled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *InstalledInfoResponse) MutateIsUdevInstalled(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *InstalledInfoResponse) IsWayland() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *InstalledInfoResponse) MutateIsWayland(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func InstalledInfoResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func InstalledInfoResponseAddIsUdevInstalled(builder *flatbuffers.Builder, isUdevInstalled bool) {
	builder.PrependBoolSlot(0, isUdevInstalled, false)
}
func InstalledInfoResponseAddIsWayland(builder *flatbuffers.Builder, isWayland bool) {
	builder.PrependBoolSlot(1, isWayland, false)
}
func InstalledInfoResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
