// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InstalledInfoRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsInstalledInfoRequest(buf []byte, offset flatbuffers.UOffsetT) *InstalledInfoRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InstalledInfoRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishInstalledInfoRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInstalledInfoRequest(buf []byte, offset flatbuffers.UOffsetT) *InstalledInfoRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InstalledInfoRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInstalledInfoRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InstalledInfoRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InstalledInfoRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func InstalledInfoRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func InstalledInfoRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
