// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KeybindRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsKeybindRequest(buf []byte, offset flatbuffers.UOffsetT) *KeybindRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KeybindRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishKeybindRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsKeybindRequest(buf []byte, offset flatbuffers.UOffsetT) *KeybindRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KeybindRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKeybindRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *KeybindRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KeybindRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KeybindRequest) KeybindId() KeybindId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return KeybindId(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *KeybindRequest) MutateKeybindId(n KeybindId) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func KeybindRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func KeybindRequestAddKeybindId(builder *flatbuffers.Builder, keybindId KeybindId) {
	builder.PrependByteSlot(0, byte(keybindId), 0)
}
func KeybindRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
