// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import "strconv"

type KeybindId byte

const (
	KeybindIdFULL_RESET          KeybindId = 0
	KeybindIdYAW_RESET           KeybindId = 1
	KeybindIdMOUNTING_RESET      KeybindId = 2
	KeybindIdPAUSE_TRACKING      KeybindId = 3
	KeybindIdFEET_MOUNTING_RESET KeybindId = 4
)

var EnumNamesKeybindId = map[KeybindId]string{
	KeybindIdFULL_RESET:          "FULL_RESET",
	KeybindIdYAW_RESET:           "YAW_RESET",
	KeybindIdMOUNTING_RESET:      "MOUNTING_RESET",
	KeybindIdPAUSE_TRACKING:      "PAUSE_TRACKING",
	KeybindIdFEET_MOUNTING_RESET: "FEET_MOUNTING_RESET",
}

var EnumValuesKeybindId = map[string]KeybindId{
	"FULL_RESET":          KeybindIdFULL_RESET,
	"YAW_RESET":           KeybindIdYAW_RESET,
	"MOUNTING_RESET":      KeybindIdMOUNTING_RESET,
	"PAUSE_TRACKING":      KeybindIdPAUSE_TRACKING,
	"FEET_MOUNTING_RESET": KeybindIdFEET_MOUNTING_RESET,
}

func (v KeybindId) String() string {
	if s, ok := EnumNamesKeybindId[v]; ok {
		return s
	}
	return "KeybindId(" + strconv.FormatInt(int64(v), 10) + ")"
}
