// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Keybind struct {
	_tab flatbuffers.Table
}

func GetRootAsKeybind(buf []byte, offset flatbuffers.UOffsetT) *Keybind {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Keybind{}
	x.Init(buf, n+offset)
	return x
}

func FinishKeybindBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsKeybind(buf []byte, offset flatbuffers.UOffsetT) *Keybind {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Keybind{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKeybindBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Keybind) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Keybind) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Keybind) KeybindId() KeybindId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return KeybindId(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Keybind) MutateKeybindId(n KeybindId) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *Keybind) KeybindNameId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Keybind) KeybindValue() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Keybind) KeybindDelay() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Keybind) MutateKeybindDelay(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func KeybindStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func KeybindAddKeybindId(builder *flatbuffers.Builder, keybindId KeybindId) {
	builder.PrependByteSlot(0, byte(keybindId), 0)
}
func KeybindAddKeybindNameId(builder *flatbuffers.Builder, keybindNameId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(keybindNameId), 0)
}
func KeybindAddKeybindValue(builder *flatbuffers.Builder, keybindValue flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(keybindValue), 0)
}
func KeybindAddKeybindDelay(builder *flatbuffers.Builder, keybindDelay float32) {
	builder.PrependFloat32Slot(3, keybindDelay, 0.0)
}
func KeybindEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
