// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Makes a temporary change to legtweaks. This is not saved to disk, and can be
// / cleared with `LegTweaksTmpClear`
type LegTweaksTmpChange struct {
	_tab flatbuffers.Table
}

func GetRootAsLegTweaksTmpChange(buf []byte, offset flatbuffers.UOffsetT) *LegTweaksTmpChange {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LegTweaksTmpChange{}
	x.Init(buf, n+offset)
	return x
}

func FinishLegTweaksTmpChangeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLegTweaksTmpChange(buf []byte, offset flatbuffers.UOffsetT) *LegTweaksTmpChange {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LegTweaksTmpChange{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLegTweaksTmpChangeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LegTweaksTmpChange) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LegTweaksTmpChange) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LegTweaksTmpChange) FloorClip() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *LegTweaksTmpChange) MutateFloorClip(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *LegTweaksTmpChange) SkatingCorrection() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *LegTweaksTmpChange) MutateSkatingCorrection(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *LegTweaksTmpChange) ToeSnap() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *LegTweaksTmpChange) MutateToeSnap(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *LegTweaksTmpChange) FootPlant() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *LegTweaksTmpChange) MutateFootPlant(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func LegTweaksTmpChangeStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func LegTweaksTmpChangeAddFloorClip(builder *flatbuffers.Builder, floorClip bool) {
	builder.PrependBool(floorClip)
	builder.Slot(0)
}
func LegTweaksTmpChangeAddSkatingCorrection(builder *flatbuffers.Builder, skatingCorrection bool) {
	builder.PrependBool(skatingCorrection)
	builder.Slot(1)
}
func LegTweaksTmpChangeAddToeSnap(builder *flatbuffers.Builder, toeSnap bool) {
	builder.PrependBool(toeSnap)
	builder.Slot(2)
}
func LegTweaksTmpChangeAddFootPlant(builder *flatbuffers.Builder, footPlant bool) {
	builder.PrependBool(footPlant)
	builder.Slot(3)
}
func LegTweaksTmpChangeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
