// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Clears the legtweaks temporary state back to what the config has.
// / Setting a field to `true` will reset that field.
type LegTweaksTmpClear struct {
	_tab flatbuffers.Table
}

func GetRootAsLegTweaksTmpClear(buf []byte, offset flatbuffers.UOffsetT) *LegTweaksTmpClear {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LegTweaksTmpClear{}
	x.Init(buf, n+offset)
	return x
}

func FinishLegTweaksTmpClearBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLegTweaksTmpClear(buf []byte, offset flatbuffers.UOffsetT) *LegTweaksTmpClear {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LegTweaksTmpClear{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLegTweaksTmpClearBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LegTweaksTmpClear) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LegTweaksTmpClear) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LegTweaksTmpClear) FloorClip() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *LegTweaksTmpClear) MutateFloorClip(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *LegTweaksTmpClear) SkatingCorrection() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *LegTweaksTmpClear) MutateSkatingCorrection(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *LegTweaksTmpClear) ToeSnap() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *LegTweaksTmpClear) MutateToeSnap(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *LegTweaksTmpClear) FootPlant() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *LegTweaksTmpClear) MutateFootPlant(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func LegTweaksTmpClearStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func LegTweaksTmpClearAddFloorClip(builder *flatbuffers.Builder, floorClip bool) {
	builder.PrependBoolSlot(0, floorClip, false)
}
func LegTweaksTmpClearAddSkatingCorrection(builder *flatbuffers.Builder, skatingCorrection bool) {
	builder.PrependBoolSlot(1, skatingCorrection, false)
}
func LegTweaksTmpClearAddToeSnap(builder *flatbuffers.Builder, toeSnap bool) {
	builder.PrependBoolSlot(2, toeSnap, false)
}
func LegTweaksTmpClearAddFootPlant(builder *flatbuffers.Builder, footPlant bool) {
	builder.PrependBoolSlot(3, footPlant, false)
}
func LegTweaksTmpClearEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
