// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
)

// / If no tracker ID is given, it's the setting for every tracker/device
type MagToggleResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsMagToggleResponse(buf []byte, offset flatbuffers.UOffsetT) *MagToggleResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MagToggleResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishMagToggleResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMagToggleResponse(buf []byte, offset flatbuffers.UOffsetT) *MagToggleResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MagToggleResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMagToggleResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MagToggleResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MagToggleResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MagToggleResponse) TrackerId(obj *solarxr_protocol__datatypes.TrackerId) *solarxr_protocol__datatypes.TrackerId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(solarxr_protocol__datatypes.TrackerId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *MagToggleResponse) Enable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *MagToggleResponse) MutateEnable(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func MagToggleResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MagToggleResponseAddTrackerId(builder *flatbuffers.Builder, trackerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(trackerId), 0)
}
func MagToggleResponseAddEnable(builder *flatbuffers.Builder, enable bool) {
	builder.PrependBoolSlot(1, enable, false)
}
func MagToggleResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
