// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
)

// / If no tracker ID is given, it's the setting for every tracker/device
type MagToggleRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsMagToggleRequest(buf []byte, offset flatbuffers.UOffsetT) *MagToggleRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MagToggleRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishMagToggleRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMagToggleRequest(buf []byte, offset flatbuffers.UOffsetT) *MagToggleRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MagToggleRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMagToggleRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MagToggleRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MagToggleRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MagToggleRequest) TrackerId(obj *solarxr_protocol__datatypes.TrackerId) *solarxr_protocol__datatypes.TrackerId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(solarxr_protocol__datatypes.TrackerId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func MagToggleRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MagToggleRequestAddTrackerId(builder *flatbuffers.Builder, trackerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(trackerId), 0)
}
func MagToggleRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
