// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NewSerialDeviceResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsNewSerialDeviceResponse(buf []byte, offset flatbuffers.UOffsetT) *NewSerialDeviceResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NewSerialDeviceResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishNewSerialDeviceResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNewSerialDeviceResponse(buf []byte, offset flatbuffers.UOffsetT) *NewSerialDeviceResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NewSerialDeviceResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNewSerialDeviceResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *NewSerialDeviceResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NewSerialDeviceResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NewSerialDeviceResponse) Device(obj *SerialDevice) *SerialDevice {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(SerialDevice)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func NewSerialDeviceResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func NewSerialDeviceResponseAddDevice(builder *flatbuffers.Builder, device flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(device), 0)
}
func NewSerialDeviceResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
