// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OpenUriRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsOpenUriRequest(buf []byte, offset flatbuffers.UOffsetT) *OpenUriRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OpenUriRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishOpenUriRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOpenUriRequest(buf []byte, offset flatbuffers.UOffsetT) *OpenUriRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OpenUriRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOpenUriRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OpenUriRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OpenUriRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func OpenUriRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func OpenUriRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
