// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OpenUriResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsOpenUriResponse(buf []byte, offset flatbuffers.UOffsetT) *OpenUriResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OpenUriResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishOpenUriResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOpenUriResponse(buf []byte, offset flatbuffers.UOffsetT) *OpenUriResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OpenUriResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOpenUriResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OpenUriResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OpenUriResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OpenUriResponse) Success() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OpenUriResponse) MutateSuccess(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func OpenUriResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func OpenUriResponseAddSuccess(builder *flatbuffers.Builder, success bool) {
	builder.PrependBoolSlot(0, success, false)
}
func OpenUriResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
