// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OpenSerialRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsOpenSerialRequest(buf []byte, offset flatbuffers.UOffsetT) *OpenSerialRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OpenSerialRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishOpenSerialRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOpenSerialRequest(buf []byte, offset flatbuffers.UOffsetT) *OpenSerialRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OpenSerialRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOpenSerialRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OpenSerialRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OpenSerialRequest) Table() flatbuffers.Table {
	return rcv._tab
}

// / Automatically pick the first serial device available
func (rcv *OpenSerialRequest) Auto() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

// / Automatically pick the first serial device available
func (rcv *OpenSerialRequest) MutateAuto(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *OpenSerialRequest) Port() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func OpenSerialRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OpenSerialRequestAddAuto(builder *flatbuffers.Builder, auto bool) {
	builder.PrependBoolSlot(0, auto, false)
}
func OpenSerialRequestAddPort(builder *flatbuffers.Builder, port flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(port), 0)
}
func OpenSerialRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
