// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OSCTrackersSetting struct {
	_tab flatbuffers.Table
}

func GetRootAsOSCTrackersSetting(buf []byte, offset flatbuffers.UOffsetT) *OSCTrackersSetting {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OSCTrackersSetting{}
	x.Init(buf, n+offset)
	return x
}

func FinishOSCTrackersSettingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOSCTrackersSetting(buf []byte, offset flatbuffers.UOffsetT) *OSCTrackersSetting {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OSCTrackersSetting{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOSCTrackersSettingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OSCTrackersSetting) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OSCTrackersSetting) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OSCTrackersSetting) Head() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OSCTrackersSetting) MutateHead(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *OSCTrackersSetting) Chest() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OSCTrackersSetting) MutateChest(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *OSCTrackersSetting) Waist() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OSCTrackersSetting) MutateWaist(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *OSCTrackersSetting) Knees() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OSCTrackersSetting) MutateKnees(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *OSCTrackersSetting) Feet() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OSCTrackersSetting) MutateFeet(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *OSCTrackersSetting) Elbows() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OSCTrackersSetting) MutateElbows(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func (rcv *OSCTrackersSetting) Hands() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OSCTrackersSetting) MutateHands(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func OSCTrackersSettingStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func OSCTrackersSettingAddHead(builder *flatbuffers.Builder, head bool) {
	builder.PrependBoolSlot(0, head, false)
}
func OSCTrackersSettingAddChest(builder *flatbuffers.Builder, chest bool) {
	builder.PrependBoolSlot(1, chest, false)
}
func OSCTrackersSettingAddWaist(builder *flatbuffers.Builder, waist bool) {
	builder.PrependBoolSlot(2, waist, false)
}
func OSCTrackersSettingAddKnees(builder *flatbuffers.Builder, knees bool) {
	builder.PrependBoolSlot(3, knees, false)
}
func OSCTrackersSettingAddFeet(builder *flatbuffers.Builder, feet bool) {
	builder.PrependBoolSlot(4, feet, false)
}
func OSCTrackersSettingAddElbows(builder *flatbuffers.Builder, elbows bool) {
	builder.PrependBoolSlot(5, elbows, false)
}
func OSCTrackersSettingAddHands(builder *flatbuffers.Builder, hands bool) {
	builder.PrependBoolSlot(6, hands, false)
}
func OSCTrackersSettingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
