// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
)

type OTAFirmwareUpdate struct {
	_tab flatbuffers.Table
}

func GetRootAsOTAFirmwareUpdate(buf []byte, offset flatbuffers.UOffsetT) *OTAFirmwareUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OTAFirmwareUpdate{}
	x.Init(buf, n+offset)
	return x
}

func FinishOTAFirmwareUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOTAFirmwareUpdate(buf []byte, offset flatbuffers.UOffsetT) *OTAFirmwareUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OTAFirmwareUpdate{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOTAFirmwareUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OTAFirmwareUpdate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OTAFirmwareUpdate) Table() flatbuffers.Table {
	return rcv._tab
}

// / id of the device, this refer to the actual DeviceId from the protocol
func (rcv *OTAFirmwareUpdate) DeviceId(obj *solarxr_protocol__datatypes.DeviceId) *solarxr_protocol__datatypes.DeviceId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(solarxr_protocol__datatypes.DeviceId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / id of the device, this refer to the actual DeviceId from the protocol
// / A table containing the url and offset of the firmware bin file
func (rcv *OTAFirmwareUpdate) FirmwarePart(obj *FirmwarePart) *FirmwarePart {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FirmwarePart)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / A table containing the url and offset of the firmware bin file
func OTAFirmwareUpdateStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OTAFirmwareUpdateAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(deviceId), 0)
}
func OTAFirmwareUpdateAddFirmwarePart(builder *flatbuffers.Builder, firmwarePart flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(firmwarePart), 0)
}
func OTAFirmwareUpdateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
