// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / The current state of the overlay's display mode.
type OverlayDisplayModeResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsOverlayDisplayModeResponse(buf []byte, offset flatbuffers.UOffsetT) *OverlayDisplayModeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OverlayDisplayModeResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishOverlayDisplayModeResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOverlayDisplayModeResponse(buf []byte, offset flatbuffers.UOffsetT) *OverlayDisplayModeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OverlayDisplayModeResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOverlayDisplayModeResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OverlayDisplayModeResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OverlayDisplayModeResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OverlayDisplayModeResponse) IsVisible() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OverlayDisplayModeResponse) MutateIsVisible(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *OverlayDisplayModeResponse) IsMirrored() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OverlayDisplayModeResponse) MutateIsMirrored(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func OverlayDisplayModeResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OverlayDisplayModeResponseAddIsVisible(builder *flatbuffers.Builder, isVisible bool) {
	builder.PrependBoolSlot(0, isVisible, false)
}
func OverlayDisplayModeResponseAddIsMirrored(builder *flatbuffers.Builder, isMirrored bool) {
	builder.PrependBoolSlot(1, isMirrored, false)
}
func OverlayDisplayModeResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
