// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Changes the state of the overlay's display mode.
type OverlayDisplayModeChangeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsOverlayDisplayModeChangeRequest(buf []byte, offset flatbuffers.UOffsetT) *OverlayDisplayModeChangeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OverlayDisplayModeChangeRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishOverlayDisplayModeChangeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOverlayDisplayModeChangeRequest(buf []byte, offset flatbuffers.UOffsetT) *OverlayDisplayModeChangeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OverlayDisplayModeChangeRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOverlayDisplayModeChangeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OverlayDisplayModeChangeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OverlayDisplayModeChangeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OverlayDisplayModeChangeRequest) IsVisible() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *OverlayDisplayModeChangeRequest) MutateIsVisible(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *OverlayDisplayModeChangeRequest) IsMirrored() *bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		v := rcv._tab.GetBool(o + rcv._tab.Pos)
		return &v
	}
	return nil
}

func (rcv *OverlayDisplayModeChangeRequest) MutateIsMirrored(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func OverlayDisplayModeChangeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OverlayDisplayModeChangeRequestAddIsVisible(builder *flatbuffers.Builder, isVisible bool) {
	builder.PrependBool(isVisible)
	builder.Slot(0)
}
func OverlayDisplayModeChangeRequestAddIsMirrored(builder *flatbuffers.Builder, isMirrored bool) {
	builder.PrependBool(isMirrored)
	builder.Slot(1)
}
func OverlayDisplayModeChangeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
