// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RecordBVHRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsRecordBVHRequest(buf []byte, offset flatbuffers.UOffsetT) *RecordBVHRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RecordBVHRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishRecordBVHRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRecordBVHRequest(buf []byte, offset flatbuffers.UOffsetT) *RecordBVHRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RecordBVHRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRecordBVHRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RecordBVHRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RecordBVHRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RecordBVHRequest) Stop() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *RecordBVHRequest) MutateStop(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

// / Path sent when starting the recording, if null the recording won't happen.
// / Has different behavior depending if its a file path or a directory path.
func (rcv *RecordBVHRequest) Path() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / Path sent when starting the recording, if null the recording won't happen.
// / Has different behavior depending if its a file path or a directory path.
func RecordBVHRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RecordBVHRequestAddStop(builder *flatbuffers.Builder, stop bool) {
	builder.PrependBoolSlot(0, stop, false)
}
func RecordBVHRequestAddPath(builder *flatbuffers.Builder, path flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(path), 0)
}
func RecordBVHRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
