// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RecordBVHStatus struct {
	_tab flatbuffers.Table
}

func GetRootAsRecordBVHStatus(buf []byte, offset flatbuffers.UOffsetT) *RecordBVHStatus {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RecordBVHStatus{}
	x.Init(buf, n+offset)
	return x
}

func FinishRecordBVHStatusBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRecordBVHStatus(buf []byte, offset flatbuffers.UOffsetT) *RecordBVHStatus {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RecordBVHStatus{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRecordBVHStatusBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RecordBVHStatus) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RecordBVHStatus) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RecordBVHStatus) Recording() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *RecordBVHStatus) MutateRecording(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func RecordBVHStatusStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RecordBVHStatusAddRecording(builder *flatbuffers.Builder, recording bool) {
	builder.PrependBoolSlot(0, recording, false)
}
func RecordBVHStatusEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
