// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RecordBVHStatusRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsRecordBVHStatusRequest(buf []byte, offset flatbuffers.UOffsetT) *RecordBVHStatusRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RecordBVHStatusRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishRecordBVHStatusRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRecordBVHStatusRequest(buf []byte, offset flatbuffers.UOffsetT) *RecordBVHStatusRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RecordBVHStatusRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRecordBVHStatusRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RecordBVHStatusRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RecordBVHStatusRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func RecordBVHStatusRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func RecordBVHStatusRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
