// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResetStayAlignedRelaxedPoseRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsResetStayAlignedRelaxedPoseRequest(buf []byte, offset flatbuffers.UOffsetT) *ResetStayAlignedRelaxedPoseRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ResetStayAlignedRelaxedPoseRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishResetStayAlignedRelaxedPoseRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsResetStayAlignedRelaxedPoseRequest(buf []byte, offset flatbuffers.UOffsetT) *ResetStayAlignedRelaxedPoseRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ResetStayAlignedRelaxedPoseRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedResetStayAlignedRelaxedPoseRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ResetStayAlignedRelaxedPoseRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ResetStayAlignedRelaxedPoseRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ResetStayAlignedRelaxedPoseRequest) Pose() StayAlignedRelaxedPose {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return StayAlignedRelaxedPose(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ResetStayAlignedRelaxedPoseRequest) MutatePose(n StayAlignedRelaxedPose) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func ResetStayAlignedRelaxedPoseRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ResetStayAlignedRelaxedPoseRequestAddPose(builder *flatbuffers.Builder, pose StayAlignedRelaxedPose) {
	builder.PrependByteSlot(0, byte(pose), 0)
}
func ResetStayAlignedRelaxedPoseRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
