// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
)

type ResetResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsResetResponse(buf []byte, offset flatbuffers.UOffsetT) *ResetResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ResetResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishResetResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsResetResponse(buf []byte, offset flatbuffers.UOffsetT) *ResetResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ResetResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedResetResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ResetResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ResetResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ResetResponse) ResetType() ResetType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ResetType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ResetResponse) MutateResetType(n ResetType) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *ResetResponse) Status() ResetStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return ResetStatus(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ResetResponse) MutateStatus(n ResetStatus) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

// / Should return the body parts reseted / being reset
func (rcv *ResetResponse) BodyParts(j int) solarxr_protocol__datatypes.BodyPart {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return solarxr_protocol__datatypes.BodyPart(rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1)))
	}
	return 0
}

func (rcv *ResetResponse) BodyPartsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ResetResponse) BodyPartsBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / Should return the body parts reseted / being reset
func (rcv *ResetResponse) MutateBodyParts(j int, n solarxr_protocol__datatypes.BodyPart) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), byte(n))
	}
	return false
}

// / gives the time in seconds passed since the start of the reset
// / is 0 when status == FINISHED
// / starts at 0
func (rcv *ResetResponse) Progress() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

// / gives the time in seconds passed since the start of the reset
// / is 0 when status == FINISHED
// / starts at 0
func (rcv *ResetResponse) MutateProgress(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *ResetResponse) Duration() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ResetResponse) MutateDuration(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func ResetResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func ResetResponseAddResetType(builder *flatbuffers.Builder, resetType ResetType) {
	builder.PrependByteSlot(0, byte(resetType), 0)
}
func ResetResponseAddStatus(builder *flatbuffers.Builder, status ResetStatus) {
	builder.PrependByteSlot(1, byte(status), 0)
}
func ResetResponseAddBodyParts(builder *flatbuffers.Builder, bodyParts flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(bodyParts), 0)
}
func ResetResponseStartBodyPartsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ResetResponseAddProgress(builder *flatbuffers.Builder, progress int32) {
	builder.PrependInt32Slot(3, progress, 0)
}
func ResetResponseAddDuration(builder *flatbuffers.Builder, duration int32) {
	builder.PrependInt32Slot(4, duration, 0)
}
func ResetResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
