// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import "strconv"

type ResetType byte

const (
	ResetTypeYaw  ResetType = 0
	ResetTypeFull ResetType = 1
	/// Second pose for calibrating mounting rotation
	ResetTypeMounting ResetType = 2
)

var EnumNamesResetType = map[ResetType]string{
	ResetTypeYaw:      "Yaw",
	ResetTypeFull:     "Full",
	ResetTypeMounting: "Mounting",
}

var EnumValuesResetType = map[string]ResetType{
	"Yaw":      ResetTypeYaw,
	"Full":     ResetTypeFull,
	"Mounting": ResetTypeMounting,
}

func (v ResetType) String() string {
	if s, ok := EnumNamesResetType[v]; ok {
		return s
	}
	return "ResetType(" + strconv.FormatInt(int64(v), 10) + ")"
}
