// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import "strconv"

type RpcMessage byte

const (
	RpcMessageNONE                                RpcMessage = 0
	RpcMessageHeartbeatRequest                    RpcMessage = 1
	RpcMessageHeartbeatResponse                   RpcMessage = 2
	RpcMessageResetRequest                        RpcMessage = 3
	RpcMessageResetResponse                       RpcMessage = 4
	RpcMessageAssignTrackerRequest                RpcMessage = 5
	RpcMessageSettingsRequest                     RpcMessage = 6
	RpcMessageSettingsResponse                    RpcMessage = 7
	RpcMessageChangeSettingsRequest               RpcMessage = 8
	RpcMessageClearDriftCompensationRequest       RpcMessage = 9
	RpcMessageRecordBVHRequest                    RpcMessage = 10
	RpcMessageRecordBVHStatus                     RpcMessage = 11
	RpcMessageSkeletonConfigRequest               RpcMessage = 12
	RpcMessageChangeSkeletonConfigRequest         RpcMessage = 13
	RpcMessageSkeletonResetAllRequest             RpcMessage = 14
	RpcMessageSkeletonConfigResponse              RpcMessage = 15
	RpcMessageOpenSerialRequest                   RpcMessage = 16
	RpcMessageCloseSerialRequest                  RpcMessage = 17
	RpcMessageSetWifiRequest                      RpcMessage = 18
	RpcMessageSerialUpdateResponse                RpcMessage = 19
	RpcMessageAutoBoneProcessRequest              RpcMessage = 20
	RpcMessageAutoBoneProcessStatusResponse       RpcMessage = 21
	RpcMessageAutoBoneEpochResponse               RpcMessage = 22
	RpcMessageOverlayDisplayModeRequest           RpcMessage = 23
	RpcMessageOverlayDisplayModeChangeRequest     RpcMessage = 24
	RpcMessageOverlayDisplayModeResponse          RpcMessage = 25
	RpcMessageSerialTrackerRebootRequest          RpcMessage = 26
	RpcMessageSerialTrackerGetInfoRequest         RpcMessage = 27
	RpcMessageSerialTrackerFactoryResetRequest    RpcMessage = 28
	RpcMessageSerialDevicesRequest                RpcMessage = 29
	RpcMessageSerialDevicesResponse               RpcMessage = 30
	RpcMessageNewSerialDeviceResponse             RpcMessage = 31
	RpcMessageStartWifiProvisioningRequest        RpcMessage = 32
	RpcMessageStopWifiProvisioningRequest         RpcMessage = 33
	RpcMessageWifiProvisioningStatusResponse      RpcMessage = 34
	RpcMessageServerInfosRequest                  RpcMessage = 35
	RpcMessageServerInfosResponse                 RpcMessage = 36
	RpcMessageLegTweaksTmpChange                  RpcMessage = 37
	RpcMessageLegTweaksTmpClear                   RpcMessage = 38
	RpcMessageTapDetectionSetupNotification       RpcMessage = 39
	RpcMessageSetPauseTrackingRequest             RpcMessage = 40
	RpcMessageStatusSystemRequest                 RpcMessage = 41
	RpcMessageStatusSystemResponse                RpcMessage = 42
	RpcMessageStatusSystemUpdate                  RpcMessage = 43
	RpcMessageStatusSystemFixed                   RpcMessage = 44
	RpcMessageClearMountingResetRequest           RpcMessage = 45
	RpcMessageHeightRequest                       RpcMessage = 46
	RpcMessageHeightResponse                      RpcMessage = 47
	RpcMessageAutoBoneApplyRequest                RpcMessage = 48
	RpcMessageAutoBoneStopRecordingRequest        RpcMessage = 49
	RpcMessageAutoBoneCancelRecordingRequest      RpcMessage = 50
	RpcMessageSaveFileNotification                RpcMessage = 51
	RpcMessageTrackingPauseStateRequest           RpcMessage = 52
	RpcMessageTrackingPauseStateResponse          RpcMessage = 53
	RpcMessageSerialTrackerGetWifiScanRequest     RpcMessage = 54
	RpcMessageUnknownDeviceHandshakeNotification  RpcMessage = 55
	RpcMessageAddUnknownDeviceRequest             RpcMessage = 56
	RpcMessageForgetDeviceRequest                 RpcMessage = 57
	RpcMessageFirmwareUpdateRequest               RpcMessage = 58
	RpcMessageFirmwareUpdateStatusResponse        RpcMessage = 59
	RpcMessageFirmwareUpdateStopQueuesRequest     RpcMessage = 60
	RpcMessageSettingsResetRequest                RpcMessage = 61
	RpcMessageMagToggleRequest                    RpcMessage = 62
	RpcMessageMagToggleResponse                   RpcMessage = 63
	RpcMessageChangeMagToggleRequest              RpcMessage = 64
	RpcMessageRecordBVHStatusRequest              RpcMessage = 65
	RpcMessageVRCConfigStateRequest               RpcMessage = 66
	RpcMessageVRCConfigStateChangeResponse        RpcMessage = 67
	RpcMessageEnableStayAlignedRequest            RpcMessage = 68
	RpcMessageDetectStayAlignedRelaxedPoseRequest RpcMessage = 69
	RpcMessageResetStayAlignedRelaxedPoseRequest  RpcMessage = 70
	RpcMessageSerialTrackerCustomCommandRequest   RpcMessage = 71
	RpcMessageVRCConfigSettingToggleMute          RpcMessage = 72
	RpcMessageTrackingChecklistRequest            RpcMessage = 73
	RpcMessageTrackingChecklistResponse           RpcMessage = 74
	RpcMessageIgnoreTrackingChecklistStepRequest  RpcMessage = 75
	RpcMessageStartUserHeightCalibration          RpcMessage = 76
	RpcMessageCancelUserHeightCalibration         RpcMessage = 77
	RpcMessageUserHeightRecordingStatusResponse   RpcMessage = 78
	RpcMessageKeybindRequest                      RpcMessage = 79
	RpcMessageChangeKeybindRequest                RpcMessage = 80
	RpcMessageKeybindResponse                     RpcMessage = 81
	RpcMessageInstalledInfoRequest                RpcMessage = 82
	RpcMessageInstalledInfoResponse               RpcMessage = 83
	RpcMessageOpenUriRequest                      RpcMessage = 84
	RpcMessageOpenUriResponse                     RpcMessage = 85
	RpcMessageEnableSteamVRDriverRequest          RpcMessage = 86
)

var EnumNamesRpcMessage = map[RpcMessage]string{
	RpcMessageNONE:                                "NONE",
	RpcMessageHeartbeatRequest:                    "HeartbeatRequest",
	RpcMessageHeartbeatResponse:                   "HeartbeatResponse",
	RpcMessageResetRequest:                        "ResetRequest",
	RpcMessageResetResponse:                       "ResetResponse",
	RpcMessageAssignTrackerRequest:                "AssignTrackerRequest",
	RpcMessageSettingsRequest:                     "SettingsRequest",
	RpcMessageSettingsResponse:                    "SettingsResponse",
	RpcMessageChangeSettingsRequest:               "ChangeSettingsRequest",
	RpcMessageClearDriftCompensationRequest:       "ClearDriftCompensationRequest",
	RpcMessageRecordBVHRequest:                    "RecordBVHRequest",
	RpcMessageRecordBVHStatus:                     "RecordBVHStatus",
	RpcMessageSkeletonConfigRequest:               "SkeletonConfigRequest",
	RpcMessageChangeSkeletonConfigRequest:         "ChangeSkeletonConfigRequest",
	RpcMessageSkeletonResetAllRequest:             "SkeletonResetAllRequest",
	RpcMessageSkeletonConfigResponse:              "SkeletonConfigResponse",
	RpcMessageOpenSerialRequest:                   "OpenSerialRequest",
	RpcMessageCloseSerialRequest:                  "CloseSerialRequest",
	RpcMessageSetWifiRequest:                      "SetWifiRequest",
	RpcMessageSerialUpdateResponse:                "SerialUpdateResponse",
	RpcMessageAutoBoneProcessRequest:              "AutoBoneProcessRequest",
	RpcMessageAutoBoneProcessStatusResponse:       "AutoBoneProcessStatusResponse",
	RpcMessageAutoBoneEpochResponse:               "AutoBoneEpochResponse",
	RpcMessageOverlayDisplayModeRequest:           "OverlayDisplayModeRequest",
	RpcMessageOverlayDisplayModeChangeRequest:     "OverlayDisplayModeChangeRequest",
	RpcMessageOverlayDisplayModeResponse:          "OverlayDisplayModeResponse",
	RpcMessageSerialTrackerRebootRequest:          "SerialTrackerRebootRequest",
	RpcMessageSerialTrackerGetInfoRequest:         "SerialTrackerGetInfoRequest",
	RpcMessageSerialTrackerFactoryResetRequest:    "SerialTrackerFactoryResetRequest",
	RpcMessageSerialDevicesRequest:                "SerialDevicesRequest",
	RpcMessageSerialDevicesResponse:               "SerialDevicesResponse",
	RpcMessageNewSerialDeviceResponse:             "NewSerialDeviceResponse",
	RpcMessageStartWifiProvisioningRequest:        "StartWifiProvisioningRequest",
	RpcMessageStopWifiProvisioningRequest:         "StopWifiProvisioningRequest",
	RpcMessageWifiProvisioningStatusResponse:      "WifiProvisioningStatusResponse",
	RpcMessageServerInfosRequest:                  "ServerInfosRequest",
	RpcMessageServerInfosResponse:                 "ServerInfosResponse",
	RpcMessageLegTweaksTmpChange:                  "LegTweaksTmpChange",
	RpcMessageLegTweaksTmpClear:                   "LegTweaksTmpClear",
	RpcMessageTapDetectionSetupNotification:       "TapDetectionSetupNotification",
	RpcMessageSetPauseTrackingRequest:             "SetPauseTrackingRequest",
	RpcMessageStatusSystemRequest:                 "StatusSystemRequest",
	RpcMessageStatusSystemResponse:                "StatusSystemResponse",
	RpcMessageStatusSystemUpdate:                  "StatusSystemUpdate",
	RpcMessageStatusSystemFixed:                   "StatusSystemFixed",
	RpcMessageClearMountingResetRequest:           "ClearMountingResetRequest",
	RpcMessageHeightRequest:                       "HeightRequest",
	RpcMessageHeightResponse:                      "HeightResponse",
	RpcMessageAutoBoneApplyRequest:                "AutoBoneApplyRequest",
	RpcMessageAutoBoneStopRecordingRequest:        "AutoBoneStopRecordingRequest",
	RpcMessageAutoBoneCancelRecordingRequest:      "AutoBoneCancelRecordingRequest",
	RpcMessageSaveFileNotification:                "SaveFileNotification",
	RpcMessageTrackingPauseStateRequest:           "TrackingPauseStateRequest",
	RpcMessageTrackingPauseStateResponse:          "TrackingPauseStateResponse",
	RpcMessageSerialTrackerGetWifiScanRequest:     "SerialTrackerGetWifiScanRequest",
	RpcMessageUnknownDeviceHandshakeNotification:  "UnknownDeviceHandshakeNotification",
	RpcMessageAddUnknownDeviceRequest:             "AddUnknownDeviceRequest",
	RpcMessageForgetDeviceRequest:                 "ForgetDeviceRequest",
	RpcMessageFirmwareUpdateRequest:               "FirmwareUpdateRequest",
	RpcMessageFirmwareUpdateStatusResponse:        "FirmwareUpdateStatusResponse",
	RpcMessageFirmwareUpdateStopQueuesRequest:     "FirmwareUpdateStopQueuesRequest",
	RpcMessageSettingsResetRequest:                "SettingsResetRequest",
	RpcMessageMagToggleRequest:                    "MagToggleRequest",
	RpcMessageMagToggleResponse:                   "MagToggleResponse",
	RpcMessageChangeMagToggleRequest:              "ChangeMagToggleRequest",
	RpcMessageRecordBVHStatusRequest:              "RecordBVHStatusRequest",
	RpcMessageVRCConfigStateRequest:               "VRCConfigStateRequest",
	RpcMessageVRCConfigStateChangeResponse:        "VRCConfigStateChangeResponse",
	RpcMessageEnableStayAlignedRequest:            "EnableStayAlignedRequest",
	RpcMessageDetectStayAlignedRelaxedPoseRequest: "DetectStayAlignedRelaxedPoseRequest",
	RpcMessageResetStayAlignedRelaxedPoseRequest:  "ResetStayAlignedRelaxedPoseRequest",
	RpcMessageSerialTrackerCustomCommandRequest:   "SerialTrackerCustomCommandRequest",
	RpcMessageVRCConfigSettingToggleMute:          "VRCConfigSettingToggleMute",
	RpcMessageTrackingChecklistRequest:            "TrackingChecklistRequest",
	RpcMessageTrackingChecklistResponse:           "TrackingChecklistResponse",
	RpcMessageIgnoreTrackingChecklistStepRequest:  "IgnoreTrackingChecklistStepRequest",
	RpcMessageStartUserHeightCalibration:          "StartUserHeightCalibration",
	RpcMessageCancelUserHeightCalibration:         "CancelUserHeightCalibration",
	RpcMessageUserHeightRecordingStatusResponse:   "UserHeightRecordingStatusResponse",
	RpcMessageKeybindRequest:                      "KeybindRequest",
	RpcMessageChangeKeybindRequest:                "ChangeKeybindRequest",
	RpcMessageKeybindResponse:                     "KeybindResponse",
	RpcMessageInstalledInfoRequest:                "InstalledInfoRequest",
	RpcMessageInstalledInfoResponse:               "InstalledInfoResponse",
	RpcMessageOpenUriRequest:                      "OpenUriRequest",
	RpcMessageOpenUriResponse:                     "OpenUriResponse",
	RpcMessageEnableSteamVRDriverRequest:          "EnableSteamVRDriverRequest",
}

var EnumValuesRpcMessage = map[string]RpcMessage{
	"NONE":                                RpcMessageNONE,
	"HeartbeatRequest":                    RpcMessageHeartbeatRequest,
	"HeartbeatResponse":                   RpcMessageHeartbeatResponse,
	"ResetRequest":                        RpcMessageResetRequest,
	"ResetResponse":                       RpcMessageResetResponse,
	"AssignTrackerRequest":                RpcMessageAssignTrackerRequest,
	"SettingsRequest":                     RpcMessageSettingsRequest,
	"SettingsResponse":                    RpcMessageSettingsResponse,
	"ChangeSettingsRequest":               RpcMessageChangeSettingsRequest,
	"ClearDriftCompensationRequest":       RpcMessageClearDriftCompensationRequest,
	"RecordBVHRequest":                    RpcMessageRecordBVHRequest,
	"RecordBVHStatus":                     RpcMessageRecordBVHStatus,
	"SkeletonConfigRequest":               RpcMessageSkeletonConfigRequest,
	"ChangeSkeletonConfigRequest":         RpcMessageChangeSkeletonConfigRequest,
	"SkeletonResetAllRequest":             RpcMessageSkeletonResetAllRequest,
	"SkeletonConfigResponse":              RpcMessageSkeletonConfigResponse,
	"OpenSerialRequest":                   RpcMessageOpenSerialRequest,
	"CloseSerialRequest":                  RpcMessageCloseSerialRequest,
	"SetWifiRequest":                      RpcMessageSetWifiRequest,
	"SerialUpdateResponse":                RpcMessageSerialUpdateResponse,
	"AutoBoneProcessRequest":              RpcMessageAutoBoneProcessRequest,
	"AutoBoneProcessStatusResponse":       RpcMessageAutoBoneProcessStatusResponse,
	"AutoBoneEpochResponse":               RpcMessageAutoBoneEpochResponse,
	"OverlayDisplayModeRequest":           RpcMessageOverlayDisplayModeRequest,
	"OverlayDisplayModeChangeRequest":     RpcMessageOverlayDisplayModeChangeRequest,
	"OverlayDisplayModeResponse":          RpcMessageOverlayDisplayModeResponse,
	"SerialTrackerRebootRequest":          RpcMessageSerialTrackerRebootRequest,
	"SerialTrackerGetInfoRequest":         RpcMessageSerialTrackerGetInfoRequest,
	"SerialTrackerFactoryResetRequest":    RpcMessageSerialTrackerFactoryResetRequest,
	"SerialDevicesRequest":                RpcMessageSerialDevicesRequest,
	"SerialDevicesResponse":               RpcMessageSerialDevicesResponse,
	"NewSerialDeviceResponse":             RpcMessageNewSerialDeviceResponse,
	"StartWifiProvisioningRequest":        RpcMessageStartWifiProvisioningRequest,
	"StopWifiProvisioningRequest":         RpcMessageStopWifiProvisioningRequest,
	"WifiProvisioningStatusResponse":      RpcMessageWifiProvisioningStatusResponse,
	"ServerInfosRequest":                  RpcMessageServerInfosRequest,
	"ServerInfosResponse":                 RpcMessageServerInfosResponse,
	"LegTweaksTmpChange":                  RpcMessageLegTweaksTmpChange,
	"LegTweaksTmpClear":                   RpcMessageLegTweaksTmpClear,
	"TapDetectionSetupNotification":       RpcMessageTapDetectionSetupNotification,
	"SetPauseTrackingRequest":             RpcMessageSetPauseTrackingRequest,
	"StatusSystemRequest":                 RpcMessageStatusSystemRequest,
	"StatusSystemResponse":                RpcMessageStatusSystemResponse,
	"StatusSystemUpdate":                  RpcMessageStatusSystemUpdate,
	"StatusSystemFixed":                   RpcMessageStatusSystemFixed,
	"ClearMountingResetRequest":           RpcMessageClearMountingResetRequest,
	"HeightRequest":                       RpcMessageHeightRequest,
	"HeightResponse":                      RpcMessageHeightResponse,
	"AutoBoneApplyRequest":                RpcMessageAutoBoneApplyRequest,
	"AutoBoneStopRecordingRequest":        RpcMessageAutoBoneStopRecordingRequest,
	"AutoBoneCancelRecordingRequest":      RpcMessageAutoBoneCancelRecordingRequest,
	"SaveFileNotification":                RpcMessageSaveFileNotification,
	"TrackingPauseStateRequest":           RpcMessageTrackingPauseStateRequest,
	"TrackingPauseStateResponse":          RpcMessageTrackingPauseStateResponse,
	"SerialTrackerGetWifiScanRequest":     RpcMessageSerialTrackerGetWifiScanRequest,
	"UnknownDeviceHandshakeNotification":  RpcMessageUnknownDeviceHandshakeNotification,
	"AddUnknownDeviceRequest":             RpcMessageAddUnknownDeviceRequest,
	"ForgetDeviceRequest":                 RpcMessageForgetDeviceRequest,
	"FirmwareUpdateRequest":               RpcMessageFirmwareUpdateRequest,
	"FirmwareUpdateStatusResponse":        RpcMessageFirmwareUpdateStatusResponse,
	"FirmwareUpdateStopQueuesRequest":     RpcMessageFirmwareUpdateStopQueuesRequest,
	"SettingsResetRequest":                RpcMessageSettingsResetRequest,
	"MagToggleRequest":                    RpcMessageMagToggleRequest,
	"MagToggleResponse":                   RpcMessageMagToggleResponse,
	"ChangeMagToggleRequest":              RpcMessageChangeMagToggleRequest,
	"RecordBVHStatusRequest":              RpcMessageRecordBVHStatusRequest,
	"VRCConfigStateRequest":               RpcMessageVRCConfigStateRequest,
	"VRCConfigStateChangeResponse":        RpcMessageVRCConfigStateChangeResponse,
	"EnableStayAlignedRequest":            RpcMessageEnableStayAlignedRequest,
	"DetectStayAlignedRelaxedPoseRequest": RpcMessageDetectStayAlignedRelaxedPoseRequest,
	"ResetStayAlignedRelaxedPoseRequest":  RpcMessageResetStayAlignedRelaxedPoseRequest,
	"SerialTrackerCustomCommandRequest":   RpcMessageSerialTrackerCustomCommandRequest,
	"VRCConfigSettingToggleMute":          RpcMessageVRCConfigSettingToggleMute,
	"TrackingChecklistRequest":            RpcMessageTrackingChecklistRequest,
	"TrackingChecklistResponse":           RpcMessageTrackingChecklistResponse,
	"IgnoreTrackingChecklistStepRequest":  RpcMessageIgnoreTrackingChecklistStepRequest,
	"StartUserHeightCalibration":          RpcMessageStartUserHeightCalibration,
	"CancelUserHeightCalibration":         RpcMessageCancelUserHeightCalibration,
	"UserHeightRecordingStatusResponse":   RpcMessageUserHeightRecordingStatusResponse,
	"KeybindRequest":                      RpcMessageKeybindRequest,
	"ChangeKeybindRequest":                RpcMessageChangeKeybindRequest,
	"KeybindResponse":                     RpcMessageKeybindResponse,
	"InstalledInfoRequest":                RpcMessageInstalledInfoRequest,
	"InstalledInfoResponse":               RpcMessageInstalledInfoResponse,
	"OpenUriRequest":                      RpcMessageOpenUriRequest,
	"OpenUriResponse":                     RpcMessageOpenUriResponse,
	"EnableSteamVRDriverRequest":          RpcMessageEnableSteamVRDriverRequest,
}

func (v RpcMessage) String() string {
	if s, ok := EnumNamesRpcMessage[v]; ok {
		return s
	}
	return "RpcMessage(" + strconv.FormatInt(int64(v), 10) + ")"
}
