// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
)

type RpcMessageHeader struct {
	_tab flatbuffers.Table
}

func GetRootAsRpcMessageHeader(buf []byte, offset flatbuffers.UOffsetT) *RpcMessageHeader {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RpcMessageHeader{}
	x.Init(buf, n+offset)
	return x
}

func FinishRpcMessageHeaderBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRpcMessageHeader(buf []byte, offset flatbuffers.UOffsetT) *RpcMessageHeader {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RpcMessageHeader{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRpcMessageHeaderBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RpcMessageHeader) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RpcMessageHeader) Table() flatbuffers.Table {
	return rcv._tab
}

// / For a request, this identifies the request. For a response, this corresponds
// / to the request that it is responding to.
func (rcv *RpcMessageHeader) TxId(obj *solarxr_protocol__datatypes.TransactionId) *solarxr_protocol__datatypes.TransactionId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(solarxr_protocol__datatypes.TransactionId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / For a request, this identifies the request. For a response, this corresponds
// / to the request that it is responding to.
func (rcv *RpcMessageHeader) MessageType() RpcMessage {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return RpcMessage(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *RpcMessageHeader) MutateMessageType(n RpcMessage) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *RpcMessageHeader) Message(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func RpcMessageHeaderStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func RpcMessageHeaderAddTxId(builder *flatbuffers.Builder, txId flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(txId), 0)
}
func RpcMessageHeaderAddMessageType(builder *flatbuffers.Builder, messageType RpcMessage) {
	builder.PrependByteSlot(1, byte(messageType), 0)
}
func RpcMessageHeaderAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(message), 0)
}
func RpcMessageHeaderEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
