// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Used for the server to save a file and have it prompt in the user side
type SaveFileNotification struct {
	_tab flatbuffers.Table
}

func GetRootAsSaveFileNotification(buf []byte, offset flatbuffers.UOffsetT) *SaveFileNotification {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SaveFileNotification{}
	x.Init(buf, n+offset)
	return x
}

func FinishSaveFileNotificationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSaveFileNotification(buf []byte, offset flatbuffers.UOffsetT) *SaveFileNotification {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SaveFileNotification{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSaveFileNotificationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SaveFileNotification) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SaveFileNotification) Table() flatbuffers.Table {
	return rcv._tab
}

// / Binary data of the file
func (rcv *SaveFileNotification) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *SaveFileNotification) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SaveFileNotification) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / Binary data of the file
func (rcv *SaveFileNotification) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

// / MIME type of file if one exists, use `file_extension` otherwise
func (rcv *SaveFileNotification) MimeType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / MIME type of file if one exists, use `file_extension` otherwise
// / Use MIME type preferably if one exists
func (rcv *SaveFileNotification) FileExtension() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / Use MIME type preferably if one exists
// / Directory recommended to save the file on
func (rcv *SaveFileNotification) ExpectedDir() *ComputerDirectory {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		v := ComputerDirectory(rcv._tab.GetByte(o + rcv._tab.Pos))
		return &v
	}
	return nil
}

// / Directory recommended to save the file on
func (rcv *SaveFileNotification) MutateExpectedDir(n ComputerDirectory) bool {
	return rcv._tab.MutateByteSlot(10, byte(n))
}

// / Recommended filename
func (rcv *SaveFileNotification) ExpectedFilename() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / Recommended filename
func SaveFileNotificationStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func SaveFileNotificationAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func SaveFileNotificationStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func SaveFileNotificationAddMimeType(builder *flatbuffers.Builder, mimeType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(mimeType), 0)
}
func SaveFileNotificationAddFileExtension(builder *flatbuffers.Builder, fileExtension flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(fileExtension), 0)
}
func SaveFileNotificationAddExpectedDir(builder *flatbuffers.Builder, expectedDir ComputerDirectory) {
	builder.PrependByte(byte(expectedDir))
	builder.Slot(3)
}
func SaveFileNotificationAddExpectedFilename(builder *flatbuffers.Builder, expectedFilename flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(expectedFilename), 0)
}
func SaveFileNotificationEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
