// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SerialDevicesResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSerialDevicesResponse(buf []byte, offset flatbuffers.UOffsetT) *SerialDevicesResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SerialDevicesResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishSerialDevicesResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSerialDevicesResponse(buf []byte, offset flatbuffers.UOffsetT) *SerialDevicesResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SerialDevicesResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSerialDevicesResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SerialDevicesResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SerialDevicesResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SerialDevicesResponse) Devices(obj *SerialDevice, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SerialDevicesResponse) DevicesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SerialDevicesResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SerialDevicesResponseAddDevices(builder *flatbuffers.Builder, devices flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(devices), 0)
}
func SerialDevicesResponseStartDevicesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SerialDevicesResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
