// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SerialDevicePort struct {
	_tab flatbuffers.Table
}

func GetRootAsSerialDevicePort(buf []byte, offset flatbuffers.UOffsetT) *SerialDevicePort {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SerialDevicePort{}
	x.Init(buf, n+offset)
	return x
}

func FinishSerialDevicePortBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSerialDevicePort(buf []byte, offset flatbuffers.UOffsetT) *SerialDevicePort {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SerialDevicePort{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSerialDevicePortBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SerialDevicePort) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SerialDevicePort) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SerialDevicePort) Port() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SerialDevicePortStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SerialDevicePortAddPort(builder *flatbuffers.Builder, port flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(port), 0)
}
func SerialDevicePortEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
