// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Sends a custom cmd to the currently connected Tracker over the Serial Monitor
type SerialTrackerCustomCommandRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSerialTrackerCustomCommandRequest(buf []byte, offset flatbuffers.UOffsetT) *SerialTrackerCustomCommandRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SerialTrackerCustomCommandRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSerialTrackerCustomCommandRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSerialTrackerCustomCommandRequest(buf []byte, offset flatbuffers.UOffsetT) *SerialTrackerCustomCommandRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SerialTrackerCustomCommandRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSerialTrackerCustomCommandRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SerialTrackerCustomCommandRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SerialTrackerCustomCommandRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SerialTrackerCustomCommandRequest) Command() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SerialTrackerCustomCommandRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SerialTrackerCustomCommandRequestAddCommand(builder *flatbuffers.Builder, command flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(command), 0)
}
func SerialTrackerCustomCommandRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
