// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SerialDevicesRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSerialDevicesRequest(buf []byte, offset flatbuffers.UOffsetT) *SerialDevicesRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SerialDevicesRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSerialDevicesRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSerialDevicesRequest(buf []byte, offset flatbuffers.UOffsetT) *SerialDevicesRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SerialDevicesRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSerialDevicesRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SerialDevicesRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SerialDevicesRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func SerialDevicesRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SerialDevicesRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
