// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SerialUpdateResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSerialUpdateResponse(buf []byte, offset flatbuffers.UOffsetT) *SerialUpdateResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SerialUpdateResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishSerialUpdateResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSerialUpdateResponse(buf []byte, offset flatbuffers.UOffsetT) *SerialUpdateResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SerialUpdateResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSerialUpdateResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SerialUpdateResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SerialUpdateResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SerialUpdateResponse) Log() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SerialUpdateResponse) Closed() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SerialUpdateResponse) MutateClosed(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *SerialUpdateResponse) Device(obj *SerialDevice) *SerialDevice {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(SerialDevice)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SerialUpdateResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SerialUpdateResponseAddLog(builder *flatbuffers.Builder, log flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(log), 0)
}
func SerialUpdateResponseAddClosed(builder *flatbuffers.Builder, closed bool) {
	builder.PrependBoolSlot(1, closed, false)
}
func SerialUpdateResponseAddDevice(builder *flatbuffers.Builder, device flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(device), 0)
}
func SerialUpdateResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
