// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Sends the FRST cmd to the currently connected Tracker over the Serial Monitor
type SerialTrackerFactoryResetRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSerialTrackerFactoryResetRequest(buf []byte, offset flatbuffers.UOffsetT) *SerialTrackerFactoryResetRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SerialTrackerFactoryResetRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSerialTrackerFactoryResetRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSerialTrackerFactoryResetRequest(buf []byte, offset flatbuffers.UOffsetT) *SerialTrackerFactoryResetRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SerialTrackerFactoryResetRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSerialTrackerFactoryResetRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SerialTrackerFactoryResetRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SerialTrackerFactoryResetRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func SerialTrackerFactoryResetRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SerialTrackerFactoryResetRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
