// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Sends the GET WIFISCAN cmd to the current tracker on the serial monitor
type SerialTrackerGetWifiScanRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSerialTrackerGetWifiScanRequest(buf []byte, offset flatbuffers.UOffsetT) *SerialTrackerGetWifiScanRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SerialTrackerGetWifiScanRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSerialTrackerGetWifiScanRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSerialTrackerGetWifiScanRequest(buf []byte, offset flatbuffers.UOffsetT) *SerialTrackerGetWifiScanRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SerialTrackerGetWifiScanRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSerialTrackerGetWifiScanRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SerialTrackerGetWifiScanRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SerialTrackerGetWifiScanRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func SerialTrackerGetWifiScanRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SerialTrackerGetWifiScanRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
