// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SerialFirmwareUpdate struct {
	_tab flatbuffers.Table
}

func GetRootAsSerialFirmwareUpdate(buf []byte, offset flatbuffers.UOffsetT) *SerialFirmwareUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SerialFirmwareUpdate{}
	x.Init(buf, n+offset)
	return x
}

func FinishSerialFirmwareUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSerialFirmwareUpdate(buf []byte, offset flatbuffers.UOffsetT) *SerialFirmwareUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SerialFirmwareUpdate{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSerialFirmwareUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SerialFirmwareUpdate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SerialFirmwareUpdate) Table() flatbuffers.Table {
	return rcv._tab
}

// / id of the device, this refer to a serial port id
func (rcv *SerialFirmwareUpdate) DeviceId(obj *SerialDevicePort) *SerialDevicePort {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(SerialDevicePort)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

// / id of the device, this refer to a serial port id
// / Will make the server ask for the tracker to be manually rebooted by the user
// / after the tracker is done flashing
func (rcv *SerialFirmwareUpdate) NeedManualReboot() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

// / Will make the server ask for the tracker to be manually rebooted by the user
// / after the tracker is done flashing
func (rcv *SerialFirmwareUpdate) MutateNeedManualReboot(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

// / Credentials to provision after the flashing
// / Only used with Serial flashing, because OTA is already connected to the wifi
func (rcv *SerialFirmwareUpdate) Ssid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / Credentials to provision after the flashing
// / Only used with Serial flashing, because OTA is already connected to the wifi
func (rcv *SerialFirmwareUpdate) Password() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / A list of urls and offsets of the different firmware files to flash
func (rcv *SerialFirmwareUpdate) FirmwarePart(obj *FirmwarePart, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SerialFirmwareUpdate) FirmwarePartLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

// / A list of urls and offsets of the different firmware files to flash
func SerialFirmwareUpdateStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func SerialFirmwareUpdateAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(deviceId), 0)
}
func SerialFirmwareUpdateAddNeedManualReboot(builder *flatbuffers.Builder, needManualReboot bool) {
	builder.PrependBoolSlot(1, needManualReboot, false)
}
func SerialFirmwareUpdateAddSsid(builder *flatbuffers.Builder, ssid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(ssid), 0)
}
func SerialFirmwareUpdateAddPassword(builder *flatbuffers.Builder, password flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(password), 0)
}
func SerialFirmwareUpdateAddFirmwarePart(builder *flatbuffers.Builder, firmwarePart flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(firmwarePart), 0)
}
func SerialFirmwareUpdateStartFirmwarePartVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SerialFirmwareUpdateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
