// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Sends the GET INFO cmd to the current tracker on the serial monitor
type SerialTrackerGetInfoRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSerialTrackerGetInfoRequest(buf []byte, offset flatbuffers.UOffsetT) *SerialTrackerGetInfoRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SerialTrackerGetInfoRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSerialTrackerGetInfoRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSerialTrackerGetInfoRequest(buf []byte, offset flatbuffers.UOffsetT) *SerialTrackerGetInfoRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SerialTrackerGetInfoRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSerialTrackerGetInfoRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SerialTrackerGetInfoRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SerialTrackerGetInfoRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func SerialTrackerGetInfoRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SerialTrackerGetInfoRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
