// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SerialDevice struct {
	_tab flatbuffers.Table
}

func GetRootAsSerialDevice(buf []byte, offset flatbuffers.UOffsetT) *SerialDevice {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SerialDevice{}
	x.Init(buf, n+offset)
	return x
}

func FinishSerialDeviceBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSerialDevice(buf []byte, offset flatbuffers.UOffsetT) *SerialDevice {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SerialDevice{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSerialDeviceBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SerialDevice) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SerialDevice) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SerialDevice) Port() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SerialDevice) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SerialDevice) Type() SerialDeviceType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return SerialDeviceType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *SerialDevice) MutateType(n SerialDeviceType) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func SerialDeviceStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SerialDeviceAddPort(builder *flatbuffers.Builder, port flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(port), 0)
}
func SerialDeviceAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func SerialDeviceAddType(builder *flatbuffers.Builder, type_ SerialDeviceType) {
	builder.PrependByteSlot(2, byte(type_), 0)
}
func SerialDeviceEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
