// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import "strconv"

type SerialDeviceType byte

const (
	SerialDeviceTypeESP_TRACKER  SerialDeviceType = 0
	SerialDeviceTypeHID_RECEIVER SerialDeviceType = 1
	SerialDeviceTypeHID_TRACKER  SerialDeviceType = 2
)

var EnumNamesSerialDeviceType = map[SerialDeviceType]string{
	SerialDeviceTypeESP_TRACKER:  "ESP_TRACKER",
	SerialDeviceTypeHID_RECEIVER: "HID_RECEIVER",
	SerialDeviceTypeHID_TRACKER:  "HID_TRACKER",
}

var EnumValuesSerialDeviceType = map[string]SerialDeviceType{
	"ESP_TRACKER":  SerialDeviceTypeESP_TRACKER,
	"HID_RECEIVER": SerialDeviceTypeHID_RECEIVER,
	"HID_TRACKER":  SerialDeviceTypeHID_TRACKER,
}

func (v SerialDeviceType) String() string {
	if s, ok := EnumNamesSerialDeviceType[v]; ok {
		return s
	}
	return "SerialDeviceType(" + strconv.FormatInt(int64(v), 10) + ")"
}
