// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Reboots the tracker connected to the serial monitor
type SerialTrackerRebootRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSerialTrackerRebootRequest(buf []byte, offset flatbuffers.UOffsetT) *SerialTrackerRebootRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SerialTrackerRebootRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSerialTrackerRebootRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSerialTrackerRebootRequest(buf []byte, offset flatbuffers.UOffsetT) *SerialTrackerRebootRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SerialTrackerRebootRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSerialTrackerRebootRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SerialTrackerRebootRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SerialTrackerRebootRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func SerialTrackerRebootRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SerialTrackerRebootRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
