// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Holds the Server information, this is a basic table holding various information about the currently running server
// / like its local ip address (useful for standalone users so they can specify the ip of the server more easily) and any more
// / infos we might want to add in the future. (like java version, working dir, server version ....)
// / This only holds the local ip for now. But there will be other information added as we chose to display them on the gui for instance
type ServerInfosResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsServerInfosResponse(buf []byte, offset flatbuffers.UOffsetT) *ServerInfosResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ServerInfosResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishServerInfosResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsServerInfosResponse(buf []byte, offset flatbuffers.UOffsetT) *ServerInfosResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ServerInfosResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedServerInfosResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ServerInfosResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ServerInfosResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ServerInfosResponse) LocalIp() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ServerInfosResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ServerInfosResponseAddLocalIp(builder *flatbuffers.Builder, localIp flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(localIp), 0)
}
func ServerInfosResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
