// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SetPauseTrackingRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSetPauseTrackingRequest(buf []byte, offset flatbuffers.UOffsetT) *SetPauseTrackingRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SetPauseTrackingRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSetPauseTrackingRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSetPauseTrackingRequest(buf []byte, offset flatbuffers.UOffsetT) *SetPauseTrackingRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SetPauseTrackingRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSetPauseTrackingRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SetPauseTrackingRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SetPauseTrackingRequest) Table() flatbuffers.Table {
	return rcv._tab
}

// / Pauses skeleton tracking if true, resumes skeleton tracking if false.
func (rcv *SetPauseTrackingRequest) PauseTracking() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

// / Pauses skeleton tracking if true, resumes skeleton tracking if false.
func (rcv *SetPauseTrackingRequest) MutatePauseTracking(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func SetPauseTrackingRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SetPauseTrackingRequestAddPauseTracking(builder *flatbuffers.Builder, pauseTracking bool) {
	builder.PrependBoolSlot(0, pauseTracking, false)
}
func SetPauseTrackingRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
