// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SettingsRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSettingsRequest(buf []byte, offset flatbuffers.UOffsetT) *SettingsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SettingsRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSettingsRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSettingsRequest(buf []byte, offset flatbuffers.UOffsetT) *SettingsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SettingsRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSettingsRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SettingsRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SettingsRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func SettingsRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SettingsRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
