// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__rpc__settings "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/rpc/settings"
)

type SettingsResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSettingsResponse(buf []byte, offset flatbuffers.UOffsetT) *SettingsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SettingsResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishSettingsResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSettingsResponse(buf []byte, offset flatbuffers.UOffsetT) *SettingsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SettingsResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSettingsResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SettingsResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SettingsResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SettingsResponse) SteamVrTrackers(obj *SteamVRTrackersSetting) *SteamVRTrackersSetting {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(SteamVRTrackersSetting)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SettingsResponse) Filtering(obj *FilteringSettings) *FilteringSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(FilteringSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SettingsResponse) DriftCompensation(obj *DriftCompensationSettings) *DriftCompensationSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DriftCompensationSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SettingsResponse) OscRouter(obj *OSCRouterSettings) *OSCRouterSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(OSCRouterSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SettingsResponse) VrcOsc(obj *VRCOSCSettings) *VRCOSCSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(VRCOSCSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SettingsResponse) VmcOsc(obj *VMCOSCSettings) *VMCOSCSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(VMCOSCSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SettingsResponse) ModelSettings(obj *solarxr_protocol__rpc__settings.ModelSettings) *solarxr_protocol__rpc__settings.ModelSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(solarxr_protocol__rpc__settings.ModelSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SettingsResponse) TapDetectionSettings(obj *TapDetectionSettings) *TapDetectionSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TapDetectionSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SettingsResponse) AutoBoneSettings(obj *AutoBoneSettings) *AutoBoneSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(AutoBoneSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SettingsResponse) ResetsSettings(obj *ResetsSettings) *ResetsSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ResetsSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SettingsResponse) StayAligned(obj *StayAlignedSettings) *StayAlignedSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(StayAlignedSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SettingsResponse) HidSettings(obj *HIDSettings) *HIDSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(HIDSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SettingsResponse) Timeout(obj *TimeoutSettings) *TimeoutSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TimeoutSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SettingsResponse) VelocitySettings(obj *VelocitySettings) *VelocitySettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(VelocitySettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SettingsResponse) Vrm(obj *VRMSettings) *VRMSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(VRMSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SettingsResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(15)
}
func SettingsResponseAddSteamVrTrackers(builder *flatbuffers.Builder, steamVrTrackers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(steamVrTrackers), 0)
}
func SettingsResponseAddFiltering(builder *flatbuffers.Builder, filtering flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(filtering), 0)
}
func SettingsResponseAddDriftCompensation(builder *flatbuffers.Builder, driftCompensation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(driftCompensation), 0)
}
func SettingsResponseAddOscRouter(builder *flatbuffers.Builder, oscRouter flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(oscRouter), 0)
}
func SettingsResponseAddVrcOsc(builder *flatbuffers.Builder, vrcOsc flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(vrcOsc), 0)
}
func SettingsResponseAddVmcOsc(builder *flatbuffers.Builder, vmcOsc flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(vmcOsc), 0)
}
func SettingsResponseAddModelSettings(builder *flatbuffers.Builder, modelSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(modelSettings), 0)
}
func SettingsResponseAddTapDetectionSettings(builder *flatbuffers.Builder, tapDetectionSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(tapDetectionSettings), 0)
}
func SettingsResponseAddAutoBoneSettings(builder *flatbuffers.Builder, autoBoneSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(autoBoneSettings), 0)
}
func SettingsResponseAddResetsSettings(builder *flatbuffers.Builder, resetsSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(resetsSettings), 0)
}
func SettingsResponseAddStayAligned(builder *flatbuffers.Builder, stayAligned flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(stayAligned), 0)
}
func SettingsResponseAddHidSettings(builder *flatbuffers.Builder, hidSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(hidSettings), 0)
}
func SettingsResponseAddTimeout(builder *flatbuffers.Builder, timeout flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(timeout), 0)
}
func SettingsResponseAddVelocitySettings(builder *flatbuffers.Builder, velocitySettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(velocitySettings), 0)
}
func SettingsResponseAddVrm(builder *flatbuffers.Builder, vrm flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(14, flatbuffers.UOffsetT(vrm), 0)
}
func SettingsResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
