// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SettingsResetRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSettingsResetRequest(buf []byte, offset flatbuffers.UOffsetT) *SettingsResetRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SettingsResetRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSettingsResetRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSettingsResetRequest(buf []byte, offset flatbuffers.UOffsetT) *SettingsResetRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SettingsResetRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSettingsResetRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SettingsResetRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SettingsResetRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func SettingsResetRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SettingsResetRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
