// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SetWifiRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSetWifiRequest(buf []byte, offset flatbuffers.UOffsetT) *SetWifiRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SetWifiRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSetWifiRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSetWifiRequest(buf []byte, offset flatbuffers.UOffsetT) *SetWifiRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SetWifiRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSetWifiRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SetWifiRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SetWifiRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SetWifiRequest) Ssid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SetWifiRequest) Password() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SetWifiRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SetWifiRequestAddSsid(builder *flatbuffers.Builder, ssid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ssid), 0)
}
func SetWifiRequestAddPassword(builder *flatbuffers.Builder, password flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(password), 0)
}
func SetWifiRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
