// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SkeletonConfigRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSkeletonConfigRequest(buf []byte, offset flatbuffers.UOffsetT) *SkeletonConfigRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SkeletonConfigRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSkeletonConfigRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSkeletonConfigRequest(buf []byte, offset flatbuffers.UOffsetT) *SkeletonConfigRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SkeletonConfigRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSkeletonConfigRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SkeletonConfigRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SkeletonConfigRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func SkeletonConfigRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SkeletonConfigRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
