// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SkeletonPart struct {
	_tab flatbuffers.Table
}

func GetRootAsSkeletonPart(buf []byte, offset flatbuffers.UOffsetT) *SkeletonPart {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SkeletonPart{}
	x.Init(buf, n+offset)
	return x
}

func FinishSkeletonPartBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSkeletonPart(buf []byte, offset flatbuffers.UOffsetT) *SkeletonPart {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SkeletonPart{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSkeletonPartBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SkeletonPart) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SkeletonPart) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SkeletonPart) Bone() SkeletonBone {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return SkeletonBone(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *SkeletonPart) MutateBone(n SkeletonBone) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *SkeletonPart) Value() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *SkeletonPart) MutateValue(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func SkeletonPartStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SkeletonPartAddBone(builder *flatbuffers.Builder, bone SkeletonBone) {
	builder.PrependByteSlot(0, byte(bone), 0)
}
func SkeletonPartAddValue(builder *flatbuffers.Builder, value float32) {
	builder.PrependFloat32Slot(1, value, 0.0)
}
func SkeletonPartEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
