// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SkeletonResetAllRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSkeletonResetAllRequest(buf []byte, offset flatbuffers.UOffsetT) *SkeletonResetAllRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SkeletonResetAllRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSkeletonResetAllRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSkeletonResetAllRequest(buf []byte, offset flatbuffers.UOffsetT) *SkeletonResetAllRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SkeletonResetAllRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSkeletonResetAllRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SkeletonResetAllRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SkeletonResetAllRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func SkeletonResetAllRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SkeletonResetAllRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
