// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import "strconv"

type SkeletonBone byte

const (
	SkeletonBoneNONE               SkeletonBone = 0
	SkeletonBoneHEAD               SkeletonBone = 1
	SkeletonBoneNECK               SkeletonBone = 2
	SkeletonBoneCHEST              SkeletonBone = 3
	SkeletonBoneCHEST_OFFSET       SkeletonBone = 4
	SkeletonBoneWAIST              SkeletonBone = 5
	SkeletonBoneHIP                SkeletonBone = 6
	SkeletonBoneHIP_OFFSET         SkeletonBone = 7
	SkeletonBoneHIPS_WIDTH         SkeletonBone = 8
	SkeletonBoneUPPER_LEG          SkeletonBone = 9
	SkeletonBoneLOWER_LEG          SkeletonBone = 10
	SkeletonBoneFOOT_LENGTH        SkeletonBone = 11
	SkeletonBoneFOOT_SHIFT         SkeletonBone = 12
	SkeletonBoneSKELETON_OFFSET    SkeletonBone = 13
	SkeletonBoneSHOULDERS_DISTANCE SkeletonBone = 14
	SkeletonBoneSHOULDERS_WIDTH    SkeletonBone = 15
	SkeletonBoneUPPER_ARM          SkeletonBone = 16
	SkeletonBoneLOWER_ARM          SkeletonBone = 17
	SkeletonBoneHAND_Y             SkeletonBone = 18
	SkeletonBoneHAND_Z             SkeletonBone = 19
	SkeletonBoneELBOW_OFFSET       SkeletonBone = 20
	SkeletonBoneUPPER_CHEST        SkeletonBone = 21
)

var EnumNamesSkeletonBone = map[SkeletonBone]string{
	SkeletonBoneNONE:               "NONE",
	SkeletonBoneHEAD:               "HEAD",
	SkeletonBoneNECK:               "NECK",
	SkeletonBoneCHEST:              "CHEST",
	SkeletonBoneCHEST_OFFSET:       "CHEST_OFFSET",
	SkeletonBoneWAIST:              "WAIST",
	SkeletonBoneHIP:                "HIP",
	SkeletonBoneHIP_OFFSET:         "HIP_OFFSET",
	SkeletonBoneHIPS_WIDTH:         "HIPS_WIDTH",
	SkeletonBoneUPPER_LEG:          "UPPER_LEG",
	SkeletonBoneLOWER_LEG:          "LOWER_LEG",
	SkeletonBoneFOOT_LENGTH:        "FOOT_LENGTH",
	SkeletonBoneFOOT_SHIFT:         "FOOT_SHIFT",
	SkeletonBoneSKELETON_OFFSET:    "SKELETON_OFFSET",
	SkeletonBoneSHOULDERS_DISTANCE: "SHOULDERS_DISTANCE",
	SkeletonBoneSHOULDERS_WIDTH:    "SHOULDERS_WIDTH",
	SkeletonBoneUPPER_ARM:          "UPPER_ARM",
	SkeletonBoneLOWER_ARM:          "LOWER_ARM",
	SkeletonBoneHAND_Y:             "HAND_Y",
	SkeletonBoneHAND_Z:             "HAND_Z",
	SkeletonBoneELBOW_OFFSET:       "ELBOW_OFFSET",
	SkeletonBoneUPPER_CHEST:        "UPPER_CHEST",
}

var EnumValuesSkeletonBone = map[string]SkeletonBone{
	"NONE":               SkeletonBoneNONE,
	"HEAD":               SkeletonBoneHEAD,
	"NECK":               SkeletonBoneNECK,
	"CHEST":              SkeletonBoneCHEST,
	"CHEST_OFFSET":       SkeletonBoneCHEST_OFFSET,
	"WAIST":              SkeletonBoneWAIST,
	"HIP":                SkeletonBoneHIP,
	"HIP_OFFSET":         SkeletonBoneHIP_OFFSET,
	"HIPS_WIDTH":         SkeletonBoneHIPS_WIDTH,
	"UPPER_LEG":          SkeletonBoneUPPER_LEG,
	"LOWER_LEG":          SkeletonBoneLOWER_LEG,
	"FOOT_LENGTH":        SkeletonBoneFOOT_LENGTH,
	"FOOT_SHIFT":         SkeletonBoneFOOT_SHIFT,
	"SKELETON_OFFSET":    SkeletonBoneSKELETON_OFFSET,
	"SHOULDERS_DISTANCE": SkeletonBoneSHOULDERS_DISTANCE,
	"SHOULDERS_WIDTH":    SkeletonBoneSHOULDERS_WIDTH,
	"UPPER_ARM":          SkeletonBoneUPPER_ARM,
	"LOWER_ARM":          SkeletonBoneLOWER_ARM,
	"HAND_Y":             SkeletonBoneHAND_Y,
	"HAND_Z":             SkeletonBoneHAND_Z,
	"ELBOW_OFFSET":       SkeletonBoneELBOW_OFFSET,
	"UPPER_CHEST":        SkeletonBoneUPPER_CHEST,
}

func (v SkeletonBone) String() string {
	if s, ok := EnumNamesSkeletonBone[v]; ok {
		return s
	}
	return "SkeletonBone(" + strconv.FormatInt(int64(v), 10) + ")"
}
