// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / When a new status appears, it's sent alone
type StatusSystemUpdate struct {
	_tab flatbuffers.Table
}

func GetRootAsStatusSystemUpdate(buf []byte, offset flatbuffers.UOffsetT) *StatusSystemUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StatusSystemUpdate{}
	x.Init(buf, n+offset)
	return x
}

func FinishStatusSystemUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStatusSystemUpdate(buf []byte, offset flatbuffers.UOffsetT) *StatusSystemUpdate {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StatusSystemUpdate{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStatusSystemUpdateBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StatusSystemUpdate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StatusSystemUpdate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StatusSystemUpdate) NewStatus(obj *StatusMessage) *StatusMessage {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(StatusMessage)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func StatusSystemUpdateStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StatusSystemUpdateAddNewStatus(builder *flatbuffers.Builder, newStatus flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(newStatus), 0)
}
func StatusSystemUpdateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
