// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
)

// / There is an available HMD tracker and it's not assigned to head
type StatusUnassignedHMD struct {
	_tab flatbuffers.Table
}

func GetRootAsStatusUnassignedHMD(buf []byte, offset flatbuffers.UOffsetT) *StatusUnassignedHMD {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StatusUnassignedHMD{}
	x.Init(buf, n+offset)
	return x
}

func FinishStatusUnassignedHMDBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStatusUnassignedHMD(buf []byte, offset flatbuffers.UOffsetT) *StatusUnassignedHMD {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StatusUnassignedHMD{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStatusUnassignedHMDBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StatusUnassignedHMD) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StatusUnassignedHMD) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StatusUnassignedHMD) TrackerId(obj *solarxr_protocol__datatypes.TrackerId) *solarxr_protocol__datatypes.TrackerId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(solarxr_protocol__datatypes.TrackerId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func StatusUnassignedHMDStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StatusUnassignedHMDAddTrackerId(builder *flatbuffers.Builder, trackerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(trackerId), 0)
}
func StatusUnassignedHMDEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
