// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
)

// / Trackers with error state
type StatusTrackerError struct {
	_tab flatbuffers.Table
}

func GetRootAsStatusTrackerError(buf []byte, offset flatbuffers.UOffsetT) *StatusTrackerError {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StatusTrackerError{}
	x.Init(buf, n+offset)
	return x
}

func FinishStatusTrackerErrorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStatusTrackerError(buf []byte, offset flatbuffers.UOffsetT) *StatusTrackerError {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StatusTrackerError{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStatusTrackerErrorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StatusTrackerError) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StatusTrackerError) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StatusTrackerError) TrackerId(obj *solarxr_protocol__datatypes.TrackerId, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *StatusTrackerError) TrackerIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func StatusTrackerErrorStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StatusTrackerErrorAddTrackerId(builder *flatbuffers.Builder, trackerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(trackerId), 0)
}
func StatusTrackerErrorStartTrackerIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StatusTrackerErrorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
