// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / When an status is fixed and it's removed, it's ID is sent
type StatusSystemFixed struct {
	_tab flatbuffers.Table
}

func GetRootAsStatusSystemFixed(buf []byte, offset flatbuffers.UOffsetT) *StatusSystemFixed {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StatusSystemFixed{}
	x.Init(buf, n+offset)
	return x
}

func FinishStatusSystemFixedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStatusSystemFixed(buf []byte, offset flatbuffers.UOffsetT) *StatusSystemFixed {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StatusSystemFixed{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStatusSystemFixedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StatusSystemFixed) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StatusSystemFixed) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StatusSystemFixed) FixedStatusId() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StatusSystemFixed) MutateFixedStatusId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func StatusSystemFixedStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StatusSystemFixedAddFixedStatusId(builder *flatbuffers.Builder, fixedStatusId uint32) {
	builder.PrependUint32Slot(0, fixedStatusId, 0)
}
func StatusSystemFixedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
