// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Request current statuses that we have
type StatusSystemRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsStatusSystemRequest(buf []byte, offset flatbuffers.UOffsetT) *StatusSystemRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StatusSystemRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishStatusSystemRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStatusSystemRequest(buf []byte, offset flatbuffers.UOffsetT) *StatusSystemRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StatusSystemRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStatusSystemRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StatusSystemRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StatusSystemRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func StatusSystemRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func StatusSystemRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
