// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
)

// / Tracker requires full reset
type StatusTrackerReset struct {
	_tab flatbuffers.Table
}

func GetRootAsStatusTrackerReset(buf []byte, offset flatbuffers.UOffsetT) *StatusTrackerReset {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StatusTrackerReset{}
	x.Init(buf, n+offset)
	return x
}

func FinishStatusTrackerResetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStatusTrackerReset(buf []byte, offset flatbuffers.UOffsetT) *StatusTrackerReset {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StatusTrackerReset{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStatusTrackerResetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StatusTrackerReset) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StatusTrackerReset) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StatusTrackerReset) TrackerId(obj *solarxr_protocol__datatypes.TrackerId, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *StatusTrackerReset) TrackerIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func StatusTrackerResetStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StatusTrackerResetAddTrackerId(builder *flatbuffers.Builder, trackerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(trackerId), 0)
}
func StatusTrackerResetStartTrackerIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StatusTrackerResetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
