// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Response containing all current valid statuses
type StatusSystemResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsStatusSystemResponse(buf []byte, offset flatbuffers.UOffsetT) *StatusSystemResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StatusSystemResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishStatusSystemResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStatusSystemResponse(buf []byte, offset flatbuffers.UOffsetT) *StatusSystemResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StatusSystemResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStatusSystemResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StatusSystemResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StatusSystemResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StatusSystemResponse) CurrentStatuses(obj *StatusMessage, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *StatusSystemResponse) CurrentStatusesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func StatusSystemResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StatusSystemResponseAddCurrentStatuses(builder *flatbuffers.Builder, currentStatuses flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(currentStatuses), 0)
}
func StatusSystemResponseStartCurrentStatusesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StatusSystemResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
