// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / An status is some kind of warning sent by the server, it's mainly made for
// / showing problems with the server and need attention from the user.
type StatusMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsStatusMessage(buf []byte, offset flatbuffers.UOffsetT) *StatusMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StatusMessage{}
	x.Init(buf, n+offset)
	return x
}

func FinishStatusMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStatusMessage(buf []byte, offset flatbuffers.UOffsetT) *StatusMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StatusMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStatusMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StatusMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StatusMessage) Table() flatbuffers.Table {
	return rcv._tab
}

// / The status ID
func (rcv *StatusMessage) Id() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

// / The status ID
func (rcv *StatusMessage) MutateId(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

// / This should be prioritized in the GUI in some way if true
func (rcv *StatusMessage) Prioritized() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

// / This should be prioritized in the GUI in some way if true
func (rcv *StatusMessage) MutatePrioritized(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *StatusMessage) DataType() StatusData {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return StatusData(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *StatusMessage) MutateDataType(n StatusData) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *StatusMessage) Data(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func StatusMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func StatusMessageAddId(builder *flatbuffers.Builder, id uint32) {
	builder.PrependUint32Slot(0, id, 0)
}
func StatusMessageAddPrioritized(builder *flatbuffers.Builder, prioritized bool) {
	builder.PrependBoolSlot(1, prioritized, false)
}
func StatusMessageAddDataType(builder *flatbuffers.Builder, dataType StatusData) {
	builder.PrependByteSlot(2, byte(dataType), 0)
}
func StatusMessageAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(data), 0)
}
func StatusMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
