// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StayAlignedSettings struct {
	_tab flatbuffers.Table
}

func GetRootAsStayAlignedSettings(buf []byte, offset flatbuffers.UOffsetT) *StayAlignedSettings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StayAlignedSettings{}
	x.Init(buf, n+offset)
	return x
}

func FinishStayAlignedSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStayAlignedSettings(buf []byte, offset flatbuffers.UOffsetT) *StayAlignedSettings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StayAlignedSettings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStayAlignedSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StayAlignedSettings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StayAlignedSettings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StayAlignedSettings) Enabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StayAlignedSettings) MutateEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *StayAlignedSettings) ExtraYawCorrection() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StayAlignedSettings) MutateExtraYawCorrection(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *StayAlignedSettings) HideYawCorrection() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StayAlignedSettings) MutateHideYawCorrection(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *StayAlignedSettings) StandingEnabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StayAlignedSettings) MutateStandingEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *StayAlignedSettings) StandingUpperLegAngle() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StayAlignedSettings) MutateStandingUpperLegAngle(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *StayAlignedSettings) StandingLowerLegAngle() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StayAlignedSettings) MutateStandingLowerLegAngle(n float32) bool {
	return rcv._tab.MutateFloat32Slot(14, n)
}

func (rcv *StayAlignedSettings) StandingFootAngle() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StayAlignedSettings) MutateStandingFootAngle(n float32) bool {
	return rcv._tab.MutateFloat32Slot(16, n)
}

func (rcv *StayAlignedSettings) SittingEnabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StayAlignedSettings) MutateSittingEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(18, n)
}

func (rcv *StayAlignedSettings) SittingUpperLegAngle() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StayAlignedSettings) MutateSittingUpperLegAngle(n float32) bool {
	return rcv._tab.MutateFloat32Slot(20, n)
}

func (rcv *StayAlignedSettings) SittingLowerLegAngle() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StayAlignedSettings) MutateSittingLowerLegAngle(n float32) bool {
	return rcv._tab.MutateFloat32Slot(22, n)
}

func (rcv *StayAlignedSettings) SittingFootAngle() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StayAlignedSettings) MutateSittingFootAngle(n float32) bool {
	return rcv._tab.MutateFloat32Slot(24, n)
}

func (rcv *StayAlignedSettings) FlatEnabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StayAlignedSettings) MutateFlatEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(26, n)
}

func (rcv *StayAlignedSettings) FlatUpperLegAngle() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StayAlignedSettings) MutateFlatUpperLegAngle(n float32) bool {
	return rcv._tab.MutateFloat32Slot(28, n)
}

func (rcv *StayAlignedSettings) FlatLowerLegAngle() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StayAlignedSettings) MutateFlatLowerLegAngle(n float32) bool {
	return rcv._tab.MutateFloat32Slot(30, n)
}

func (rcv *StayAlignedSettings) FlatFootAngle() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *StayAlignedSettings) MutateFlatFootAngle(n float32) bool {
	return rcv._tab.MutateFloat32Slot(32, n)
}

func (rcv *StayAlignedSettings) SetupComplete() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *StayAlignedSettings) MutateSetupComplete(n bool) bool {
	return rcv._tab.MutateBoolSlot(34, n)
}

func StayAlignedSettingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(16)
}
func StayAlignedSettingsAddEnabled(builder *flatbuffers.Builder, enabled bool) {
	builder.PrependBoolSlot(0, enabled, false)
}
func StayAlignedSettingsAddExtraYawCorrection(builder *flatbuffers.Builder, extraYawCorrection bool) {
	builder.PrependBoolSlot(1, extraYawCorrection, false)
}
func StayAlignedSettingsAddHideYawCorrection(builder *flatbuffers.Builder, hideYawCorrection bool) {
	builder.PrependBoolSlot(2, hideYawCorrection, false)
}
func StayAlignedSettingsAddStandingEnabled(builder *flatbuffers.Builder, standingEnabled bool) {
	builder.PrependBoolSlot(3, standingEnabled, false)
}
func StayAlignedSettingsAddStandingUpperLegAngle(builder *flatbuffers.Builder, standingUpperLegAngle float32) {
	builder.PrependFloat32Slot(4, standingUpperLegAngle, 0.0)
}
func StayAlignedSettingsAddStandingLowerLegAngle(builder *flatbuffers.Builder, standingLowerLegAngle float32) {
	builder.PrependFloat32Slot(5, standingLowerLegAngle, 0.0)
}
func StayAlignedSettingsAddStandingFootAngle(builder *flatbuffers.Builder, standingFootAngle float32) {
	builder.PrependFloat32Slot(6, standingFootAngle, 0.0)
}
func StayAlignedSettingsAddSittingEnabled(builder *flatbuffers.Builder, sittingEnabled bool) {
	builder.PrependBoolSlot(7, sittingEnabled, false)
}
func StayAlignedSettingsAddSittingUpperLegAngle(builder *flatbuffers.Builder, sittingUpperLegAngle float32) {
	builder.PrependFloat32Slot(8, sittingUpperLegAngle, 0.0)
}
func StayAlignedSettingsAddSittingLowerLegAngle(builder *flatbuffers.Builder, sittingLowerLegAngle float32) {
	builder.PrependFloat32Slot(9, sittingLowerLegAngle, 0.0)
}
func StayAlignedSettingsAddSittingFootAngle(builder *flatbuffers.Builder, sittingFootAngle float32) {
	builder.PrependFloat32Slot(10, sittingFootAngle, 0.0)
}
func StayAlignedSettingsAddFlatEnabled(builder *flatbuffers.Builder, flatEnabled bool) {
	builder.PrependBoolSlot(11, flatEnabled, false)
}
func StayAlignedSettingsAddFlatUpperLegAngle(builder *flatbuffers.Builder, flatUpperLegAngle float32) {
	builder.PrependFloat32Slot(12, flatUpperLegAngle, 0.0)
}
func StayAlignedSettingsAddFlatLowerLegAngle(builder *flatbuffers.Builder, flatLowerLegAngle float32) {
	builder.PrependFloat32Slot(13, flatLowerLegAngle, 0.0)
}
func StayAlignedSettingsAddFlatFootAngle(builder *flatbuffers.Builder, flatFootAngle float32) {
	builder.PrependFloat32Slot(14, flatFootAngle, 0.0)
}
func StayAlignedSettingsAddSetupComplete(builder *flatbuffers.Builder, setupComplete bool) {
	builder.PrependBoolSlot(15, setupComplete, false)
}
func StayAlignedSettingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
