// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SteamVRTrackersSetting struct {
	_tab flatbuffers.Table
}

func GetRootAsSteamVRTrackersSetting(buf []byte, offset flatbuffers.UOffsetT) *SteamVRTrackersSetting {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SteamVRTrackersSetting{}
	x.Init(buf, n+offset)
	return x
}

func FinishSteamVRTrackersSettingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSteamVRTrackersSetting(buf []byte, offset flatbuffers.UOffsetT) *SteamVRTrackersSetting {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SteamVRTrackersSetting{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSteamVRTrackersSettingBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SteamVRTrackersSetting) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SteamVRTrackersSetting) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SteamVRTrackersSetting) Waist() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SteamVRTrackersSetting) MutateWaist(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *SteamVRTrackersSetting) Chest() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SteamVRTrackersSetting) MutateChest(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *SteamVRTrackersSetting) AutomaticTrackerToggle() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SteamVRTrackersSetting) MutateAutomaticTrackerToggle(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func (rcv *SteamVRTrackersSetting) LeftFoot() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SteamVRTrackersSetting) MutateLeftFoot(n bool) bool {
	return rcv._tab.MutateBoolSlot(18, n)
}

func (rcv *SteamVRTrackersSetting) RightFoot() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SteamVRTrackersSetting) MutateRightFoot(n bool) bool {
	return rcv._tab.MutateBoolSlot(20, n)
}

func (rcv *SteamVRTrackersSetting) LeftKnee() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SteamVRTrackersSetting) MutateLeftKnee(n bool) bool {
	return rcv._tab.MutateBoolSlot(22, n)
}

func (rcv *SteamVRTrackersSetting) RightKnee() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SteamVRTrackersSetting) MutateRightKnee(n bool) bool {
	return rcv._tab.MutateBoolSlot(24, n)
}

func (rcv *SteamVRTrackersSetting) LeftElbow() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SteamVRTrackersSetting) MutateLeftElbow(n bool) bool {
	return rcv._tab.MutateBoolSlot(26, n)
}

func (rcv *SteamVRTrackersSetting) RightElbow() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SteamVRTrackersSetting) MutateRightElbow(n bool) bool {
	return rcv._tab.MutateBoolSlot(28, n)
}

func (rcv *SteamVRTrackersSetting) LeftHand() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SteamVRTrackersSetting) MutateLeftHand(n bool) bool {
	return rcv._tab.MutateBoolSlot(30, n)
}

func (rcv *SteamVRTrackersSetting) RightHand() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SteamVRTrackersSetting) MutateRightHand(n bool) bool {
	return rcv._tab.MutateBoolSlot(32, n)
}

func SteamVRTrackersSettingStart(builder *flatbuffers.Builder) {
	builder.StartObject(15)
}
func SteamVRTrackersSettingAddWaist(builder *flatbuffers.Builder, waist bool) {
	builder.PrependBoolSlot(0, waist, false)
}
func SteamVRTrackersSettingAddChest(builder *flatbuffers.Builder, chest bool) {
	builder.PrependBoolSlot(1, chest, false)
}
func SteamVRTrackersSettingAddAutomaticTrackerToggle(builder *flatbuffers.Builder, automaticTrackerToggle bool) {
	builder.PrependBoolSlot(6, automaticTrackerToggle, false)
}
func SteamVRTrackersSettingAddLeftFoot(builder *flatbuffers.Builder, leftFoot bool) {
	builder.PrependBoolSlot(7, leftFoot, false)
}
func SteamVRTrackersSettingAddRightFoot(builder *flatbuffers.Builder, rightFoot bool) {
	builder.PrependBoolSlot(8, rightFoot, false)
}
func SteamVRTrackersSettingAddLeftKnee(builder *flatbuffers.Builder, leftKnee bool) {
	builder.PrependBoolSlot(9, leftKnee, false)
}
func SteamVRTrackersSettingAddRightKnee(builder *flatbuffers.Builder, rightKnee bool) {
	builder.PrependBoolSlot(10, rightKnee, false)
}
func SteamVRTrackersSettingAddLeftElbow(builder *flatbuffers.Builder, leftElbow bool) {
	builder.PrependBoolSlot(11, leftElbow, false)
}
func SteamVRTrackersSettingAddRightElbow(builder *flatbuffers.Builder, rightElbow bool) {
	builder.PrependBoolSlot(12, rightElbow, false)
}
func SteamVRTrackersSettingAddLeftHand(builder *flatbuffers.Builder, leftHand bool) {
	builder.PrependBoolSlot(13, leftHand, false)
}
func SteamVRTrackersSettingAddRightHand(builder *flatbuffers.Builder, rightHand bool) {
	builder.PrependBoolSlot(14, rightHand, false)
}
func SteamVRTrackersSettingEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
