// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StopWifiProvisioningRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsStopWifiProvisioningRequest(buf []byte, offset flatbuffers.UOffsetT) *StopWifiProvisioningRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StopWifiProvisioningRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishStopWifiProvisioningRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStopWifiProvisioningRequest(buf []byte, offset flatbuffers.UOffsetT) *StopWifiProvisioningRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StopWifiProvisioningRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStopWifiProvisioningRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StopWifiProvisioningRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StopWifiProvisioningRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func StopWifiProvisioningRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func StopWifiProvisioningRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
