// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
)

// / See TapDetectionSettings::setup_mode
type TapDetectionSetupNotification struct {
	_tab flatbuffers.Table
}

func GetRootAsTapDetectionSetupNotification(buf []byte, offset flatbuffers.UOffsetT) *TapDetectionSetupNotification {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TapDetectionSetupNotification{}
	x.Init(buf, n+offset)
	return x
}

func FinishTapDetectionSetupNotificationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTapDetectionSetupNotification(buf []byte, offset flatbuffers.UOffsetT) *TapDetectionSetupNotification {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TapDetectionSetupNotification{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTapDetectionSetupNotificationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TapDetectionSetupNotification) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TapDetectionSetupNotification) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TapDetectionSetupNotification) TrackerId(obj *solarxr_protocol__datatypes.TrackerId) *solarxr_protocol__datatypes.TrackerId {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(solarxr_protocol__datatypes.TrackerId)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TapDetectionSetupNotificationStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TapDetectionSetupNotificationAddTrackerId(builder *flatbuffers.Builder, trackerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(trackerId), 0)
}
func TapDetectionSetupNotificationEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
