// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TimeoutSettings struct {
	_tab flatbuffers.Table
}

func GetRootAsTimeoutSettings(buf []byte, offset flatbuffers.UOffsetT) *TimeoutSettings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TimeoutSettings{}
	x.Init(buf, n+offset)
	return x
}

func FinishTimeoutSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTimeoutSettings(buf []byte, offset flatbuffers.UOffsetT) *TimeoutSettings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TimeoutSettings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTimeoutSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TimeoutSettings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TimeoutSettings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TimeoutSettings) Duration() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *TimeoutSettings) MutateDuration(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func TimeoutSettingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TimeoutSettingsAddDuration(builder *flatbuffers.Builder, duration float32) {
	builder.PrependFloat32Slot(0, duration, 0.0)
}
func TimeoutSettingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
