// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import "strconv"

type TrackingChecklistStepId byte

const (
	TrackingChecklistStepIdUNKNOWN                   TrackingChecklistStepId = 0
	TrackingChecklistStepIdTRACKERS_REST_CALIBRATION TrackingChecklistStepId = 1
	TrackingChecklistStepIdFULL_RESET                TrackingChecklistStepId = 2
	TrackingChecklistStepIdVRCHAT_SETTINGS           TrackingChecklistStepId = 3
	TrackingChecklistStepIdSTEAMVR_DISCONNECTED      TrackingChecklistStepId = 4
	TrackingChecklistStepIdUNASSIGNED_HMD            TrackingChecklistStepId = 5
	TrackingChecklistStepIdTRACKER_ERROR             TrackingChecklistStepId = 6
	TrackingChecklistStepIdNETWORK_PROFILE_PUBLIC    TrackingChecklistStepId = 7
	TrackingChecklistStepIdMOUNTING_CALIBRATION      TrackingChecklistStepId = 8
	TrackingChecklistStepIdFEET_MOUNTING_CALIBRATION TrackingChecklistStepId = 9
	TrackingChecklistStepIdSTAY_ALIGNED_CONFIGURED   TrackingChecklistStepId = 10
	TrackingChecklistStepIdSTEAMVR_HANDS_ENABLED     TrackingChecklistStepId = 11
	TrackingChecklistStepIdSTANDABLE_INSTALLED       TrackingChecklistStepId = 12
)

var EnumNamesTrackingChecklistStepId = map[TrackingChecklistStepId]string{
	TrackingChecklistStepIdUNKNOWN:                   "UNKNOWN",
	TrackingChecklistStepIdTRACKERS_REST_CALIBRATION: "TRACKERS_REST_CALIBRATION",
	TrackingChecklistStepIdFULL_RESET:                "FULL_RESET",
	TrackingChecklistStepIdVRCHAT_SETTINGS:           "VRCHAT_SETTINGS",
	TrackingChecklistStepIdSTEAMVR_DISCONNECTED:      "STEAMVR_DISCONNECTED",
	TrackingChecklistStepIdUNASSIGNED_HMD:            "UNASSIGNED_HMD",
	TrackingChecklistStepIdTRACKER_ERROR:             "TRACKER_ERROR",
	TrackingChecklistStepIdNETWORK_PROFILE_PUBLIC:    "NETWORK_PROFILE_PUBLIC",
	TrackingChecklistStepIdMOUNTING_CALIBRATION:      "MOUNTING_CALIBRATION",
	TrackingChecklistStepIdFEET_MOUNTING_CALIBRATION: "FEET_MOUNTING_CALIBRATION",
	TrackingChecklistStepIdSTAY_ALIGNED_CONFIGURED:   "STAY_ALIGNED_CONFIGURED",
	TrackingChecklistStepIdSTEAMVR_HANDS_ENABLED:     "STEAMVR_HANDS_ENABLED",
	TrackingChecklistStepIdSTANDABLE_INSTALLED:       "STANDABLE_INSTALLED",
}

var EnumValuesTrackingChecklistStepId = map[string]TrackingChecklistStepId{
	"UNKNOWN":                   TrackingChecklistStepIdUNKNOWN,
	"TRACKERS_REST_CALIBRATION": TrackingChecklistStepIdTRACKERS_REST_CALIBRATION,
	"FULL_RESET":                TrackingChecklistStepIdFULL_RESET,
	"VRCHAT_SETTINGS":           TrackingChecklistStepIdVRCHAT_SETTINGS,
	"STEAMVR_DISCONNECTED":      TrackingChecklistStepIdSTEAMVR_DISCONNECTED,
	"UNASSIGNED_HMD":            TrackingChecklistStepIdUNASSIGNED_HMD,
	"TRACKER_ERROR":             TrackingChecklistStepIdTRACKER_ERROR,
	"NETWORK_PROFILE_PUBLIC":    TrackingChecklistStepIdNETWORK_PROFILE_PUBLIC,
	"MOUNTING_CALIBRATION":      TrackingChecklistStepIdMOUNTING_CALIBRATION,
	"FEET_MOUNTING_CALIBRATION": TrackingChecklistStepIdFEET_MOUNTING_CALIBRATION,
	"STAY_ALIGNED_CONFIGURED":   TrackingChecklistStepIdSTAY_ALIGNED_CONFIGURED,
	"STEAMVR_HANDS_ENABLED":     TrackingChecklistStepIdSTEAMVR_HANDS_ENABLED,
	"STANDABLE_INSTALLED":       TrackingChecklistStepIdSTANDABLE_INSTALLED,
}

func (v TrackingChecklistStepId) String() string {
	if s, ok := EnumNamesTrackingChecklistStepId[v]; ok {
		return s
	}
	return "TrackingChecklistStepId(" + strconv.FormatInt(int64(v), 10) + ")"
}
