// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TrackingChecklistPublicNetworks struct {
	_tab flatbuffers.Table
}

func GetRootAsTrackingChecklistPublicNetworks(buf []byte, offset flatbuffers.UOffsetT) *TrackingChecklistPublicNetworks {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TrackingChecklistPublicNetworks{}
	x.Init(buf, n+offset)
	return x
}

func FinishTrackingChecklistPublicNetworksBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTrackingChecklistPublicNetworks(buf []byte, offset flatbuffers.UOffsetT) *TrackingChecklistPublicNetworks {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TrackingChecklistPublicNetworks{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTrackingChecklistPublicNetworksBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TrackingChecklistPublicNetworks) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TrackingChecklistPublicNetworks) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TrackingChecklistPublicNetworks) Adapters(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *TrackingChecklistPublicNetworks) AdaptersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TrackingChecklistPublicNetworksStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TrackingChecklistPublicNetworksAddAdapters(builder *flatbuffers.Builder, adapters flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(adapters), 0)
}
func TrackingChecklistPublicNetworksStartAdaptersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TrackingChecklistPublicNetworksEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
