// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TrackingPauseStateResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsTrackingPauseStateResponse(buf []byte, offset flatbuffers.UOffsetT) *TrackingPauseStateResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TrackingPauseStateResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishTrackingPauseStateResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTrackingPauseStateResponse(buf []byte, offset flatbuffers.UOffsetT) *TrackingPauseStateResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TrackingPauseStateResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTrackingPauseStateResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TrackingPauseStateResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TrackingPauseStateResponse) Table() flatbuffers.Table {
	return rcv._tab
}

// / Skeleton tracking is paused if true, skeleton tracking is unpaused if false.
func (rcv *TrackingPauseStateResponse) TrackingPaused() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

// / Skeleton tracking is paused if true, skeleton tracking is unpaused if false.
func (rcv *TrackingPauseStateResponse) MutateTrackingPaused(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func TrackingPauseStateResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TrackingPauseStateResponseAddTrackingPaused(builder *flatbuffers.Builder, trackingPaused bool) {
	builder.PrependBoolSlot(0, trackingPaused, false)
}
func TrackingPauseStateResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
