// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TrackingChecklistRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTrackingChecklistRequest(buf []byte, offset flatbuffers.UOffsetT) *TrackingChecklistRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TrackingChecklistRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishTrackingChecklistRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTrackingChecklistRequest(buf []byte, offset flatbuffers.UOffsetT) *TrackingChecklistRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TrackingChecklistRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTrackingChecklistRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TrackingChecklistRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TrackingChecklistRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func TrackingChecklistRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func TrackingChecklistRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
