// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import "strconv"

type TrackingChecklistExtraData byte

const (
	TrackingChecklistExtraDataNONE                                 TrackingChecklistExtraData = 0
	TrackingChecklistExtraDataTrackingChecklistTrackerReset        TrackingChecklistExtraData = 1
	TrackingChecklistExtraDataTrackingChecklistTrackerError        TrackingChecklistExtraData = 2
	TrackingChecklistExtraDataTrackingChecklistSteamVRDisconnected TrackingChecklistExtraData = 3
	TrackingChecklistExtraDataTrackingChecklistUnassignedHMD       TrackingChecklistExtraData = 4
	TrackingChecklistExtraDataTrackingChecklistNeedCalibration     TrackingChecklistExtraData = 5
	TrackingChecklistExtraDataTrackingChecklistPublicNetworks      TrackingChecklistExtraData = 6
)

var EnumNamesTrackingChecklistExtraData = map[TrackingChecklistExtraData]string{
	TrackingChecklistExtraDataNONE:                                 "NONE",
	TrackingChecklistExtraDataTrackingChecklistTrackerReset:        "TrackingChecklistTrackerReset",
	TrackingChecklistExtraDataTrackingChecklistTrackerError:        "TrackingChecklistTrackerError",
	TrackingChecklistExtraDataTrackingChecklistSteamVRDisconnected: "TrackingChecklistSteamVRDisconnected",
	TrackingChecklistExtraDataTrackingChecklistUnassignedHMD:       "TrackingChecklistUnassignedHMD",
	TrackingChecklistExtraDataTrackingChecklistNeedCalibration:     "TrackingChecklistNeedCalibration",
	TrackingChecklistExtraDataTrackingChecklistPublicNetworks:      "TrackingChecklistPublicNetworks",
}

var EnumValuesTrackingChecklistExtraData = map[string]TrackingChecklistExtraData{
	"NONE":                                 TrackingChecklistExtraDataNONE,
	"TrackingChecklistTrackerReset":        TrackingChecklistExtraDataTrackingChecklistTrackerReset,
	"TrackingChecklistTrackerError":        TrackingChecklistExtraDataTrackingChecklistTrackerError,
	"TrackingChecklistSteamVRDisconnected": TrackingChecklistExtraDataTrackingChecklistSteamVRDisconnected,
	"TrackingChecklistUnassignedHMD":       TrackingChecklistExtraDataTrackingChecklistUnassignedHMD,
	"TrackingChecklistNeedCalibration":     TrackingChecklistExtraDataTrackingChecklistNeedCalibration,
	"TrackingChecklistPublicNetworks":      TrackingChecklistExtraDataTrackingChecklistPublicNetworks,
}

func (v TrackingChecklistExtraData) String() string {
	if s, ok := EnumNamesTrackingChecklistExtraData[v]; ok {
		return s
	}
	return "TrackingChecklistExtraData(" + strconv.FormatInt(int64(v), 10) + ")"
}
