// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TrackingChecklistSteamVRDisconnected struct {
	_tab flatbuffers.Table
}

func GetRootAsTrackingChecklistSteamVRDisconnected(buf []byte, offset flatbuffers.UOffsetT) *TrackingChecklistSteamVRDisconnected {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TrackingChecklistSteamVRDisconnected{}
	x.Init(buf, n+offset)
	return x
}

func FinishTrackingChecklistSteamVRDisconnectedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTrackingChecklistSteamVRDisconnected(buf []byte, offset flatbuffers.UOffsetT) *TrackingChecklistSteamVRDisconnected {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TrackingChecklistSteamVRDisconnected{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTrackingChecklistSteamVRDisconnectedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TrackingChecklistSteamVRDisconnected) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TrackingChecklistSteamVRDisconnected) Table() flatbuffers.Table {
	return rcv._tab
}

// / Name of bridge in the server's config
func (rcv *TrackingChecklistSteamVRDisconnected) BridgeSettingsName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

// / Name of bridge in the server's config
// / Is the driver installed?
func (rcv *TrackingChecklistSteamVRDisconnected) DriverInstalled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

// / Is the driver installed?
func (rcv *TrackingChecklistSteamVRDisconnected) MutateDriverInstalled(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

// / Has the driver been blocked due to SteamVR's "safe mode"?
func (rcv *TrackingChecklistSteamVRDisconnected) DriverBlockedBySafeMode() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

// / Has the driver been blocked due to SteamVR's "safe mode"?
func (rcv *TrackingChecklistSteamVRDisconnected) MutateDriverBlockedBySafeMode(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

// / Is the driver enabled in SteamVR settings?
func (rcv *TrackingChecklistSteamVRDisconnected) DriverEnabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

// / Is the driver enabled in SteamVR settings?
func (rcv *TrackingChecklistSteamVRDisconnected) MutateDriverEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func TrackingChecklistSteamVRDisconnectedStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func TrackingChecklistSteamVRDisconnectedAddBridgeSettingsName(builder *flatbuffers.Builder, bridgeSettingsName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bridgeSettingsName), 0)
}
func TrackingChecklistSteamVRDisconnectedAddDriverInstalled(builder *flatbuffers.Builder, driverInstalled bool) {
	builder.PrependBoolSlot(1, driverInstalled, false)
}
func TrackingChecklistSteamVRDisconnectedAddDriverBlockedBySafeMode(builder *flatbuffers.Builder, driverBlockedBySafeMode bool) {
	builder.PrependBoolSlot(2, driverBlockedBySafeMode, false)
}
func TrackingChecklistSteamVRDisconnectedAddDriverEnabled(builder *flatbuffers.Builder, driverEnabled bool) {
	builder.PrependBoolSlot(3, driverEnabled, false)
}
func TrackingChecklistSteamVRDisconnectedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
