// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Requests the current state of tracking pause
type TrackingPauseStateRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTrackingPauseStateRequest(buf []byte, offset flatbuffers.UOffsetT) *TrackingPauseStateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TrackingPauseStateRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishTrackingPauseStateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTrackingPauseStateRequest(buf []byte, offset flatbuffers.UOffsetT) *TrackingPauseStateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TrackingPauseStateRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTrackingPauseStateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TrackingPauseStateRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TrackingPauseStateRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func TrackingPauseStateRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func TrackingPauseStateRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
