// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"

	solarxr_protocol__datatypes "github.com/camesura/camesura/bridge/internal/solarxr/solarxr_protocol/datatypes"
)

// / Trackers that need a reset
type TrackingChecklistTrackerReset struct {
	_tab flatbuffers.Table
}

func GetRootAsTrackingChecklistTrackerReset(buf []byte, offset flatbuffers.UOffsetT) *TrackingChecklistTrackerReset {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TrackingChecklistTrackerReset{}
	x.Init(buf, n+offset)
	return x
}

func FinishTrackingChecklistTrackerResetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTrackingChecklistTrackerReset(buf []byte, offset flatbuffers.UOffsetT) *TrackingChecklistTrackerReset {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TrackingChecklistTrackerReset{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTrackingChecklistTrackerResetBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TrackingChecklistTrackerReset) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TrackingChecklistTrackerReset) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TrackingChecklistTrackerReset) TrackersId(obj *solarxr_protocol__datatypes.TrackerId, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TrackingChecklistTrackerReset) TrackersIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TrackingChecklistTrackerResetStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TrackingChecklistTrackerResetAddTrackersId(builder *flatbuffers.Builder, trackersId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(trackersId), 0)
}
func TrackingChecklistTrackerResetStartTrackersIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TrackingChecklistTrackerResetEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
