// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / Server notifies connection of an unknown device.
// / If the notification is no longer sent, it means the device connected to another
// / server, got connected to this server or it was turned off.
type UnknownDeviceHandshakeNotification struct {
	_tab flatbuffers.Table
}

func GetRootAsUnknownDeviceHandshakeNotification(buf []byte, offset flatbuffers.UOffsetT) *UnknownDeviceHandshakeNotification {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UnknownDeviceHandshakeNotification{}
	x.Init(buf, n+offset)
	return x
}

func FinishUnknownDeviceHandshakeNotificationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUnknownDeviceHandshakeNotification(buf []byte, offset flatbuffers.UOffsetT) *UnknownDeviceHandshakeNotification {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UnknownDeviceHandshakeNotification{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUnknownDeviceHandshakeNotificationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UnknownDeviceHandshakeNotification) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UnknownDeviceHandshakeNotification) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UnknownDeviceHandshakeNotification) MacAddress() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func UnknownDeviceHandshakeNotificationStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UnknownDeviceHandshakeNotificationAddMacAddress(builder *flatbuffers.Builder, macAddress flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(macAddress), 0)
}
func UnknownDeviceHandshakeNotificationEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
