// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import "strconv"

type UserHeightCalibrationStatus byte

const (
	UserHeightCalibrationStatusNONE                         UserHeightCalibrationStatus = 0
	UserHeightCalibrationStatusRECORDING_FLOOR              UserHeightCalibrationStatus = 1
	UserHeightCalibrationStatusWAITING_FOR_CONTROLLER_PITCH UserHeightCalibrationStatus = 2
	UserHeightCalibrationStatusWAITING_FOR_RISE             UserHeightCalibrationStatus = 3
	UserHeightCalibrationStatusWAITING_FOR_FW_LOOK          UserHeightCalibrationStatus = 4
	UserHeightCalibrationStatusRECORDING_HEIGHT             UserHeightCalibrationStatus = 5
	UserHeightCalibrationStatusDONE                         UserHeightCalibrationStatus = 6
	UserHeightCalibrationStatusERROR_TOO_HIGH               UserHeightCalibrationStatus = 7
	UserHeightCalibrationStatusERROR_TOO_SMALL              UserHeightCalibrationStatus = 8
	UserHeightCalibrationStatusERROR_TIMEOUT                UserHeightCalibrationStatus = 9
)

var EnumNamesUserHeightCalibrationStatus = map[UserHeightCalibrationStatus]string{
	UserHeightCalibrationStatusNONE:                         "NONE",
	UserHeightCalibrationStatusRECORDING_FLOOR:              "RECORDING_FLOOR",
	UserHeightCalibrationStatusWAITING_FOR_CONTROLLER_PITCH: "WAITING_FOR_CONTROLLER_PITCH",
	UserHeightCalibrationStatusWAITING_FOR_RISE:             "WAITING_FOR_RISE",
	UserHeightCalibrationStatusWAITING_FOR_FW_LOOK:          "WAITING_FOR_FW_LOOK",
	UserHeightCalibrationStatusRECORDING_HEIGHT:             "RECORDING_HEIGHT",
	UserHeightCalibrationStatusDONE:                         "DONE",
	UserHeightCalibrationStatusERROR_TOO_HIGH:               "ERROR_TOO_HIGH",
	UserHeightCalibrationStatusERROR_TOO_SMALL:              "ERROR_TOO_SMALL",
	UserHeightCalibrationStatusERROR_TIMEOUT:                "ERROR_TIMEOUT",
}

var EnumValuesUserHeightCalibrationStatus = map[string]UserHeightCalibrationStatus{
	"NONE":                         UserHeightCalibrationStatusNONE,
	"RECORDING_FLOOR":              UserHeightCalibrationStatusRECORDING_FLOOR,
	"WAITING_FOR_CONTROLLER_PITCH": UserHeightCalibrationStatusWAITING_FOR_CONTROLLER_PITCH,
	"WAITING_FOR_RISE":             UserHeightCalibrationStatusWAITING_FOR_RISE,
	"WAITING_FOR_FW_LOOK":          UserHeightCalibrationStatusWAITING_FOR_FW_LOOK,
	"RECORDING_HEIGHT":             UserHeightCalibrationStatusRECORDING_HEIGHT,
	"DONE":                         UserHeightCalibrationStatusDONE,
	"ERROR_TOO_HIGH":               UserHeightCalibrationStatusERROR_TOO_HIGH,
	"ERROR_TOO_SMALL":              UserHeightCalibrationStatusERROR_TOO_SMALL,
	"ERROR_TIMEOUT":                UserHeightCalibrationStatusERROR_TIMEOUT,
}

func (v UserHeightCalibrationStatus) String() string {
	if s, ok := EnumNamesUserHeightCalibrationStatus[v]; ok {
		return s
	}
	return "UserHeightCalibrationStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
