// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserHeightRecordingStatusResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsUserHeightRecordingStatusResponse(buf []byte, offset flatbuffers.UOffsetT) *UserHeightRecordingStatusResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserHeightRecordingStatusResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishUserHeightRecordingStatusResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUserHeightRecordingStatusResponse(buf []byte, offset flatbuffers.UOffsetT) *UserHeightRecordingStatusResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserHeightRecordingStatusResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUserHeightRecordingStatusResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UserHeightRecordingStatusResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserHeightRecordingStatusResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UserHeightRecordingStatusResponse) HmdHeight() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *UserHeightRecordingStatusResponse) MutateHmdHeight(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *UserHeightRecordingStatusResponse) Status() UserHeightCalibrationStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return UserHeightCalibrationStatus(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *UserHeightRecordingStatusResponse) MutateStatus(n UserHeightCalibrationStatus) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func UserHeightRecordingStatusResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func UserHeightRecordingStatusResponseAddHmdHeight(builder *flatbuffers.Builder, hmdHeight float32) {
	builder.PrependFloat32Slot(0, hmdHeight, 0.0)
}
func UserHeightRecordingStatusResponseAddStatus(builder *flatbuffers.Builder, status UserHeightCalibrationStatus) {
	builder.PrependByteSlot(1, byte(status), 0)
}
func UserHeightRecordingStatusResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
