// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VelocitySettings struct {
	_tab flatbuffers.Table
}

func GetRootAsVelocitySettings(buf []byte, offset flatbuffers.UOffsetT) *VelocitySettings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VelocitySettings{}
	x.Init(buf, n+offset)
	return x
}

func FinishVelocitySettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVelocitySettings(buf []byte, offset flatbuffers.UOffsetT) *VelocitySettings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VelocitySettings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVelocitySettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VelocitySettings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VelocitySettings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VelocitySettings) SendDerivedVelocity() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VelocitySettings) MutateSendDerivedVelocity(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func VelocitySettingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func VelocitySettingsAddSendDerivedVelocity(builder *flatbuffers.Builder, sendDerivedVelocity bool) {
	builder.PrependBoolSlot(0, sendDerivedVelocity, false)
}
func VelocitySettingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
