// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / OSC Settings specific to VMC
type VMCOSCSettings struct {
	_tab flatbuffers.Table
}

func GetRootAsVMCOSCSettings(buf []byte, offset flatbuffers.UOffsetT) *VMCOSCSettings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VMCOSCSettings{}
	x.Init(buf, n+offset)
	return x
}

func FinishVMCOSCSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVMCOSCSettings(buf []byte, offset flatbuffers.UOffsetT) *VMCOSCSettings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VMCOSCSettings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVMCOSCSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VMCOSCSettings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VMCOSCSettings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VMCOSCSettings) OscSettings(obj *OSCSettings) *OSCSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(OSCSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *VMCOSCSettings) AnchorHip() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VMCOSCSettings) MutateAnchorHip(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *VMCOSCSettings) MirrorTracking() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VMCOSCSettings) MutateMirrorTracking(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func VMCOSCSettingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func VMCOSCSettingsAddOscSettings(builder *flatbuffers.Builder, oscSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(oscSettings), 0)
}
func VMCOSCSettingsAddAnchorHip(builder *flatbuffers.Builder, anchorHip bool) {
	builder.PrependBoolSlot(2, anchorHip, false)
}
func VMCOSCSettingsAddMirrorTracking(builder *flatbuffers.Builder, mirrorTracking bool) {
	builder.PrependBoolSlot(3, mirrorTracking, false)
}
func VMCOSCSettingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
