// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import "strconv"

type VRCAvatarMeasurementType byte

const (
	VRCAvatarMeasurementTypeUNKNOWN  VRCAvatarMeasurementType = 0
	VRCAvatarMeasurementTypeHEIGHT   VRCAvatarMeasurementType = 1
	VRCAvatarMeasurementTypeARM_SPAN VRCAvatarMeasurementType = 2
)

var EnumNamesVRCAvatarMeasurementType = map[VRCAvatarMeasurementType]string{
	VRCAvatarMeasurementTypeUNKNOWN:  "UNKNOWN",
	VRCAvatarMeasurementTypeHEIGHT:   "HEIGHT",
	VRCAvatarMeasurementTypeARM_SPAN: "ARM_SPAN",
}

var EnumValuesVRCAvatarMeasurementType = map[string]VRCAvatarMeasurementType{
	"UNKNOWN":  VRCAvatarMeasurementTypeUNKNOWN,
	"HEIGHT":   VRCAvatarMeasurementTypeHEIGHT,
	"ARM_SPAN": VRCAvatarMeasurementTypeARM_SPAN,
}

func (v VRCAvatarMeasurementType) String() string {
	if s, ok := EnumNamesVRCAvatarMeasurementType[v]; ok {
		return s
	}
	return "VRCAvatarMeasurementType(" + strconv.FormatInt(int64(v), 10) + ")"
}
