// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VRCConfigValidity struct {
	_tab flatbuffers.Table
}

func GetRootAsVRCConfigValidity(buf []byte, offset flatbuffers.UOffsetT) *VRCConfigValidity {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VRCConfigValidity{}
	x.Init(buf, n+offset)
	return x
}

func FinishVRCConfigValidityBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVRCConfigValidity(buf []byte, offset flatbuffers.UOffsetT) *VRCConfigValidity {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VRCConfigValidity{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVRCConfigValidityBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VRCConfigValidity) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VRCConfigValidity) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VRCConfigValidity) LegacyModeOk() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigValidity) MutateLegacyModeOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *VRCConfigValidity) ShoulderTrackingOk() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigValidity) MutateShoulderTrackingOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *VRCConfigValidity) UserHeightOk() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigValidity) MutateUserHeightOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *VRCConfigValidity) CalibrationRangeOk() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigValidity) MutateCalibrationRangeOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *VRCConfigValidity) CalibrationVisualsOk() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigValidity) MutateCalibrationVisualsOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *VRCConfigValidity) TrackerModelOk() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigValidity) MutateTrackerModelOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func (rcv *VRCConfigValidity) SpineModeOk() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigValidity) MutateSpineModeOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func (rcv *VRCConfigValidity) AvatarMeasurementTypeOk() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigValidity) MutateAvatarMeasurementTypeOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(18, n)
}

func (rcv *VRCConfigValidity) ShoulderWidthCompensationOk() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigValidity) MutateShoulderWidthCompensationOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(20, n)
}

func VRCConfigValidityStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func VRCConfigValidityAddLegacyModeOk(builder *flatbuffers.Builder, legacyModeOk bool) {
	builder.PrependBoolSlot(0, legacyModeOk, false)
}
func VRCConfigValidityAddShoulderTrackingOk(builder *flatbuffers.Builder, shoulderTrackingOk bool) {
	builder.PrependBoolSlot(1, shoulderTrackingOk, false)
}
func VRCConfigValidityAddUserHeightOk(builder *flatbuffers.Builder, userHeightOk bool) {
	builder.PrependBoolSlot(2, userHeightOk, false)
}
func VRCConfigValidityAddCalibrationRangeOk(builder *flatbuffers.Builder, calibrationRangeOk bool) {
	builder.PrependBoolSlot(3, calibrationRangeOk, false)
}
func VRCConfigValidityAddCalibrationVisualsOk(builder *flatbuffers.Builder, calibrationVisualsOk bool) {
	builder.PrependBoolSlot(4, calibrationVisualsOk, false)
}
func VRCConfigValidityAddTrackerModelOk(builder *flatbuffers.Builder, trackerModelOk bool) {
	builder.PrependBoolSlot(5, trackerModelOk, false)
}
func VRCConfigValidityAddSpineModeOk(builder *flatbuffers.Builder, spineModeOk bool) {
	builder.PrependBoolSlot(6, spineModeOk, false)
}
func VRCConfigValidityAddAvatarMeasurementTypeOk(builder *flatbuffers.Builder, avatarMeasurementTypeOk bool) {
	builder.PrependBoolSlot(7, avatarMeasurementTypeOk, false)
}
func VRCConfigValidityAddShoulderWidthCompensationOk(builder *flatbuffers.Builder, shoulderWidthCompensationOk bool) {
	builder.PrependBoolSlot(8, shoulderWidthCompensationOk, false)
}
func VRCConfigValidityEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
