// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VRCConfigSettingToggleMute struct {
	_tab flatbuffers.Table
}

func GetRootAsVRCConfigSettingToggleMute(buf []byte, offset flatbuffers.UOffsetT) *VRCConfigSettingToggleMute {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VRCConfigSettingToggleMute{}
	x.Init(buf, n+offset)
	return x
}

func FinishVRCConfigSettingToggleMuteBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVRCConfigSettingToggleMute(buf []byte, offset flatbuffers.UOffsetT) *VRCConfigSettingToggleMute {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VRCConfigSettingToggleMute{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVRCConfigSettingToggleMuteBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VRCConfigSettingToggleMute) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VRCConfigSettingToggleMute) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VRCConfigSettingToggleMute) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func VRCConfigSettingToggleMuteStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func VRCConfigSettingToggleMuteAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func VRCConfigSettingToggleMuteEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
