// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VRCConfigValues struct {
	_tab flatbuffers.Table
}

func GetRootAsVRCConfigValues(buf []byte, offset flatbuffers.UOffsetT) *VRCConfigValues {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VRCConfigValues{}
	x.Init(buf, n+offset)
	return x
}

func FinishVRCConfigValuesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVRCConfigValues(buf []byte, offset flatbuffers.UOffsetT) *VRCConfigValues {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VRCConfigValues{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVRCConfigValuesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VRCConfigValues) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VRCConfigValues) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VRCConfigValues) LegacyMode() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigValues) MutateLegacyMode(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *VRCConfigValues) ShoulderTrackingDisabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigValues) MutateShoulderTrackingDisabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *VRCConfigValues) UserHeight() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *VRCConfigValues) MutateUserHeight(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *VRCConfigValues) CalibrationRange() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *VRCConfigValues) MutateCalibrationRange(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *VRCConfigValues) CalibrationVisuals() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigValues) MutateCalibrationVisuals(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *VRCConfigValues) TrackerModel() VRCTrackerModel {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return VRCTrackerModel(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *VRCConfigValues) MutateTrackerModel(n VRCTrackerModel) bool {
	return rcv._tab.MutateByteSlot(14, byte(n))
}

func (rcv *VRCConfigValues) SpineMode() VRCSpineMode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return VRCSpineMode(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *VRCConfigValues) MutateSpineMode(n VRCSpineMode) bool {
	return rcv._tab.MutateByteSlot(16, byte(n))
}

func (rcv *VRCConfigValues) AvatarMeasurementType() VRCAvatarMeasurementType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return VRCAvatarMeasurementType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *VRCConfigValues) MutateAvatarMeasurementType(n VRCAvatarMeasurementType) bool {
	return rcv._tab.MutateByteSlot(18, byte(n))
}

func (rcv *VRCConfigValues) ShoulderWidthCompensation() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigValues) MutateShoulderWidthCompensation(n bool) bool {
	return rcv._tab.MutateBoolSlot(20, n)
}

func VRCConfigValuesStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func VRCConfigValuesAddLegacyMode(builder *flatbuffers.Builder, legacyMode bool) {
	builder.PrependBoolSlot(0, legacyMode, false)
}
func VRCConfigValuesAddShoulderTrackingDisabled(builder *flatbuffers.Builder, shoulderTrackingDisabled bool) {
	builder.PrependBoolSlot(1, shoulderTrackingDisabled, false)
}
func VRCConfigValuesAddUserHeight(builder *flatbuffers.Builder, userHeight float32) {
	builder.PrependFloat32Slot(2, userHeight, 0.0)
}
func VRCConfigValuesAddCalibrationRange(builder *flatbuffers.Builder, calibrationRange float32) {
	builder.PrependFloat32Slot(3, calibrationRange, 0.0)
}
func VRCConfigValuesAddCalibrationVisuals(builder *flatbuffers.Builder, calibrationVisuals bool) {
	builder.PrependBoolSlot(4, calibrationVisuals, false)
}
func VRCConfigValuesAddTrackerModel(builder *flatbuffers.Builder, trackerModel VRCTrackerModel) {
	builder.PrependByteSlot(5, byte(trackerModel), 0)
}
func VRCConfigValuesAddSpineMode(builder *flatbuffers.Builder, spineMode VRCSpineMode) {
	builder.PrependByteSlot(6, byte(spineMode), 0)
}
func VRCConfigValuesAddAvatarMeasurementType(builder *flatbuffers.Builder, avatarMeasurementType VRCAvatarMeasurementType) {
	builder.PrependByteSlot(7, byte(avatarMeasurementType), 0)
}
func VRCConfigValuesAddShoulderWidthCompensation(builder *flatbuffers.Builder, shoulderWidthCompensation bool) {
	builder.PrependBoolSlot(8, shoulderWidthCompensation, false)
}
func VRCConfigValuesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
