// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VRCConfigRecommendedValues struct {
	_tab flatbuffers.Table
}

func GetRootAsVRCConfigRecommendedValues(buf []byte, offset flatbuffers.UOffsetT) *VRCConfigRecommendedValues {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VRCConfigRecommendedValues{}
	x.Init(buf, n+offset)
	return x
}

func FinishVRCConfigRecommendedValuesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVRCConfigRecommendedValues(buf []byte, offset flatbuffers.UOffsetT) *VRCConfigRecommendedValues {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VRCConfigRecommendedValues{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVRCConfigRecommendedValuesBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VRCConfigRecommendedValues) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VRCConfigRecommendedValues) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VRCConfigRecommendedValues) LegacyMode() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigRecommendedValues) MutateLegacyMode(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *VRCConfigRecommendedValues) ShoulderTrackingDisabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigRecommendedValues) MutateShoulderTrackingDisabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *VRCConfigRecommendedValues) UserHeight() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *VRCConfigRecommendedValues) MutateUserHeight(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *VRCConfigRecommendedValues) CalibrationRange() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *VRCConfigRecommendedValues) MutateCalibrationRange(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *VRCConfigRecommendedValues) CalibrationVisuals() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigRecommendedValues) MutateCalibrationVisuals(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *VRCConfigRecommendedValues) TrackerModel() VRCTrackerModel {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return VRCTrackerModel(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *VRCConfigRecommendedValues) MutateTrackerModel(n VRCTrackerModel) bool {
	return rcv._tab.MutateByteSlot(14, byte(n))
}

func (rcv *VRCConfigRecommendedValues) SpineMode(j int) VRCSpineMode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return VRCSpineMode(rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1)))
	}
	return 0
}

func (rcv *VRCConfigRecommendedValues) SpineModeLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *VRCConfigRecommendedValues) SpineModeBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *VRCConfigRecommendedValues) MutateSpineMode(j int, n VRCSpineMode) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), byte(n))
	}
	return false
}

func (rcv *VRCConfigRecommendedValues) AvatarMeasurementType() VRCAvatarMeasurementType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return VRCAvatarMeasurementType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *VRCConfigRecommendedValues) MutateAvatarMeasurementType(n VRCAvatarMeasurementType) bool {
	return rcv._tab.MutateByteSlot(18, byte(n))
}

func (rcv *VRCConfigRecommendedValues) ShoulderWidthCompensation() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCConfigRecommendedValues) MutateShoulderWidthCompensation(n bool) bool {
	return rcv._tab.MutateBoolSlot(20, n)
}

func VRCConfigRecommendedValuesStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func VRCConfigRecommendedValuesAddLegacyMode(builder *flatbuffers.Builder, legacyMode bool) {
	builder.PrependBoolSlot(0, legacyMode, false)
}
func VRCConfigRecommendedValuesAddShoulderTrackingDisabled(builder *flatbuffers.Builder, shoulderTrackingDisabled bool) {
	builder.PrependBoolSlot(1, shoulderTrackingDisabled, false)
}
func VRCConfigRecommendedValuesAddUserHeight(builder *flatbuffers.Builder, userHeight float32) {
	builder.PrependFloat32Slot(2, userHeight, 0.0)
}
func VRCConfigRecommendedValuesAddCalibrationRange(builder *flatbuffers.Builder, calibrationRange float32) {
	builder.PrependFloat32Slot(3, calibrationRange, 0.0)
}
func VRCConfigRecommendedValuesAddCalibrationVisuals(builder *flatbuffers.Builder, calibrationVisuals bool) {
	builder.PrependBoolSlot(4, calibrationVisuals, false)
}
func VRCConfigRecommendedValuesAddTrackerModel(builder *flatbuffers.Builder, trackerModel VRCTrackerModel) {
	builder.PrependByteSlot(5, byte(trackerModel), 0)
}
func VRCConfigRecommendedValuesAddSpineMode(builder *flatbuffers.Builder, spineMode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(spineMode), 0)
}
func VRCConfigRecommendedValuesStartSpineModeVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func VRCConfigRecommendedValuesAddAvatarMeasurementType(builder *flatbuffers.Builder, avatarMeasurementType VRCAvatarMeasurementType) {
	builder.PrependByteSlot(7, byte(avatarMeasurementType), 0)
}
func VRCConfigRecommendedValuesAddShoulderWidthCompensation(builder *flatbuffers.Builder, shoulderWidthCompensation bool) {
	builder.PrependBoolSlot(8, shoulderWidthCompensation, false)
}
func VRCConfigRecommendedValuesEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
