// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VRCConfigStateRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsVRCConfigStateRequest(buf []byte, offset flatbuffers.UOffsetT) *VRCConfigStateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VRCConfigStateRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishVRCConfigStateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVRCConfigStateRequest(buf []byte, offset flatbuffers.UOffsetT) *VRCConfigStateRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VRCConfigStateRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVRCConfigStateRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VRCConfigStateRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VRCConfigStateRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func VRCConfigStateRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func VRCConfigStateRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
