// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / OSC Settings specific to VRChat
type VRCOSCSettings struct {
	_tab flatbuffers.Table
}

func GetRootAsVRCOSCSettings(buf []byte, offset flatbuffers.UOffsetT) *VRCOSCSettings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VRCOSCSettings{}
	x.Init(buf, n+offset)
	return x
}

func FinishVRCOSCSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVRCOSCSettings(buf []byte, offset flatbuffers.UOffsetT) *VRCOSCSettings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VRCOSCSettings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVRCOSCSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VRCOSCSettings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VRCOSCSettings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VRCOSCSettings) OscSettings(obj *OSCSettings) *OSCSettings {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(OSCSettings)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *VRCOSCSettings) Trackers(obj *OSCTrackersSetting) *OSCTrackersSetting {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(OSCTrackersSetting)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *VRCOSCSettings) OscqueryEnabled() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VRCOSCSettings) MutateOscqueryEnabled(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func VRCOSCSettingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func VRCOSCSettingsAddOscSettings(builder *flatbuffers.Builder, oscSettings flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(oscSettings), 0)
}
func VRCOSCSettingsAddTrackers(builder *flatbuffers.Builder, trackers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(trackers), 0)
}
func VRCOSCSettingsAddOscqueryEnabled(builder *flatbuffers.Builder, oscqueryEnabled bool) {
	builder.PrependBoolSlot(2, oscqueryEnabled, false)
}
func VRCOSCSettingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
