// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import "strconv"

type VRCSpineMode byte

const (
	VRCSpineModeUNKNOWN   VRCSpineMode = 0
	VRCSpineModeLOCK_HIP  VRCSpineMode = 1
	VRCSpineModeLOCK_HEAD VRCSpineMode = 2
	VRCSpineModeLOCK_BOTH VRCSpineMode = 3
)

var EnumNamesVRCSpineMode = map[VRCSpineMode]string{
	VRCSpineModeUNKNOWN:   "UNKNOWN",
	VRCSpineModeLOCK_HIP:  "LOCK_HIP",
	VRCSpineModeLOCK_HEAD: "LOCK_HEAD",
	VRCSpineModeLOCK_BOTH: "LOCK_BOTH",
}

var EnumValuesVRCSpineMode = map[string]VRCSpineMode{
	"UNKNOWN":   VRCSpineModeUNKNOWN,
	"LOCK_HIP":  VRCSpineModeLOCK_HIP,
	"LOCK_HEAD": VRCSpineModeLOCK_HEAD,
	"LOCK_BOTH": VRCSpineModeLOCK_BOTH,
}

func (v VRCSpineMode) String() string {
	if s, ok := EnumNamesVRCSpineMode[v]; ok {
		return s
	}
	return "VRCSpineMode(" + strconv.FormatInt(int64(v), 10) + ")"
}
