// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import "strconv"

type VRCTrackerModel byte

const (
	VRCTrackerModelUNKNOWN VRCTrackerModel = 0
	VRCTrackerModelSPHERE  VRCTrackerModel = 1
	VRCTrackerModelSYSTEM  VRCTrackerModel = 2
	VRCTrackerModelBOX     VRCTrackerModel = 3
	VRCTrackerModelAXIS    VRCTrackerModel = 4
)

var EnumNamesVRCTrackerModel = map[VRCTrackerModel]string{
	VRCTrackerModelUNKNOWN: "UNKNOWN",
	VRCTrackerModelSPHERE:  "SPHERE",
	VRCTrackerModelSYSTEM:  "SYSTEM",
	VRCTrackerModelBOX:     "BOX",
	VRCTrackerModelAXIS:    "AXIS",
}

var EnumValuesVRCTrackerModel = map[string]VRCTrackerModel{
	"UNKNOWN": VRCTrackerModelUNKNOWN,
	"SPHERE":  VRCTrackerModelSPHERE,
	"SYSTEM":  VRCTrackerModelSYSTEM,
	"BOX":     VRCTrackerModelBOX,
	"AXIS":    VRCTrackerModelAXIS,
}

func (v VRCTrackerModel) String() string {
	if s, ok := EnumNamesVRCTrackerModel[v]; ok {
		return s
	}
	return "VRCTrackerModel(" + strconv.FormatInt(int64(v), 10) + ")"
}
