// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

// / VRM Settings for rescaling to avatar-scale
type VRMSettings struct {
	_tab flatbuffers.Table
}

func GetRootAsVRMSettings(buf []byte, offset flatbuffers.UOffsetT) *VRMSettings {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VRMSettings{}
	x.Init(buf, n+offset)
	return x
}

func FinishVRMSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVRMSettings(buf []byte, offset flatbuffers.UOffsetT) *VRMSettings {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VRMSettings{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVRMSettingsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VRMSettings) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VRMSettings) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VRMSettings) VrmJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func VRMSettingsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func VRMSettingsAddVrmJson(builder *flatbuffers.Builder, vrmJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(vrmJson), 0)
}
func VRMSettingsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
