// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WifiProvisioningStatusResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsWifiProvisioningStatusResponse(buf []byte, offset flatbuffers.UOffsetT) *WifiProvisioningStatusResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WifiProvisioningStatusResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishWifiProvisioningStatusResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWifiProvisioningStatusResponse(buf []byte, offset flatbuffers.UOffsetT) *WifiProvisioningStatusResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WifiProvisioningStatusResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWifiProvisioningStatusResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *WifiProvisioningStatusResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WifiProvisioningStatusResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WifiProvisioningStatusResponse) Status() WifiProvisioningStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return WifiProvisioningStatus(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *WifiProvisioningStatusResponse) MutateStatus(n WifiProvisioningStatus) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func WifiProvisioningStatusResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func WifiProvisioningStatusResponseAddStatus(builder *flatbuffers.Builder, status WifiProvisioningStatus) {
	builder.PrependByteSlot(0, byte(status), 0)
}
func WifiProvisioningStatusResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
